### ISSUE TITLE
[rock-dkms-git] should be removed

### ISSUE THREAD

**Issue by ranisalt** [rocm-arch/rocm-arch#108]
Both `rock-dkms` and `rock-dkms-git` generate the same package, I don't know why the latter was created and it should probably be removed.

**Comment by acxz** [comment]
Instead of removing it we can update it to just use the upstream sources: https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver

**Comment by acxz** [comment]
See: #29

**Comment by ranisalt** [comment]
That is a very good suggestion indeed; I don't know how to work with dkms, though.
