### ISSUE TITLE
[libhsakmt-git] should be removed

### ISSUE THREAD

**Issue by ranisalt** [rocm-arch/rocm-arch#109]
This package pulls from an extremely outdated (4 years) and abandoned repository for `hsakmt-roct`. Development moved to a new repository that the latter already follows. Should remove the former package then.

**Comment by acxz** [comment]
Good point, can you submit a deletion request at https://aur.archlinux.org/packages/libhsakmt-git?

**Comment by ranisalt** [comment]
Done. When it's accepted, I'll remove the packages here then :)

**Comment by lordheavy** [comment]
Package removed!

**Comment by rigred** [comment]
Great.
With that I close this issue.
