### ISSUE TITLE
packages that need to be synced

### ISSUE THREAD

**Issue by acxz** [rocm-arch/rocm-arch#124]
- [x] hipblas
- [x] hipcub
- [x] hipsparse
- [x] rocalution
- [x] rocblas
- [x] rocprim
- [x] rocthrust
- [x] miopen
- [x] llvm-amdgpu
- [x] comgr
- [x] rccl
- [x] rocrand
- [x] rocm-device-libs

**Comment by notcome** [comment]
Is this related to renaming packages? I am in the middle of building things and found that we have conflicted packages like `rocm-clang-ocl` and `clang-ocl`. I suppose I should better hold off installing ROCm until this is resolved?

**Comment by acxz** [comment]
That specific conflict should be resolved, now.

**Comment by thx1111** [comment]
Still, with rocm-comgr 3.3.0-3 installed:
```
Package (1)  New Version  Net Change

comgr        3.3.0-1       60.03 MiB
...
(1/1) checking for file conflicts                                    [######################################] 100%
error: failed to commit transaction (conflicting files)
comgr: /opt/rocm/include/amd_comgr.h exists in filesystem (owned by rocm-comgr)
comgr: /opt/rocm/include/opencl1.2-c.pch exists in filesystem (owned by rocm-comgr)
comgr: /opt/rocm/include/opencl2.0-c.pch exists in filesystem (owned by rocm-comgr)
comgr: /opt/rocm/lib/cmake/amd_comgr/amd_comgr-config-version.cmake exists in filesystem (owned by rocm-comgr)
comgr: /opt/rocm/lib/cmake/amd_comgr/amd_comgr-config.cmake exists in filesystem (owned by rocm-comgr)
comgr: /opt/rocm/lib/cmake/amd_comgr/amd_comgr-targets-noconfig.cmake exists in filesystem (owned by rocm-comgr)
comgr: /opt/rocm/lib/cmake/amd_comgr/amd_comgr-targets.cmake exists in filesystem (owned by rocm-comgr)
comgr: /opt/rocm/lib/libamd_comgr.so exists in filesystem (owned by rocm-comgr)
comgr: /opt/rocm/lib/libamd_comgr.so.1 exists in filesystem (owned by rocm-comgr)
comgr: /opt/rocm/lib/libamd_comgr.so.1.6 exists in filesystem (owned by rocm-comgr)
comgr: /opt/rocm/share/amd_comgr/LICENSE.txt exists in filesystem (owned by rocm-comgr)
comgr: /opt/rocm/share/amd_comgr/NOTICES.txt exists in filesystem (owned by rocm-comgr)
comgr: /opt/rocm/share/amd_comgr/README.md exists in filesystem (owned by rocm-comgr)
Errors occurred, no packages were upgraded.
```
Which package is at fault?

**Comment by notcome** [comment]
> Still, with rocm-comgr 3.3.0-3 installed:
> 
> ```
> Package (1)  New Version  Net Change
> 
> comgr        3.3.0-1       60.03 MiB
> ...
> (1/1) checking for file conflicts                                    [######################################] 100%
> error: failed to commit transaction (conflicting files)
> comgr: /opt/rocm/include/amd_comgr.h exists in filesystem (owned by rocm-comgr)
> comgr: /opt/rocm/include/opencl1.2-c.pch exists in filesystem (owned by rocm-comgr)
> comgr: /opt/rocm/include/opencl2.0-c.pch exists in filesystem (owned by rocm-comgr)
> comgr: /opt/rocm/lib/cmake/amd_comgr/amd_comgr-config-version.cmake exists in filesystem (owned by rocm-comgr)
> comgr: /opt/rocm/lib/cmake/amd_comgr/amd_comgr-config.cmake exists in filesystem (owned by rocm-comgr)
> comgr: /opt/rocm/lib/cmake/amd_comgr/amd_comgr-targets-noconfig.cmake exists in filesystem (owned by rocm-comgr)
> comgr: /opt/rocm/lib/cmake/amd_comgr/amd_comgr-targets.cmake exists in filesystem (owned by rocm-comgr)
> comgr: /opt/rocm/lib/libamd_comgr.so exists in filesystem (owned by rocm-comgr)
> comgr: /opt/rocm/lib/libamd_comgr.so.1 exists in filesystem (owned by rocm-comgr)
> comgr: /opt/rocm/lib/libamd_comgr.so.1.6 exists in filesystem (owned by rocm-comgr)
> comgr: /opt/rocm/share/amd_comgr/LICENSE.txt exists in filesystem (owned by rocm-comgr)
> comgr: /opt/rocm/share/amd_comgr/NOTICES.txt exists in filesystem (owned by rocm-comgr)
> comgr: /opt/rocm/share/amd_comgr/README.md exists in filesystem (owned by rocm-comgr)
> Errors occurred, no packages were upgraded.
> ```
> 
> Which package is at fault?

My understanding is that there is some sort of name changing lately so comgr was rocm-comgr. What I did was removing all packages and recompile using PKGBUILDs from this repo. Everything went smoothly.

**Comment by thx1111** [comment]
> My understanding is that there is some sort of name changing lately so comgr was rocm-comgr.

Thanks for the note.  Hmm - that seems unfortunate, since `pacman -Qs rocm` can no longer be used to discover all of the rocm packages.  But then, the hsakmt-roct package also fails to show in those results.  What is the point of the name change?  Gratuitously removing *all* packages, and recompiling - and without any instruction that this is *necessary* - itself seems overly "heavy-handed".

I see that the rocm-opencl-runtime package has changed the "Depends On" list, replacing "rocm-comgr" with just "comgr".  This can leave the rocm-comgr package as a "not required" package, with no explicit communication that the rocm-comgr package should be removed.  It is not at all clear, to the casual observer, that one package is replacing another, or specifically, *which* package is replacing *which*.

The rocm-comgr package should be made a "Conflicts With" of the comgr package.  Or better, the package name change should simply be reverted.

**Comment by acxz** [comment]
@farnoy @ranisalt @naetherm @neeshy can you guys take a look at these packages and try to sync them?

**Comment by ranisalt** [comment]
I updated most of them, the others I don't have access.

**Comment by thx1111** [comment]
Maybe make sure that the string "rocm" is used or included in the descriptions of all of the related packages, so that `pacman -Qs rocm` or `pacman -Ss rocm` will immediately find them all?

**Comment by acxz** [comment]
That seems like a good idea, we could also create a ‘rocm’ group. In any case, feel free to create PRs about this! ;)

**Comment by farnoy** [comment]
Sorry about being a blocker here, I'll go ahead and disown my packages, but first I need to reorder my co-maintainer list.

**Comment by farnoy** [comment]
Ok that didn't take very long, @acxz you're now the maintainer of these packages:
* rocrand
* clang-ocl
* hcc
* hip
* miopen
* miopengemm
* rocfft
* rocm-cmake-git
* rocminfo

**Comment by acxz** [comment]
Sweet thank you so much!!

**Comment by acxz** [comment]
@ranisalt @naetherm can you take a look at these packages to sync once more?
