### ISSUE TITLE
[llvm-roc] Deprecate in favour of llvm-amdgpu

### ISSUE THREAD

**Issue by tpkessler** [rocm-arch/rocm-arch#129]
`llvm-roc` never had a matching debian package but `llvm-amdgpu` does. Shouldn't the latter replace `llvm-roc`?

**Comment by acxz** [comment]
So the ubuntu llvm-amdgpu package does not contain the header files needed for some compilation. In that sense, they are supposed to be different, but the llvm-amdgpu we ship does have these header files.
Saying that yeah it makes sense to just have llvm-amdgpu replace llvm-roc. I'm in favor of this.

**Comment by ranisalt** [comment]
I can't use anything build with `llvm-amdgpu`. `clinfo` segfaults. It was working with `llvm-roc`, please check the flags.

**Comment by acxz** [comment]
With #131 clinfo works for me.

**Comment by acxz** [comment]
Should be resolved once the packages in #124 get synced.

**Comment by acxz** [comment]
I have made a merge request for this package. Once it is approved we can remove it from this repo.

**Comment by tpkessler** [comment]
Great! I'll leave it open until the package is removed.

**Comment by acxz** [comment]
We can now close this with: 
3faa69f
