### ISSUE TITLE
[python-pytorch-rocm] Compiling and running PyTorch with ROCm on Archlinux

### ISSUE THREAD

**Issue by s-bernard** [rocm-arch/rocm-arch#135]
Hi everyone,

First, thanks a lot for maintaining the ROCm packages, it's not easy and you're doing a great job.

A week ago, I decided to try PyTorch with ROCm on my Arch so I began the compilation process. Then it failed, I found a way to remove the error, then it failed again, I fixed it, then again, etc.
I finally succeeded to have a working* version so I've compiled all the patches I did to share them with you.

PR #134 : PyTorch depends on most of the ROCm stack, so I needed to update everything to 3.3.0

PR #132 : one library way more complicated to upgrade was MIOpen. The raison is it needs rocblas with tensile. But compiling rocblas with tensile was quite a journey.

PR #133 : PyTorch build failed a few times because some include files were not found. By looking at ubuntu docker, I found that most of them were symlinks in `/opt/rocm/include`.

PR: #131 : The most tricky error was at runtime, with an LLVM error `:CommandLine Error: Option 'disable-symbolication' registered more than once!`. After some digging, comparing with ubuntu docker which was working fine, I found that my version of PyTorch was linked to a ROCm LLVM library, Ubuntu was not.
So I looked at llvm-roc and found that it builds and links DYLIB, which was the shared library linked to PyTorch. I compiled LLVM without it, same for Comgr and the problem was solved. Bonus, llvm-roc (or llvm-amdgpu) is not needed after Comgr is built.

Finally, there is still an issue for which I do not have a PR yet. Due to capitalization mixup in project names (hip/HIP, hcc/HCC, …), in the cmake files, some project cannot be found when you launch cmake on PyTorch. With some patches on PyTorch, I improved the situation but at the end, I still needed to edit the cmake files of subproject (like `/opt/rocm/rccl/lib/cmake/rccl/rccl-config.cmake`) to change `find_dependency(hip)` by `find_dependency(HIP)`

Thanks.

*I still have issues on some *cuda* tests, I'll find a way ;)

**Comment by s-bernard** [comment]
BTW, I did 4 PRs to simplify the review process, you can accept them in any order. Actually, all commits are independent and can even be sherry-picked.

**Comment by acxz** [comment]
Sweet this is really amazing. Thanks for this thorough investigation process! I'm a bit busy this week, but we will try to get these PRs merged and packaged through arch4edu.

**Comment by s-bernard** [comment]
I was thinking about writing the PKGBUILD for pytorch, do you think it is better to put it on this repository?

**Comment by acxz** [comment]
Yeah it think it makes more sense for the PKGBUILD to live here, since it makes tracking issues and PRs much easier.

**Comment by s-bernard** [comment]
OK, it confirms what I was thinking. I'll probably do a PR in the next days.

**Comment by notcome** [comment]
When compiling `rocblas` I am getting complaints about cannot find LLVM's CMake file. Setting `LLVM_DIR` appears to solve the issue `/opt/rocm/llvm/lib/cmake/llvm/`. Do you guys have encountered this?

**Comment by notcome** [comment]
Two additional issue while compiling rocblas.

First, `hipconfig` is not inside $PATH. Should it be installed to `/usr/bin` or should we set a temporary $PATH variable?

Second, `kernelextract` complains about:

```
Can't locate File/Which.pm in @INC (you may need to install the File::Which module) (@INC contains: /usr/lib/perl5/5.30/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/5.30/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/5.30/core_perl /usr/share/perl5/core_perl) at /usr/bin/extractkernel line 6.
BEGIN failed--compilation aborted at /usr/bin/extractkernel line 6.
```

I am not familiar with Perl at all. Lets say if I could install the said module.

**Comment by notcome** [comment]
Just to confirm here that after exposing hipconfig via PATH, setting LLVM_DIR, and installing `pacman -S perl-file-which`, I have successfully compiled rocblas. Now heading to MIOpen, and hopefully Tensorflow would work.

**Comment by s-bernard** [comment]
Strange about hipconfig in the PATH, it should be done in c0c9ecf (or the equivalent for hip).

For rocblas and LLVM_DIR, I think you actually does not need llvm-gpu, so regular system llvm works. It should probably added as dependency.

**Comment by s-bernard** [comment]
@notcome The strangest issue I have with PyTorch is https://github.com/ROCmSoftwarePlatform/pytorch/issues/639.

**Comment by s-bernard** [comment]
OK, I get it for hipconfig, I made a stupid typo!

**Comment by s-bernard** [comment]
BTW, I compiled pytorch within a ubuntu docker and all official packages. I had to apply the same patches to PyTorch and some cmake files. Thus what is done here is really good.

**Comment by chiboreache** [comment]
hey, i also trying to compile it with ROCm key enabled, but having an error




```sh
:: Downloading the latest sources for a devel package python-pytorch-cuda-git...

:: Starting the build:
==> Making package: python-pytorch-git 1.3.1.r27598.30364f0b016-1 (Thu Jun 18 04:13:03 2020)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
-> Updating pytorch git repo...
Fetching origin
==> Validating source files with sha512sums...
pytorch ... Skipped
==> Extracting sources...
-> Creating working copy of pytorch git repo...
Reset branch 'makepkg'
==> Starting prepare()...
==> Starting pkgver()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
Building without cuda and without MKL-DNN
Building wheel torch-1.3.1
-- Building version 1.3.1
cmake --build . --target install --config Release -- -j 8
make: *** No rule to make target 'install'.  Stop.
Traceback (most recent call last):
File "setup.py", line 732, in <module>
build_deps()
File "setup.py", line 311, in build_deps
build_caffe2(version=version,
File "/home/chibo/.cache/pikaur/build/python-pytorch-git/src/pytorch-git/tools/build_pytorch_libs.py", line 62, in build_caffe2
cmake.build(my_env)
File "/home/chibo/.cache/pikaur/build/python-pytorch-git/src/pytorch-git/tools/setup_helpers/cmake.py", line 345, in build
self.run(build_args, my_env)
File "/home/chibo/.cache/pikaur/build/python-pytorch-git/src/pytorch-git/tools/setup_helpers/cmake.py", line 141, in run
check_call(command, cwd=self.build_dir, env=env)
File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j','8']' returned non-zero exit status 2.
==> ERROR: A failure occurred in build().
Aborting...
```

_not sure that is right tread, but whatever_

**Comment by tpkessler** [comment]
Hey @chiboreache could you please open a separate issue on this and provide more information regarding your setup and the PKGBUILD you use? I don't understand what you mean with "ROCm key enabled" as you're cloning `python-pytorch-cuda-git`?

**Comment by chiboreache** [comment]
>could you please open a separate issue

i guess i have the same problem exposed in this issue, but if you think creating new issue are necessary, let me know


>PKGBUILD

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-pytorch-git

>what you mean with "ROCm key enabled" 

i edit PKGBUILD `export USE_ROCM=ON` before compilation


>setup

 ```sh
↪ python collect_env.py
Collecting environment information...
PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Arch Linux
GCC version: (GCC) 10.1.0
CMake version: version 3.17.3

Python version: 3.8
Is CUDA available: No
CUDA runtime version: 10.2.89
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: /usr/lib/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.5.0
[pip3] torchvision==0.6.0
[conda] Could not collect
```

**Comment by tpkessler** [comment]
We do not maintain the pytorch package, so I don't think that we can help you here. From your log files it seems like it fails at the very beginning of the build process:
> `make: *** No rule to make target 'install'.  Stop.`

So your problem is not related to the ROCm stack. 

It's better to open a separate issue for your problems. This one is an announcement for a series of PRs, not a collection of build errors for pytorch. I'm closing this one. If you still have problems, feel free to open up a new one.
