### ISSUE TITLE
[rocblas] Possible memory leak building rocblas

### ISSUE THREAD

**Issue by helfio** [rocm-arch/rocm-arch#137]
Hi,

I'm trying to build the whole stack, but I got into a problem here. Building rocblas it seems to be a memory leak since clang10 process grows up to all the ram it can eats (I have 16GB) and I'd say the whole swap as well (it got up to 15 of my 20 GB). Any idea how to solve this?

In case it is realted, before doing this, I was trying to build it with hip package, but I saw some commits on hip-hcc and changed to that package. This previous attempt was unsuccessful since Tensile throwed a few typeerrors.

My GPU is a RX590 and I have the deps listed in the PKGBUILD. Let me know in case you need further info.

Thanks,
Pablo.

**Comment by tpkessler** [comment]
Hey Pablo,

it's not a bug, it's a feature. I need 50 GB RAM to compile `rocblas`. If you need more RAM you may create a swapfile:

https://wiki.archlinux.org/index.php/swap#Swap_file

**Comment by helfio** [comment]
Oh! Ok, I'll grow my swapfile.
Thank you!

**Comment by helfio** [comment]
It did the trick. Thank you @tpkessler !
