### ISSUE TITLE
[rocm-opencl-runtime] either rocm-device-libs or llvm-roc is runtime dependency, not make

### ISSUE THREAD

**Issue by mighty9245** [rocm-arch/rocm-arch#147]
i was manually installing `rocm-opencl-runtime` (without an aur helper) and after successful installation decided to do a little cleanup - i moved all packages to dependencies and left `rocm-opencl-runtime` explicitly installed, but i noticed that nothing depends on two packages - `rocm-device-libs` and `llvm-roc`, they are make dependencies. i assume that i can delete make dependencies after successful build? i did so. on the next day i noticed that `clinfo` segfaults. installing these packages back fixed the issue. so i assume they are runtime dependencies, not make? or one of these packages?

**Comment by acxz** [comment]
Thx for reporting! Feel free to make a PR resolving this.

**Comment by mighty9245** [comment]
well, here is what i have:
![image](https://user-images.githubusercontent.com/52252283/81008938-6c19ff80-8e5c-11ea-9675-2230dcc0c003.png)

**Comment by acxz** [comment]
Hmm weird indeed
also for reference please post the output in text form so we can search it instead of an image.

**Comment by kode54** [comment]
I have removed those two packages from my system, and clinfo still works. I can send the clinfo output later, when I'm back in Linux.

**Comment by mighty9245** [comment]
i'm not sure if it's the cause, but as i said before, i was manually installing `rocm-opencl-runtime`, basically installing things as `makepkg` complained, here is the order:
```
[2020-04-28T21:08:43+0300] [ALPM] installed hashcat (1:5.1.0-1)
[2020-04-28T22:52:30+0300] [ALPM] installed clinfo (2.2.18.04.06-1)
[2020-04-28T22:55:21+0300] [ALPM] installed numactl (2.0.13-3)
[2020-04-28T22:55:40+0300] [ALPM] installed hsakmt-roct (3.3.0-1)
[2020-04-28T23:03:05+0300] [ALPM] installed hsa-rocr (3.3.0-5)
[2020-04-28T23:08:26+0300] [ALPM] installed rocm-cmake (3.3.0-1)
[2020-04-28T23:08:58+0300] [ALPM] installed z3 (4.8.7-1)
[2020-04-29T00:07:03+0300] [ALPM] installed llvm-amdgpu (3.3.0-1)
[2020-04-29T01:09:51+0300] [ALPM] installed llvm-roc (3.3.0-2)
[2020-04-29T01:12:44+0300] [ALPM] installed rocm-device-libs (3.3.0-2)
[2020-04-29T01:15:52+0300] [ALPM] installed comgr (3.3.0-1)
[2020-04-29T01:19:20+0300] [ALPM] installed rocm-opencl-runtime (3.3.0-6)```

another thing is that only `clinfo` provided by arch repositories segfaults:
```
workstation:~$ clinfo
Segmentation fault (core dumped)
workstation:~$ /opt/rocm/bin/x86_64/clinfo
Number of platforms:				 1
  Platform Profile:				 FULL_PROFILE
  Platform Version:				 OpenCL 2.0 AMD-APP.internal.dbg (3098.0)
  Platform Name:				 AMD Accelerated Parallel Processing
  Platform Vendor:				 Advanced Micro Devices, Inc.
  Platform Extensions:				 cl_khr_icd cl_amd_object_metadata cl_amd_event_callback 


  Platform Name:				 AMD Accelerated Parallel Processing
ERROR: clGetDeviceIDs(-1)
```

clinfo is not the real problem though, it's just an example. hashcat, for which i installed all this stuff, segfaults as well.

**Comment by kode54** [comment]
As I was about to say, `rocm-device-libs` is a make dependency of `comgr`, but not listed as a regular dependency. You may wish to check your packages for updates, as a semi-recent update to `llvm-amdgpu` disabled some dynamic libraries option, so the resulting `rocm-device-libs` and `comgr` should statically link the compiler bits they need now.

**Comment by acxz** [comment]
Based on kode54's comment, @mighty9245 you seem to have outdated llvm-amdgpu and comgr versions. Please update them and try again. Instead of manually installing the packages, we recommend you use an AUR helper such as `yay`. Also the arch4edu is hosting binary versions of most of these pkgbuilds. See: https://wiki.archlinux.org/index.php/Unofficial_user_repositories#arch4edu

**Comment by mighty9245** [comment]
looks like you forgot to update `rocm-device-libs` package on aur. it still has `llvm-roc` as make dependency, but `llvm-roc` doesn't exist as a package anymore. can't reinstall right now.
![image](https://user-images.githubusercontent.com/52252283/81339246-818a6600-90b6-11ea-9cb3-ddb90f65185b.png)

**Comment by acxz** [comment]
See: https://github.com/rocm-arch/rocm-arch/issues/124

@ranisalt @neeshy can you guys take a look at this?

**Comment by mighty9245** [comment]
got you, won't it be a problem if i'll wait for sync and then reinstall all the stuff and report back about my issue?

**Comment by ranisalt** [comment]
rocm-device-libs has been updated

**Comment by mighty9245** [comment]
ok, i reinstalled all the stuff, moved all the things except `rocm-opencl-runtime` to dependencies and uninstalled unneeded and everything works now. thanks!

btw, thank you for all your job on rocm stack. you're doing really great job for all lazy people who just want to install things and get them running like me :)
