### ISSUE TITLE
[rocm-device-libs] Missing required package llvm-roc

### ISSUE THREAD

**Issue by HeroCC** [rocm-arch/rocm-arch#154]
I saw some discussion elsewhere about packages not being synced, so apologies if this is already known. Nonetheless, I tried to install `rocm-opencl-runtime` just now, and was unable to, it looks like `rocm-device-libs` depends on the package `llvm-roc`, which doesn't exist anywhere I can find it. Any support would be greatly appreciated, thank you!

**Comment by HeroCC** [comment]
Did a bit more searching, looks like this was fixed in #142, but hasn't been synced to the aur yet (#124).

**Comment by ranisalt** [comment]
I just synced it :P

**Comment by HeroCC** [comment]
Great turnaround :sweat_smile:, thank you!

**Comment by ranisalt** [comment]
Always a pleasure :laughing:
