### ISSUE TITLE
[rocm-opencl-runtime] multiple definition of ret_val

### ISSUE THREAD

**Issue by imyxh** [rocm-arch/rocm-arch#165]
Hi, I'm not sure if this is an issue with the AUR packages, or if it's with ROCm, or if I'm just doing something wrong. I installed, in the following order:
```
cd ./hsakmt-roct && makepkg -sci
cd ../hsa-rocr && makepkg -sci
cd ../rocm-cmake && makepkg -sci
cd ../llvm-roc && makepkg -sci
cd ../rocm-device-libs && makepkg -sci
cd ../llvm-amdgpu && makepkg -sci
cd ../comgr && makepkg -sci
cd ../rocm-opencl-runtime && makepkg -sci
```
With versions:
```
comgr 3.3.0-2
hsakmt-roct 3.3.0-1
hsa-rocr 3.3.0-5
llvm-amdgpu 3.3.0-2
llvm-roc 3.3.0-2
rocm-cmake 3.3.0-1
rocm-device-libs 3.3.0-3
```
Yet I still get the following error in compiling rocm-opencl-runtime:
```
[100%] Linking C executable icd_loader_test
/usr/bin/ld: CMakeFiles/icd_loader_test.dir/test_platforms.c.o:(.bss+0x110): multiple definition of `ret_val'; CMakeFiles/icd_loader_test.dir/test_kernel.c.o:(.bss+0x348): first defined here
/usr/bin/ld: CMakeFiles/icd_loader_test.dir/test_program_objects.c.o:(.bss+0x0): multiple definition of `ret_val'; CMakeFiles/icd_loader_test.dir/test_kernel.c.o:(.bss+0x348): first defined here
/usr/bin/ld: CMakeFiles/icd_loader_test.dir/test_sampler_objects.c.o:(.bss+0x0): multiple definition of `ret_val'; CMakeFiles/icd_loader_test.dir/test_kernel.c.o:(.bss+0x348): first defined here
/usr/bin/ld: CMakeFiles/icd_loader_test.dir/test_cl_runtime.c.o:(.bss+0x0): multiple definition of `ret_val'; CMakeFiles/icd_loader_test.dir/test_kernel.c.o:(.bss+0x348): first defined here
/usr/bin/ld: CMakeFiles/icd_loader_test.dir/test_clgl.c.o:(.bss+0x248): multiple definition of `ret_val'; CMakeFiles/icd_loader_test.dir/test_kernel.c.o:(.bss+0x348): first defined here
/usr/bin/ld: CMakeFiles/icd_loader_test.dir/test_image_objects.c.o:(.bss+0x0): multiple definition of `ret_val'; CMakeFiles/icd_loader_test.dir/test_kernel.c.o:(.bss+0x348): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [api/opencl/khronos/icd/test/loader_test/CMakeFiles/icd_loader_test.dir/build.make:271: api/opencl/khronos/icd/test/loader_test/icd_loader_test] Error 1
make[1]: *** [CMakeFiles/Makefile2:1330: api/opencl/khronos/icd/test/loader_test/CMakeFiles/icd_loader_test.dir/all] Error 2
make: *** [Makefile:172: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```
It looks like the linker might be complaining about ret_val being defined globally in multiple files?
![image](https://user-images.githubusercontent.com/12703838/81989914-f26bd980-95f2-11ea-8855-54058355e118.png)
![image](https://user-images.githubusercontent.com/12703838/81989938-fb5cab00-95f2-11ea-8063-6d61277e71cd.png)

Since this hasn't been reported before, and this is on the latest stable version of the pkgbuild, I would like to assume that it's my fault but I can't find anything wrong with my build process.

Advice would be appreciated. Thanks!

**Comment by acxz** [comment]
Hey @imyxh thx for the report! Also just for future reference if you could post code blocks in text instead of pictures that would be much appreciated. It makes it easier to search things.

Also if you are not developing on the PKGBUILDs we recommend to just use the PKGBUILDs from the AUR using an AUR helper. You can also use the arch4edu repository which hosts many of these packages in binary making the installation much faster. See: https://github.com/arch4edu/arch4edu/wiki/Add-arch4edu-to-your-Archlinux

**Comment by acxz** [comment]
hmm I can't seem to reproduce it, lets keep this issue open until others have had a chance reproduce it.

**Comment by imyxh** [comment]
To rule out any effect from external packages, the state of my system, etc, I just reproduced this on a LXC system. Steps:

1. Create an [Linux container](https://wiki.archlinux.org/index.php/Linux_Containers) with the archlinux/current/amd64 downloaded image;
2. install git and the base-devel group;
3. create a user and give them sudo permissions;
4. install falconindy's [auracle](https://github.com/falconindy/auracle) tool (to help with downloading the repos);
5. download my `upgrade.sh` (below);
6. run `yes | ./upgrade.sh` and observe the error produced in build() for rocm-opencl-runtime at the end.

Contents of upgrade.sh:
```sh
#!/bin/sh
set -e

# check with auracle buildorder and update this

echo
echo "downloading new PKGBUILDs"
echo
auracle clone --recurse rocm-opencl-runtime
echo
echo "packages downloaded, installing ..."
echo
cd ./hsakmt-roct && makepkg -sci
cd ../hsa-rocr && makepkg -sci
cd ../llvm-amdgpu && makepkg -sci
cd ../rocm-cmake && makepkg -sci
cd ../llvm-roc && makepkg -sci
cd ../rocm-device-libs && makepkg -sci
cd ../comgr && makepkg -sci
cd ../rocm-opencl-runtime && makepkg -sci
cd ..
echo
echo "done!"
echo
```

**Comment by imyxh** [comment]
Update: interestingly enough, I can actually reproduce this on the container by installing the master branch of ROCm-OpenCL-Runtime straight from git, following AMD's own instructions....

Does my system have a curse that also applies to any containers I create? Perhaps I'll file an issue upstream and see if they can help. @acxz, feel free to close this issue if that's what you think is best. I can post an update if it turns out this is an Archlinux-specific problem.
