### ISSUE TITLE
Packages to sync

### ISSUE THREAD

**Issue by acxz** [rocm-arch/rocm-arch#166]
- [ ] rocprim 
- [ ] rocthrust
- [ ] rocfft
- [ ] rocrand

**Comment by farnoy** [comment]
I no longer have access to these packages, unassigning.

**Comment by acxz** [comment]
Ah sorry about that, I assigned it to you because you were listed as a co-maintainer for rocprim and rocthrust.

**Comment by ranisalt** [comment]
I don't have access too. I don't know who is responsible for that, but I keep getting added and removed from the maintainer list and this is spamming my inbox, so I would be so happy if that kindly stopped.

![image](https://user-images.githubusercontent.com/1993083/82127548-f68b2900-97a3-11ea-95fb-2865282648be.png)

**Comment by acxz** [comment]
Weird the AUR package states that you are a co-maintainer for the rocprim and rocthrust packages.

**Comment by ranisalt** [comment]
Wait, but why did I receive messages telling "you were removed"? That's confusing.

Published all of them
