### ISSUE TITLE
[hcc] missing cstdlib in Shutdown.cpp prevents compilation

### ISSUE THREAD

**Issue by iskur** [rocm-arch/rocm-arch#167]
The file "llvm-project-roc-hcc-3.3.0/clang-tools-extra/clangd/Shutdown.cpp" is missing a:

`#include <cstdlib>`

Without it compilation fails for me with:
> error: ‘abort’ is not a member of ‘std’

**Comment by acxz** [comment]
hmm interesting indeed, let me try a rebuild rq

**Comment by tpkessler** [comment]
I can reproduce the error:

```bash
/build/hcc/src/hcc-roc-hcc-3.3.0/llvm-project/clang-tools-extra/clangd/Shutdown.cpp:21:10: error: ‘abort’ is not a member of ‘std’
   21 |     std::abort();
      |          ^~~~~
```

**Comment by tpkessler** [comment]
`hcc` is deprecated and will be removed from this repo and the AUR #191 . `llvm-amdgpu` in combination with `hip-rocclr` is the new way in ROCm 3.5.0 to compile the code.
