### ISSUE TITLE
[hipsparse] Requires hip >= 3.30 however hip 3.30 is installed...

### ISSUE THREAD

**Issue by zack-ashen** [rocm-arch/rocm-arch#173]
Firstly, thank you so much for this project. It has been extremely helpful. However, when attempting to install hipsparse or rocm-libs it fails immediately with `hipsparse requires hip >= 3.30`. However, when I run `./hipcc --version` it returns: `HIP version: 3.3.20195-`.

**Comment by tpkessler** [comment]
Hi @zack-ashen, thank you for kind words. `rocm-libs` is work in progress at the moment but you can get working packages from the PRs I've opened. For `hipblas` you may try PR #163. It hasn't been merged yet as we working on `rocblas` at the moment, see #158.

**Comment by zack-ashen** [comment]
Thanks so much! I was able to get `hipblas` install from your PR. However, still struggling with `rocblas` and the rest of `rocm-libs`. Guess I'll just have to wait for more development... This project is really great though I can't wait to have Tensorflow finally running.
