### ISSUE TITLE
Packages to Sync

### ISSUE THREAD

**Issue by acxz** [rocm-arch/rocm-arch#176]
- [ ] rock-dkms

**Comment by acxz** [comment]
Sorry to ping @ranisalt again but you mind syncing these packages? I would like to resolve #168 asap

**Comment by ranisalt** [comment]
My computer has bricked and I can't use it now.

**Comment by acxz** [comment]
Oh noo

**Comment by acxz** [comment]
If you have internet access do you think you add me as a comaintainer on those packages?

**Comment by acxz** [comment]
@naetherm @neeshy since it seems like you guys do not have the time to maintain the packages, can you transfer the ownership of the packages over to me? rocm 3.5.0 is around the corner and I would like to get these packages out as soon as possible.

**Comment by ranisalt** [comment]
I have given you access to the packages I own. You can push them all now, I should have access to a new computer with a Radeon GPU by Monday so I will return contributing to the organization.

Also, note that what you did is against the rules of the AUR, you should only request orphan/deletion of a package after a two weeks notice. You might get flagged as a spammer if you repeat.

@naetherm is missing, and some packages are owned by them, which means I can't give you access. I will push them first when I can.

**Comment by naetherm** [comment]
> @naetherm @neeshy since it seems like you guys do not have the time to maintain the packages, can you transfer the ownership of the packages over to me? rocm 3.5.0 is around the corner and I would like to get these packages out as soon as possible.

Gave you access to the packages I own too.

**Comment by ranisalt** [comment]
Hello :rofl:

**Comment by naetherm** [comment]
> Hello

Have I missed you? (Sorry, first coffee in the morning if that's the case ;) )

**Comment by ranisalt** [comment]
No, but we have missed you hahaha my access is fine.

**Comment by acxz** [comment]
Thank you guys so much!
