### ISSUE TITLE
ROCm 3.5.0 released

### ISSUE THREAD

**Issue by tpkessler** [rocm-arch/rocm-arch#179]
From https://github.com/RadeonOpenCompute/ROCm:
>The following changes apply in this release:
>  HCC is deprecated and replaced with the HIP-Clang compiler
>   HIP-HCC runtime is changed to Radeon Open Compute Common Language Runtime (HIP-ROCClr)
>    In the v3.5 release, the firmware is separated from the kernel package. The difference is as >follows:
 >       v3.5 release has two separate rock-dkms and rock-dkms-firmware packages
 >       v3.3 release had the firmware as part of the rock-dkms package

Unfortunately there's no support for Ubuntu 20.04, so not for `glibc 2.31`. Let's see how far we come with the new ROCm stack.

How should be proceed? I suggest we should start with `hsakmt-roct`, `hsa-rocr`, `comgr` and alike as they are needed for nearly all other package. In a second step we should update the opencl-runtime (which is buggy for me on a Vega 56 in version 3.1.). Then we should build `hip` with `vdi` (`ROCClr`) and then deprecate `hcc` like AMD does. This means for instance that all packages in `rocm-libs` need to be updated.

**Comment by acxz** [comment]
I think that sounds like a great plan, as you can prob tell I have been busy with other projects these days and haven't been able to spend as much time as I would like to on rocm-arch.

**Comment by tpkessler** [comment]
I was able to compile the new OpenCL runtime, #189 . In contrast to what AMD say in their release notes, `clinfo` shows version 2.0, not 2.2.
In addition, we now have the new `hip-rocclr` which works fine for the  examples I tried.

What's missing now are `rocm-libs`. Updating them should be straightforward: 
* Update sources, checksums
* Remove `hcc` dependency and compile with the new `hipcc` from `hip-rocclr` instead

Furthermore, we also have to update packages like `rocm-smi`, `rocprofiler`,...
But this shouldn't be that difficult.

**Comment by naetherm** [comment]
Amazing work @tpkessler , as @acxz I'm also a bit busy these days.
Should we maybe add a checkbox-list of all libraries, already ported libraries can be checked or when the task of porting to 3.5.x takes a bit longer one can flag those package by his/her username so there are not two people working on the same package?

**Comment by tpkessler** [comment]
Thank you @naetherm. We should create a separate issue for every remaining package and group those in a milestone. Then we can assign work to everybody and monitor the progress we make.

**Comment by tpkessler** [comment]
I've opened a separate issue for every package not updated to 3.5.0 yet and organized them in a milestone. Some of them are assigned to me. Which one will you choose @acxz , @naetherm , @rigred , @ranisalt , @farnoy ?

**Comment by acxz** [comment]
I choose Pikachu haha, jk I can take care of some today.

**Comment by tpkessler** [comment]
We've completed the milestone! All packages are now at version 3.5.0.
