### ISSUE TITLE
[rocm-opencl-runtime] out of date

### ISSUE THREAD

**Issue by acxz** [rocm-arch/rocm-arch#180]
This package is out of date.

Flagged by @Megacubo on AUR

**Comment by tpkessler** [comment]
Fixed with #189

**Comment by acxz** [comment]
@tpkessler I had some problems syncing since @ranisalt had pushed a commit to the AUR package without going through this repo. The simplest and easiest solution was for me to remove rocm-opencl-runtime and pull in the AUR remote. Could you resubmit a PR for upgrading this package?

Sorry about that.

**Comment by tpkessler** [comment]
No problem @acxz. I've resubmitted the OpenCL runtime package.

**Comment by acxz** [comment]
thx! synced and closed
