### ISSUE TITLE
[hsa-rocr] Build error

### ISSUE THREAD

**Issue by ruben2000de** [rocm-arch/rocm-arch#195]
I'm building on manjaro via AUR and getting this error:
https://aur.archlinux.org/packages/hsa-rocr/
(sorry, my system is speaking german)

[ 56%] Building CXX object CMakeFiles/hsa-runtime64.dir/core/runtime/intercept_queue.cpp.o
[ 59%] Building CXX object CMakeFiles/hsa-runtime64.dir/core/runtime/ipc_signal.cpp.o
/var/tmp/pamac-build-user/hsa-rocr/src/ROCR-Runtime-rocm-3.5.0/src/core/runtime/amd_filter_device.cpp: In Elementfunktion »void amd::RvdFilter::BuildDeviceUuidList(uint32_t)«:
/var/tmp/pamac-build-user/hsa-rocr/src/ROCR-Runtime-rocm-3.5.0/src/core/runtime/amd_filter_device.cpp:107:15: Fehler: »HsaNodeProperties« {aka »struct _HsaNodeProperties«} hat kein Element namens »UniqueID«
  107 |     if (props.UniqueID == 0) {
      |               ^~~~~~~~
/var/tmp/pamac-build-user/hsa-rocr/src/ROCR-Runtime-rocm-3.5.0/src/core/runtime/amd_filter_device.cpp:117:21: Fehler: »HsaNodeProperties« {aka »struct _HsaNodeProperties«} hat kein Element namens »UniqueID«
  117 |            << props.UniqueID;
      |                     ^~~~~~~~
[ 62%] Building CXX object CMakeFiles/hsa-runtime64.dir/core/runtime/isa.cpp.o
[ 64%] Building CXX object CMakeFiles/hsa-runtime64.dir/core/runtime/runtime.cpp.o
[ 67%] Building CXX object CMakeFiles/hsa-runtime64.dir/core/runtime/signal.cpp.o
/var/tmp/pamac-build-user/hsa-rocr/src/ROCR-Runtime-rocm-3.5.0/src/core/runtime/amd_gpu_agent.cpp: In Elementfunktion »virtual hsa_status_t amd::GpuAgent::GetInfo(hsa_agent_info_t, void*) const«:
/var/tmp/pamac-build-user/hsa-rocr/src/ROCR-Runtime-rocm-3.5.0/src/core/runtime/amd_gpu_agent.cpp:905:63: Fehler: »const HsaNodeProperties« {aka »const struct _HsaNodeProperties«} hat kein Element namens »UniqueID«
  905 |       uint64_t uuid_value = static_cast<uint64_t>(properties_.UniqueID);
      |                                                               ^~~~~~~~
make[2]: *** [CMakeFiles/hsa-runtime64.dir/build.make:226: CMakeFiles/hsa-runtime64.dir/core/runtime/amd_filter_device.cpp.o] Fehler 1
make[2]: *** Es wird auf noch nicht beendete Prozesse gewartet....
make[2]: *** [CMakeFiles/hsa-runtime64.dir/build.make:161: CMakeFiles/hsa-runtime64.dir/core/runtime/amd_gpu_agent.cpp.o] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:183: CMakeFiles/hsa-runtime64.dir/all] Fehler 2
make: *** [Makefile:172: all] Fehler 2
==> FEHLER: Ein Fehler geschah in build().
    Breche ab...

**Comment by acxz** [comment]
Thx for the report @ruben2000de Before digging into this I would like to point out that we do not support Manjaro, we only support Arch-based distros which have repo compatibility with Arch, such as [EndeavourOS](https://endeavouros.com/).

**Comment by ruben2000de** [comment]
already thought something linke that. Thats because I first commented the AUR package. Maybe a pro-user but not a maker here.

**Comment by acxz** [comment]
@ruben2000de it seems that no one has been able to reproduce this issue. I recommend you try using the arch4edu repo as shown in the [installation instructions](https://github.com/rocm-arch/rocm-arch#installation) if this still does not work for you then I suggest moving over to EndeavourOS. Sorry we couldn't help you out, but the AUR is primarily for Arch Users (or distros that are Arch repo compatbile users). Do try the arch4edu repo tho, hopefully that will work instead of compiling the code by yourself.
