### ISSUE TITLE
README for project

### ISSUE THREAD

**Issue by tpkessler** [rocm-arch/rocm-arch#204]
We miss a README for the repository. It may serve as a sandbox for the ArchWiki entry we have to write. It should contain:

- [x] A short summary of the packages hosted here as well as a quick start guide, similar to @acxz 's PR to the ROCm repository: https://github.com/RadeonOpenCompute/ROCm_Documentation/pull/73
- [x] Warnings: `llvm-amdgpu` and `rocblas` need a lot of RAM and disk space: Use a swap file https://wiki.archlinux.org/index.php/swap#Swap_file (for me 64 GB with 32 GB RAM is enough)
- [ ] A list a packages needed for certain tasks, for instance:
  * CUDA usecase: How do I install HIP (with hipify) as a drop-in replacement for my CUDA code?
  * I use cuBLAS. What package do I need for ROCm?
  * How get tensorflow up and running?
- [x] Use binary package whenever possible, link to arch4edu https://wiki.archlinux.org/index.php/unofficial_user_repositories#arch4edu
- [ ] Link to the ArchWiki entry for ROCm

Anything else?

**Comment by pepper-jk** [comment]
Another Warning:
`llvm-amdgpu` needs >50GB free disk space during build

It just crashed on me at 98%. -.-

**Comment by acxz** [comment]
@tpkessler these are all really great points that we need to document. However I do not think a README is the best approach. This repo is a temporary one until these rocm packages get placed into the official repositories. In any case documentation should go in the ArchWiki under the [ROCm](https://wiki.archlinux.org/index.php/GPGPU#ROCm) section: https://wiki.archlinux.org/index.php/GPGPU#ROCm

In fact this is listed as one of the checklist items under https://github.com/rocm-arch/rocm-arch/issues/11

We can have this issue track the documentation progress on the ArchWiki tho and turn your bullet points into a checklist.

**Comment by tpkessler** [comment]
@pepper-jk Thanks for your hint. That's also what I observe. After building `llvm-amdgpu` I always immediately delete the `src` and `pkg` dirs.

**Comment by tpkessler** [comment]
@acxz I totally agree with you. My idea was that we use the README as a sanbox for the ArchWiki entry.

**Comment by acxz** [comment]
hmm I see the point in that, and it is much easier to work on the markdown format on Github than the Arch Wiki.

Okay then yeah let's work on the README in this repo and once we feel like it is ready enough (or once we reach the ROCm 3.5 milestone) we can have someone move the README information over to the relevant Arch Wiki entry.

For the readme since it doesn't involve syncing to the AUR feel free to merge and push those readme changes without a PR.

**Comment by tpkessler** [comment]
I've pushed the first version of the README. Please feel free to improve it.

**Comment by acxz** [comment]
I think that bullet 3 should be under the ROCm ArchWiki entry and should not be in this readme.

**Comment by acxz** [comment]
I finished bullet 4 with 378ffda and as such closing this issue.
Feel free to reopen this if you disagree @tpkessler
