### ISSUE TITLE
[hipsparse] Update to 3.5.0

### ISSUE THREAD

**Issue by tpkessler** [rocm-arch/rocm-arch#207]

**Comment by tpkessler** [comment]
I cannot compile it on Arch Linux at the moment: https://github.com/ROCmSoftwarePlatform/hipSPARSE/issues/121

**Comment by acxz** [comment]
Let's push this out anyway. Even though the new version doesn't build, the current version doesn't build either. It's better to debug the lastest version than figuring out how the older version builds.
