### ISSUE TITLE
[hcc] build failure

### ISSUE THREAD

**Issue by BrunoLiegiBastonLiegi** [rocm-arch/rocm-arch#25]
Hello, I'm facing build failure while building hcc on manjaro 5.5.6-1. Compilation stops at the following point:

[1661/5463] Building CXX object compiler/projects/compiler-rt/lib/sanitizer_c...RTSanitizerCommonNoTermination.i386.dir/sanitizer_platform_limits_posix.cpp.o FAILED: compiler/projects/compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonNoTermination.i386.dir/sanitizer_platform_limits_posix.cpp.o /usr/bin/c++ -DHAVE_RPC_XDR_H=0 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Icompiler/projects/compiler-rt/lib/sanitizer_common -I/home/andrea/build/hcc/src/hcc-roc-hcc-2.10.0/compiler-rt/lib/sanitizer_common -Iinclude -I/home/andrea/build/hcc/src/hcc-roc-hcc-2.10.0/include -I/home/andrea/build/hcc/src/hcc-roc-hcc-2.10.0/compiler/include -I/usr/include/libxml2 -Icompiler/include -I/home/andrea/build/hcc/src/hcc-roc-hcc-2.10.0/compiler-rt/lib/sanitizer_common/.. -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -fPIC -fvisibility-inlines-hidden -Werror=date-time -std=c++14 -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment -fdiagnostics-color -ffunction-sections -fdata-sections -Wall -std=c++14 -Wno-unused-parameter -O3 -DNDEBUG -m32 -fPIC -fno-builtin -fno-exceptions -fomit-frame-pointer -funwind-tables -fno-stack-protector -fvisibility=hidden -fno-lto -O3 -g -Wno-variadic-macros -Wno-non-virtual-dtor -fno-rtti -Wframe-larger-than=570 -MD -MT compiler/projects/compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonNoTermination.i386.dir/sanitizer_platform_limits_posix.cpp.o -MF compiler/projects/compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonNoTermination.i386.dir/sanitizer_platform_limits_posix.cpp.o.d -o compiler/projects/compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonNoTermination.i386.dir/sanitizer_platform_limits_posix.cpp.o -c /home/andrea/build/hcc/src/hcc-roc-hcc-2.10.0/compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_posix.cpp 
In file included from /home/andrea/build/hcc/src/hcc-roc-hcc-2.10.0/compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_posix.cpp:162: /home/andrea/build/hcc/src/hcc-roc-hcc-2.10.0/compiler-rt/lib/sanitizer_common/sanitizer_internal_defs.h:342:72: error: narrowing conversion of ‘-1’ from ‘int’ to ‘unsigned int’ [-Wnarrowing] 342 | typedef char IMPL_PASTE(assertion_failed_##_, line)[2*(int)(pred)-1] | 

thanks in advance for the awesome job you are doing!

**Comment by acxz** [comment]
thx for reporting the error! Just from looking at the output, it seems like you are using hcc 2.10? Can you confirm if you are using the package on the AUR?

**Comment by BrunoLiegiBastonLiegi** [comment]
Yes sorry about that, cause I tried also building the previous version, that must be the output of the second try.
This is what I get with 3.0.0:

[1665/5541] Building CXX object llvm-project/llvm/projects/compiler-rt/lib/sa...RTSanitizerCommonNoTermination.i386.dir/sanitizer_platform_limits_posix.cpp.o
FAILED: llvm-project/llvm/projects/compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonNoTermination.i386.dir/sanitizer_platform_limits_posix.cpp.o 
/usr/bin/c++  -DHAVE_RPC_XDR_H=0 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Illvm-project/llvm/projects/compiler-rt/lib/sanitizer_common -I/home/andrea/build/hcc/src/hcc-roc-hcc-3.0.0/llvm-project/compiler-rt/lib/sanitizer_common -Iinclude -I/home/andrea/build/hcc/src/hcc-roc-hcc-3.0.0/include -I/home/andrea/build/hcc/src/hcc-roc-hcc-3.0.0/llvm-project/llvm/include -I/usr/include/libxml2 -Illvm-project/llvm/include -I/home/andrea/build/hcc/src/hcc-roc-hcc-3.0.0/llvm-project/compiler-rt/lib/sanitizer_common/.. -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -fPIC -fvisibility-inlines-hidden -Werror=date-time -std=c++14 -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment -fdiagnostics-color -ffunction-sections -fdata-sections -Wall -std=c++14 -Wno-unused-parameter -O3 -DNDEBUG    -m32 -fPIC -fno-builtin -fno-exceptions -fomit-frame-pointer -funwind-tables -fno-stack-protector -fvisibility=hidden -fno-lto -O3 -g -Wno-variadic-macros -Wno-non-virtual-dtor -fno-rtti -Wframe-larger-than=570 -MD -MT llvm-project/llvm/projects/compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonNoTermination.i386.dir/sanitizer_platform_limits_posix.cpp.o -MF llvm-project/llvm/projects/compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonNoTermination.i386.dir/sanitizer_platform_limits_posix.cpp.o.d -o llvm-project/llvm/projects/compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonNoTermination.i386.dir/sanitizer_platform_limits_posix.cpp.o -c /home/andrea/build/hcc/src/hcc-roc-hcc-3.0.0/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_posix.cpp
In file included from /home/andrea/build/hcc/src/hcc-roc-hcc-3.0.0/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_posix.cpp:167:
/home/andrea/build/hcc/src/hcc-roc-hcc-3.0.0/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_internal_defs.h:342:72: error: narrowing conversion of ‘-1’ from ‘int’ to ‘unsigned int’ [-Wnarrowing]
  342 |     typedef char IMPL_PASTE(assertion_failed_##_, line)[2*(int)(pred)-1]

The problem is the same I think...

**Comment by acxz** [comment]
hmm, I see. We are currently trying to push out hcc version 3.1.0. Maybe that will resolve the issue.

**Comment by BrunoLiegiBastonLiegi** [comment]
Perfect thank you.
Furthermore I have not experience in writing PKGBUILDs, but if there is anything I can do to help you, just let me know!

**Comment by acxz** [comment]
Submitting bug reports is very useful for us. Another thing you can do is submit issues upstream. It is not always the case that we will be able to fix the issue with packaging, but rather there is a deeper problem that AMD themselves need to fix. For example, I would submit this bug report to the AMD repository that contains hcc. They might know of a fix right off the bat and can include it in their next release.

**Comment by neeshy** [comment]
According to https://bugs.gentoo.org/709672 this is a bug related to building llvm against glibc 2.30. I'll add the relevant patches shortly.

**Comment by neeshy** [comment]
After patching and compiling, there are still linking errors we'll have to figure out:

```ld: warning: libhsakmt.so.1, needed by /opt/rocm/lib/libhsa-runtime64.so, not found (try using -rpath or -rpath-link)            
ld: /opt/rocm/lib/libhsa-runtime64.so: undefined reference to `hsaKmtUpdateQueue@HSAKMT_1'                                                                                 
ld: /opt/rocm/lib/libhsa-runtime64.so: undefined reference to `hsaKmtSetQueueCUMask@HSAKMT_1'                                     
ld: /opt/rocm/lib/libhsa-runtime64.so: undefined reference to `hsaKmtAcquireSystemProperties@HSAKMT_1'                                                            
ld: /opt/rocm/lib/libhsa-runtime64.so: undefined reference to `hsaKmtGetNodeCacheProperties@HSAKMT_1'
ld: /opt/rocm/lib/libhsa-runtime64.so: undefined reference to `hsaKmtSetTrapHandler@HSAKMT_1'
ld: /opt/rocm/lib/libhsa-runtime64.so: undefined reference to `hsaKmtGetClockCounters@HSAKMT_1'                                  
ld: /opt/rocm/lib/libhsa-runtime64.so: undefined reference to `hsaKmtQueryPointerInfo@HSAKMT_1'
ld: /opt/rocm/lib/libhsa-runtime64.so: undefined reference to `hsaKmtWaitOnMultipleEvents@HSAKMT_1'                            
ld: /opt/rocm/lib/libhsa-runtime64.so: undefined reference to `hsaKmtCreateEvent@HSAKMT_1'
ld: /opt/rocm/lib/libhsa-runtime64.so: undefined reference to `hsaKmtSetMemoryUserData@HSAKMT_1'
ld: /opt/rocm/lib/libhsa-runtime64.so: undefined reference to `hsaKmtReleaseSystemProperties@HSAKMT_1'                  
ld: /opt/rocm/lib/libhsa-runtime64.so: undefined reference to `hsaKmtRegisterSharedHandleToNodes@HSAKMT_1'                                                                 
ld: /opt/rocm/lib/libhsa-runtime64.so: undefined reference to `hsaKmtUnmapMemoryToGPU@HSAKMT_1'               
ld: /opt/rocm/lib/libhsa-runtime64.so: undefined reference to `hsaKmtCloseKFD@HSAKMT_1'                                                                        
ld: /opt/rocm/lib/libhsa-runtime64.so: undefined reference to `hsaKmtDestroyQueue@HSAKMT_1'
ld: /opt/rocm/lib/libhsa-runtime64.so: undefined reference to `hsaKmtGetNodeMemoryProperties@HSAKMT_1'
ld: /opt/rocm/lib/libhsa-runtime64.so: undefined reference to `hsaKmtDeregisterMemory@HSAKMT_1'                               
ld: /opt/rocm/lib/libhsa-runtime64.so: undefined reference to `hsaKmtWaitOnEvent@HSAKMT_1'
ld: /opt/rocm/lib/libhsa-runtime64.so: undefined reference to `hsaKmtRegisterGraphicsHandleToNodes@HSAKMT_1'
ld: /opt/rocm/lib/libhsa-runtime64.so: undefined reference to `hsaKmtAllocQueueGWS@HSAKMT_1'
ld: /opt/rocm/lib/libhsa-runtime64.so: undefined reference to `hsaKmtSetEvent@HSAKMT_1'                       
ld: /opt/rocm/lib/libhsa-runtime64.so: undefined reference to `hsaKmtGetVersion@HSAKMT_1'
ld: /opt/rocm/lib/libhsa-runtime64.so: undefined reference to `hsaKmtRegisterSharedHandle@HSAKMT_1'                       
ld: /opt/rocm/lib/libhsa-runtime64.so: undefined reference to `hsaKmtGetNodeProperties@HSAKMT_1'                              
ld: /opt/rocm/lib/libhsa-runtime64.so: undefined reference to `hsaKmtAllocMemory@HSAKMT_1'                                                                                 
ld: /opt/rocm/lib/libhsa-runtime64.so: undefined reference to `hsaKmtShareMemory@HSAKMT_1'
ld: /opt/rocm/lib/libhsa-runtime64.so: undefined reference to `hsaKmtMapMemoryToGPU@HSAKMT_1'                                                                              
ld: /opt/rocm/lib/libhsa-runtime64.so: undefined reference to `hsaKmtOpenKFD@HSAKMT_1'
ld: /opt/rocm/lib/libhsa-runtime64.so: undefined reference to `hsaKmtGetNodeIoLinkProperties@HSAKMT_1'
ld: /opt/rocm/lib/libhsa-runtime64.so: undefined reference to `hsaKmtCreateQueue@HSAKMT_1'
ld: /opt/rocm/lib/libhsa-runtime64.so: undefined reference to `hsaKmtRegisterMemoryWithFlags@HSAKMT_1'
ld: /opt/rocm/lib/libhsa-runtime64.so: undefined reference to `hsaKmtMapMemoryToGPUNodes@HSAKMT_1'
ld: /opt/rocm/lib/libhsa-runtime64.so: undefined reference to `hsaKmtSetMemoryPolicy@HSAKMT_1'
ld: /opt/rocm/lib/libhsa-runtime64.so: undefined reference to `hsaKmtFreeMemory@HSAKMT_1'
ld: /opt/rocm/lib/libhsa-runtime64.so: undefined reference to `hsaKmtDestroyEvent@HSAKMT_1'
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [cmake-tests/CMakeFiles/cmake-test.dir/build.make:87: bin/cmake-test] Error 1```

**Comment by neeshy** [comment]
This page suggests that hsakmt should be at leasat a makedepend of hcc. It's strange how the build system for hcc doesn't pick this up during the configure step.
https://github.com/RadeonOpenCompute/hcc/wiki

**Comment by neeshy** [comment]
Apparently libhsakmt should be provided by roct-thunk-interface:
https://github.com/RadeonOpenCompute/ROCT-Thunk-Interface
There's a pkgconfig file in the root of that repo, and if you look under src/ every symbol that the hcc build is erroring out on is implemented.

**Comment by BrunoLiegiBastonLiegi** [comment]
Hi guys, today I was trying with hcc 3.1.0 and thus first I updated roct-thunk-interface, no problem here, and then tried with rocr-runtime. This results again in a build failure, I attach the building log. Should I open a new issue?

[log.txt](https://github.com/rocm-arch/rocm-arch/files/4307305/log.txt)

**Comment by acxz** [comment]
yes

**Comment by BrunoLiegiBastonLiegi** [comment]
Good news, I managed to build rocr-runtime 3.1 as depicted in #40 and after that hcc 3.1 building goes well.

**Comment by acxz** [comment]
After @neeshy's added the patch, hcc is building just fine for me. I'm closing this issue since it seems like you also got the build working.
