### ISSUE TITLE
[hcc] Add python to makedepends

### ISSUE THREAD

**Issue by frazerk** [rocm-arch/rocm-arch#26]
The `llvm` dependency (at least) requires `python` to build. This should be added to `makedepends` to support tools that build in a clean chroot (e.g. `aur sync --chroot`).

I think this is the only missing build dependency, though I can't be completely certain due to the `hcc` build failing for the reason reported in #25. At the very least, the configure step passes when this is added.

**Comment by neeshy** [comment]
The python make dep was added in https://github.com/rocm-arch/rocm-arch/commit/c54b26b7f60f25241051d539ed803ce812feda6a but we haven't pushed to the AUR yet.
We wanted to iron out some issues before pushing, but that's taking longer than originally anticipated. I'll push to the AUR shortly.

**Comment by acxz** [comment]
has been resolved and synced to the AUR.
