### ISSUE TITLE
[rock-dkms-bin] DRM_VER does not provide a default OS name

### ISSUE THREAD

**Issue by acxz** [rocm-arch/rocm-arch#267]
This comment is a continuation of #244 and follows the patch we have for the package.

Upstream issue: https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver/issues/94

**Comment by tpkessler** [comment]
Relevant upstream issue https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime/issues/122

**Comment by acxz** [comment]
Removing patch label since the upstream PR does not work anymore.

**Comment by acxz** [comment]
I am closing this issue as `rock-dkms-bin` is slated to be deleted.
