### ISSUE TITLE
[aomp-amdgpu] Functional clang for OpenMP offloading on Radeon GPUs

### ISSUE THREAD

**Issue by tpkessler** [rocm-arch/rocm-arch#280]
This issue accompanies a series of pull requests that bring `aomp-amdgpu` on Arch Linux:

## General remarks

The Arch Linux packages use the same cmake flags as the upstream build scripts. This means:

* `CMAKE_BUILD_TYPE=Release` for all packages,
* Configure compiler and libraries with `RPATH` pointing to `/opt/rocm/aomp/lib`. This is needed to pick up the right LLVM and OpenMP libraries.
* Currently, only the `C/C++` backend works. `flang` does not, see below.
* The examples (for OpenMP and HIP) from the `aomp` repo run successfully.
* The `aomp` `clang` can also compile HIP code.
* `clang` from `aomp-llvm` can be used as a backend for `hipcc` by setting the environment variable `HIP_CLANG_PATH`:
```
HIP_CLANG_PATH=/opt/rocm/aomp/bin hipcc ...
```

## A simple example
```C
#include <stdio.h>
#include <omp.h>

int main(int argc, char *argv[])
{
    #pragma omp target
    printf("I'm running on the %s.\n", omp_is_initial_device() ? "host" : "accelerator");

    return 0;
}
```
Compile and run:
```bash
/opt/rocm/aomp/bin/clang -fopenmp -fopenmp-targets=amdgcn-amd-amdhsa -Xopenmp-target=amdgcn-amd-amdhsa -march=$(/opt/rocm/aomp/bin/mygpu) simple.c -o simple
./simple
```
Expected output:
```
I'm running on the accelerator.
```

## The metapackage: `aomp-amdgpu` #273 
The current package is split into several single packages; `aomp-amdpu` is now a metapackage similiar to `rocm-dev` and `rocm-libs`

## The backend: `aomp-llvm` #274 
Yet another `LLVM/clang`. This package is not identical with `llvm-amdgpu`.

## The runtime: `aomp-openmp` #276 
Runtime libraries for OpenMP both for host and device calls. Is built twice, once in release, then in debug mode.

## Fortran support: `aomp-flang` `aomp-pgmath` `aomp-flang-runtime` #277 #278 #279 
These packages compile fine but I get a linker error whenever I try to build a fortran program:
```bash
/usr/bin/ld: /opt/rocm/aomp/bin/../lib/libflang.so: undefined reference to `norm2_real8_'
/usr/bin/ld: /opt/rocm/aomp/bin/../lib/libflang.so: undefined reference to `stime'
/usr/bin/ld: /opt/rocm/aomp/bin/../lib/libpgmath.so: undefined reference to `__mth_i_dceil'
/usr/bin/ld: /opt/rocm/aomp/bin/../lib/libpgmath.so: undefined reference to `__mth_i_floor'
/usr/bin/ld: /opt/rocm/aomp/bin/../lib/libflang.so: undefined reference to `norm2_real4_i8_'
/usr/bin/ld: /opt/rocm/aomp/bin/../lib/libpgmath.so: undefined reference to `__mth_i_dfloor'
/usr/bin/ld: /opt/rocm/aomp/bin/../lib/libflang.so: undefined reference to `norm2_real4_'
/usr/bin/ld: /opt/rocm/aomp/bin/../lib/libflang.so: undefined reference to `norm2_real8_i8_'
```

**Comment by acxz** [comment]
This is some great work @tpkessler, however I dont really have the time to review these changes properly.
I'll let u finish this one out. If you think the PRs are good push them to master and run `aurpublish <package-name>` to sync/create the package on the AUR.

**Comment by rigred** [comment]
Some of the undefined references are odd.
Since looking at the code they appear to mainly revolve around ARM targets which we aren't even building.

**Comment by rigred** [comment]
Everything looks good to merge.
Only thing I'm still suspicious of is `aomp-flang-runtime`
Something real odd is going on there. Will only be able to test that in the morning.

**Comment by tpkessler** [comment]
Hey @acxz, I would also prefer to have them all in a single package. The problem is that `aomp-openmp` and `aomp-flang` need to be compiled with `clang` from `aomp-llvm`. I don't know how to do this in a single `PKGBUILD`. 
The compile chain is

aomp-llvm -> aomp-extras (needs clang from aomp-llvm) -> aomp-openmp (needs tools from aomp-extras and aomp-llvm)

Then you have a working `C/C++` compiler with OpenMP offloading for amdgcn.

**Comment by tpkessler** [comment]
Thanks @rigred for having a look at my pull requests. I also don't understand what's going wrong there.

**Comment by tpkessler** [comment]
> If you could build everything and install it within one package that would be great.

I tried to merge all `package()` functions in a single `PKGBUILD`, but it already fails when building `aomp-extras`. The compiler is not able to locate the bitcode files, see [here](https://github.com/ROCm-Developer-Tools/aomp/issues/114).
If we would like to have a single `PKGBUILD` for `aomp-amdgpu` this would mean at the moment that we would have to recompile half of the ROCm core stack (`hsakmt-roct`, `hsa-rocr`, `rocm-device-libs`, `rocminfo`, ...) with `aomp-llvm` and put it under `/opt/rocm/aomp`.

**Comment by tpkessler** [comment]
I've got some help upstream. `aomp-amdgpu` is now built in standalone mode. However, the `flang` component still doesn't work.

**Comment by acxz** [comment]
Feel free to keep another issue open specific for flang, I'll close this one.
