### ISSUE TITLE
[hipsparse] missing / in install prefix

### ISSUE THREAD

**Issue by cduchesne** [rocm-arch/rocm-arch#283]
There is a missing / in PKGBUILD for install prefix: https://github.com/rocm-arch/rocm-arch/blob/master/hipsparse/PKGBUILD#L31

**Comment by acxz** [comment]
Ah nice catch, feel free to open up a PR to resolve this.

**Comment by cduchesne** [comment]
i'm not allowed to contribute to open source outside of filing generic issues unfortunately, even when personal like this case

**Comment by tpkessler** [comment]
No problem. I've taken care of it.
