### ISSUE TITLE
[hsa-ext-rocr] deb 404 not found

### ISSUE THREAD

**Issue by kjuanman** [rocm-arch/rocm-arch#291]
Downloading hsa-ext-rocr-dev_1.1.30501.0-rocm-rel-3.5-34-def83d8_amd64.deb...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found

The available .deb at 2020 july 4th is:
https://repo.radeon.com/rocm/apt/debian/pool/main/h/hsa-ext-rocr-dev/hsa-ext-rocr-dev_1.1.30500.0-rocm-rel-3.5-30-def83d8_amd64.deb

**Comment by acxz** [comment]
Thats for the report, feel free to make a PR!
