### ISSUE TITLE
[hsa-ext-rocr] out of date

### ISSUE THREAD

**Issue by acxz** [rocm-arch/rocm-arch#30]

**Comment by acxz** [comment]
It seems like it also needs `hsakmt-roct` as a dep.

**Comment by acxz** [comment]
Commit 5021ab7 should resolve this.
Will close upon sync.

**Comment by holishing** [comment]
upstream updated version again
http://repo.radeon.com/rocm/apt/debian/pool/main/h/hsa-ext-rocr-dev/
http://repo.radeon.com/rocm/apt/debian/pool/main/h/hsa-ext-rocr-dev/hsa-ext-rocr-dev_1.1.30300.0-rocm-rel-3.3-19-23fc088b_amd64.deb

**Comment by acxz** [comment]
@holishing thx for letting us know! Feel free to make a PR!

**Comment by acxz** [comment]
@neeshy this issue has been open for a week, can you take a look at it? If we don't hear a response within a couple of days, we'll go ahead and submit an orphan request for this package.

**Comment by acxz** [comment]
Should be resolved now
