### ISSUE TITLE
Rudimentary Navi support possible - should we integrate?

### ISSUE THREAD

**Issue by kozross** [rocm-arch/rocm-arch#310]
Unfortunately, [AMD are being a bit silly on this point][1], so [someone else stepped up][2]. However, it's [clearly far from a good state][3]. Is this something we want to watch and/or use?

[1]: https://github.com/RadeonOpenCompute/ROCm/issues/887#issuecomment-668889122
[2]: https://github.com/smartbitcoin/MyROCm
[3]: https://github.com/smartbitcoin/MyROCm/issues/2

**Comment by acxz** [comment]
We can't really integrate it as it is closed source. If you or anyone else wants to they can make a PKGBUILD for it and put it up on the AUR, but since it is not a "rocm" package/repo from AMD themselves it doesn't fit in this repository.
