### ISSUE TITLE
[comgr] fails to build

### ISSUE THREAD

**Issue by tkuestner** [rocm-arch/rocm-arch#311]
I'm trying to install comgr via `yay -S comgr`, but it fails to build with the following message:

<details open>
<summary>Log, first half</summary>
<br>

:: (1/1) Parsing SRCINFO: comgr
==> Making package: comgr 3.5.0-2 (Wed Aug  5 22:17:08 2020)
==> Retrieving sources...
  -> Found comgr-3.5.0.tar.gz
==> Validating source files with sha256sums...
    comgr-3.5.0.tar.gz ... Passed
==> Making package: comgr 3.5.0-2 (Wed Aug  5 22:17:08 2020)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found comgr-3.5.0.tar.gz
==> Validating source files with sha256sums...
    comgr-3.5.0.tar.gz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting comgr-3.5.0.tar.gz with bsdtar
bsdtar: Failed to set default locale
==> Sources are ready.
==> Making package: comgr 3.5.0-2 (Wed Aug  5 22:17:10 2020)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Removing existing $pkgdir/ directory...
==> Starting build()...
-- The C compiler identification is GNU 10.1.0
-- The CXX compiler identification is GNU 10.1.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.11") 
------------LLVM_DIR: /opt/rocm/llvm/lib/cmake/llvm
---LLVM_INCLUDE_DIRS: /opt/rocm/llvm/include
---LLVM_LIBRARY_DIRS: /opt/rocm/llvm/lib
-----------Clang_DIR: /opt/rocm/llvm/lib/cmake/clang
--CLANG_INCLUDE_DIRS: /opt/rocm/llvm/include
----LLD_INCLUDE_DIRS: 
---AMDDeviceLibs_DIR: /opt/rocm/lib/cmake/AMDDeviceLibs
------------ROCM_DIR: /opt/rocm/share/rocm/cmake
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kuestner/.cache/yay/comgr/src/build
make: Entering directory '/home/kuestner/.cache/yay/comgr/src/build'

</details>

(Cut lots of CMake output not containing any errors.)

<details open>
<summary>Log, second half</summary>
<br>

[ 56%] Building CXX object CMakeFiles/amd_comgr.dir/src/comgr-objdump.cpp.o
/home/kuestner/.cache/yay/comgr/src/ROCm-CompilerSupport-rocm-3.5.0/lib/comgr/src/comgr-symbol.cpp: In member function 'COMGR::SymbolContext* COMGR::SymbolHelper::createBinary(llvm::StringRef, const char*, amd_comgr_data_kind_t)':
/home/kuestner/.cache/yay/comgr/src/ROCm-CompilerSupport-rocm-3.5.0/lib/comgr/src/comgr-symbol.cpp:171:32: error: cannot convert 'llvm::Expected<long unsigned int>' to 'uint64_t' {aka 'long unsigned int'} in assignment
  171 |     Symp->Value = Fsym.getValue();
      |                   ~~~~~~~~~~~~~^~
      |                                |
      |                                llvm::Expected<long unsigned int>
/home/kuestner/.cache/yay/comgr/src/ROCm-CompilerSupport-rocm-3.5.0/lib/comgr/src/comgr-symbol.cpp:174:54: error: cannot convert 'llvm::Expected<unsigned int>' to 'uint64_t' {aka 'long unsigned int'} in initialization
  174 |     uint64_t Flags = Fsym.getObject()->getSymbolFlags(Symb);
      |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
      |                                                      |
      |                                                      llvm::Expected<unsigned int>
/home/kuestner/.cache/yay/comgr/src/ROCm-CompilerSupport-rocm-3.5.0/lib/comgr/src/comgr-symbol.cpp: In member function 'amd_comgr_status_t COMGR::SymbolHelper::iterateTable(llvm::StringRef, amd_comgr_data_kind_t, amd_comgr_status_t (*)(amd_comgr_symbol_t, void*), void*)':
/home/kuestner/.cache/yay/comgr/src/ROCm-CompilerSupport-rocm-3.5.0/lib/comgr/src/comgr-symbol.cpp:236:36: error: cannot convert 'llvm::Expected<long unsigned int>' to 'uint64_t' {aka 'long unsigned int'} in assignment
  236 |       Ctxp->Value = Symbol.getValue();
      |                     ~~~~~~~~~~~~~~~^~
      |                                    |
      |                                    llvm::Expected<long unsigned int>
/home/kuestner/.cache/yay/comgr/src/ROCm-CompilerSupport-rocm-3.5.0/lib/comgr/src/comgr-symbol.cpp:242:58: error: cannot convert 'llvm::Expected<unsigned int>' to 'uint64_t' {aka 'long unsigned int'} in initialization
  242 |       uint64_t Flags = Symbol.getObject()->getSymbolFlags(Symb);
      |                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
      |                                                          |
      |                                                          llvm::Expected<unsigned int>
make[2]: *** [CMakeFiles/amd_comgr.dir/build.make:187: CMakeFiles/amd_comgr.dir/src/comgr-symbol.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/kuestner/.cache/yay/comgr/src/ROCm-CompilerSupport-rocm-3.5.0/lib/comgr/src/comgr-objdump.cpp: In member function 'void llvm::DisassemHelper::DisassembleObject(const llvm::object::ObjectFile*, bool)':
/home/kuestner/.cache/yay/comgr/src/ROCm-CompilerSupport-rocm-3.5.0/lib/comgr/src/comgr-objdump.cpp:1304:44: error: no matching function for call to 'error(llvm::Error)'
 1304 |       error(ExportEntry.getSymbolName(Name));
      |                                            ^
/home/kuestner/.cache/yay/comgr/src/ROCm-CompilerSupport-rocm-3.5.0/lib/comgr/src/comgr-objdump.cpp:326:13: note: candidate: 'void error(std::error_code)'
  326 | static void error(std::error_code EC) {
      |             ^~~~~
/home/kuestner/.cache/yay/comgr/src/ROCm-CompilerSupport-rocm-3.5.0/lib/comgr/src/comgr-objdump.cpp:326:35: note:   no known conversion for argument 1 from 'llvm::Error' to 'std::error_code'
  326 | static void error(std::error_code EC) {
      |                   ~~~~~~~~~~~~~~~~^~
/home/kuestner/.cache/yay/comgr/src/ROCm-CompilerSupport-rocm-3.5.0/lib/comgr/src/comgr-objdump.cpp:335:37: note: candidate: 'void error(llvm::Twine)'
  335 | static LLVM_ATTRIBUTE_NORETURN void error(Twine Message) {
      |                                     ^~~~~
/home/kuestner/.cache/yay/comgr/src/ROCm-CompilerSupport-rocm-3.5.0/lib/comgr/src/comgr-objdump.cpp:335:49: note:   no known conversion for argument 1 from 'llvm::Error' to 'llvm::Twine'
  335 | static LLVM_ATTRIBUTE_NORETURN void error(Twine Message) {
      |                                           ~~~~~~^~~~~~~
/home/kuestner/.cache/yay/comgr/src/ROCm-CompilerSupport-rocm-3.5.0/lib/comgr/src/comgr-objdump.cpp:1308:42: error: no matching function for call to 'error(llvm::Error)'
 1308 |       error(ExportEntry.getExportRVA(RVA));
      |                                          ^
/home/kuestner/.cache/yay/comgr/src/ROCm-CompilerSupport-rocm-3.5.0/lib/comgr/src/comgr-objdump.cpp:326:13: note: candidate: 'void error(std::error_code)'
  326 | static void error(std::error_code EC) {
      |             ^~~~~
/home/kuestner/.cache/yay/comgr/src/ROCm-CompilerSupport-rocm-3.5.0/lib/comgr/src/comgr-objdump.cpp:326:35: note:   no known conversion for argument 1 from 'llvm::Error' to 'std::error_code'
  326 | static void error(std::error_code EC) {
      |                   ~~~~~~~~~~~~~~~~^~
/home/kuestner/.cache/yay/comgr/src/ROCm-CompilerSupport-rocm-3.5.0/lib/comgr/src/comgr-objdump.cpp:335:37: note: candidate: 'void error(llvm::Twine)'
  335 | static LLVM_ATTRIBUTE_NORETURN void error(Twine Message) {
      |                                     ^~~~~
/home/kuestner/.cache/yay/comgr/src/ROCm-CompilerSupport-rocm-3.5.0/lib/comgr/src/comgr-objdump.cpp:335:49: note:   no known conversion for argument 1 from 'llvm::Error' to 'llvm::Twine'
  335 | static LLVM_ATTRIBUTE_NORETURN void error(Twine Message) {
      |                                           ~~~~~~^~~~~~~
/home/kuestner/.cache/yay/comgr/src/ROCm-CompilerSupport-rocm-3.5.0/lib/comgr/src/comgr-objdump.cpp: In member function 'void llvm::DisassemHelper::PrintSymbolTable(const llvm::object::ObjectFile*, llvm::StringRef, llvm::StringRef)':
/home/kuestner/.cache/yay/comgr/src/ROCm-CompilerSupport-rocm-3.5.0/lib/comgr/src/comgr-objdump.cpp:1807:37: error: cannot convert 'llvm::Expected<unsigned int>' to 'uint32_t' {aka 'unsigned int'} in initialization
 1807 |     uint32_t Flags = Symbol.getFlags();
      |                      ~~~~~~~~~~~~~~~^~
      |                                     |
      |                                     llvm::Expected<unsigned int>
make[2]: *** [CMakeFiles/amd_comgr.dir/build.make:161: CMakeFiles/amd_comgr.dir/src/comgr-objdump.cpp.o] Error 1
/home/kuestner/.cache/yay/comgr/src/ROCm-CompilerSupport-rocm-3.5.0/lib/comgr/src/comgr-device-libs.cpp: In function 'amd_comgr_status_t COMGR::addDeviceLibraries(COMGR::DataAction*, COMGR::DataSet*)':
/home/kuestner/.cache/yay/comgr/src/ROCm-CompilerSupport-rocm-3.5.0/lib/comgr/src/comgr-device-libs.cpp:118:18: error: 'StringSwitch' was not declared in this scope
  118 |     bool *Flag = StringSwitch<bool *>(Option)
      |                  ^~~~~~~~~~~~
/home/kuestner/.cache/yay/comgr/src/ROCm-CompilerSupport-rocm-3.5.0/lib/comgr/src/comgr-device-libs.cpp:118:31: error: expected primary-expression before 'bool'
  118 |     bool *Flag = StringSwitch<bool *>(Option)
      |                               ^~~~
/home/kuestner/.cache/yay/comgr/src/ROCm-CompilerSupport-rocm-3.5.0/lib/comgr/src/comgr-device-libs.cpp:117:14: warning: unused variable 'Option' [-Wunused-variable]
  117 |   for (auto &Option : ActionInfo->getOptions(true)) {
      |              ^~~~~~
make[2]: *** [CMakeFiles/amd_comgr.dir/build.make:96: CMakeFiles/amd_comgr.dir/src/comgr-device-libs.cpp.o] Error 1
make[2]: Leaving directory '/home/kuestner/.cache/yay/comgr/src/build'
make[1]: *** [CMakeFiles/Makefile2:718: CMakeFiles/amd_comgr.dir/all] Error 2
make[1]: Leaving directory '/home/kuestner/.cache/yay/comgr/src/build'
make: *** [Makefile:183: all] Error 2
make: Leaving directory '/home/kuestner/.cache/yay/comgr/src/build'
==> ERROR: A failure occurred in build().
    Aborting...
error making: %!s(func() string=0x555555a2b830)

</details>

**Comment by acxz** [comment]
@tkuestner see the [readme](https://github.com/rocm-arch/rocm-arch/blob/master/README.md) for instructions on how to use the binary packages arch4edu provides (be sure to give them a star!) if you just want to install `comgr`. We only recommend compiling `comgr` if you plan on developing/contributing to the repository.

In terms of the error, I am not able to reproduce. Maybe others can chime in.

Also you can use the backticks "``" to wrap codeblocks instead of `>` which is used for quotes. Since you have a long log I would also recommend using a dropdown. See: https://gist.github.com/citrusui/07978f14b11adada364ff901e27c7f61

**Comment by acxz** [comment]
I'm gonna go ahead and close this issue due to lack of activity and that no one can reproduce.

**Comment by tkuestner** [comment]
The issue was I installed from llvm-amdgpu-git, which gave me rocm llvm version 12.0.0. Compiling comgr with this newer llvm version resulted in errors.
I reverted that and installed the regular llvm-amdgpu and now everything works fine.

**Comment by acxz** [comment]
glad to hear
