### ISSUE TITLE
[rocblas] sgemm internal error, tensile solution found but not kernel

### ISSUE THREAD

**Issue by goastler** [rocm-arch/rocm-arch#312]
Hi,

Hopefully this is the right place for this issue!

I've built the rocm libraries on arch linux running kernel 5.7. All libraries built apart from RCCL which I built manually using the rocm docs. Everything compiled correctly and seemed fine.

To test the GPU, I ran the following:
```python
x = tf.Variable(3, name="x")
y = tf.Variable(4, name="y")
f = x * x + y * y + 2

tf.print(f)
```
Which prints 27 so the GPU should be working - all well and good.

When I come to run a simple keras / tensorflow model however, all is not well. Here's the code I run:
```python
    # load the train
    name = "et_1000"
    train = np.loadtxt(name + '_train.csv', delimiter=',')
    # split into input (X) and output (y) variables
    train_data = train[:, 0:train.shape[1]-1]
    train_labels = train[:, train.shape[1]-1]
    # define the keras model
    model = Sequential()
    model.add(Dense(12, input_dim=train_data.shape[1], activation='relu'))
    model.add(Dense(8, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    # compile the keras model
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    # fit the keras model on the train
    model.fit(train_data, train_labels, epochs=100000, batch_size=10,
              callbacks=[EarlyStopping(
        patience=1000,
        min_delta=1e-10,
        monitor="loss",
        restore_best_weights=True,
    )]
              )
    # evaluate the keras model
    test = np.loadtxt(name + '_test.csv', delimiter=',')
    test_data = test[:, 0:test.shape[1]-1]
    test_labels = test[:, test.shape[1]-1]
    _, accuracy = model.evaluate(test_data, test_labels)
    print('Accuracy: %.4f' % (accuracy * 100))
```
Nothing special here, just a simple network. Upon running the above code I get the following error:
```
2020-08-13 09:04:42.725334: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7399 MB memory) -> physical GPU (device: 0, name: Ellesmere [Radeon RX 470/480/570/570X/580/580X/590], pci bus id: 0000:07:00.0)
27
Epoch 1/100000
2020-08-13 09:04:43.583230: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library librocblas.so
Error: Tensile solution found, but Kernel Cijk_Ailk_Bljk_SB_MT32x8x64_SE_APM1_AF0EM1_AF1EM1_AMAS3_ASBE01_ASEM1_BL1_DTL0_EPS0_FL0_GRVW2_GSU32_ISA803_IU1_K1_KLA_LBSPPn1_LPA0_LPB0_LDL1_NLCA1_NLCB1_ONLL1_PBD0_PK0_PGR0_PLR1_RK0_SIA1_SU32_SUM0_SUS256_SNLL0_TT2_2_TLDS0_USFGROn1_VAW1_VSn1_VW2_WG16_4_4_WGM1 not found in any loaded module. exception thown for { a_type: "f32_r", b_type: "f32_r", c_type: "f32_r", d_type: "f32_r", compute_type: "f32_r", transA: 'N', transB: 'N', M: 12, N: 10, K: 1000, lda: 12, ldb: 1000, ldc: 12, ldd: 12, beta: -12345.0, batch_count: 1, stride_a: 12000, stride_b: 10000, stride_c: 120, stride_d: 120 }

2020-08-13 09:04:50.195043: E tensorflow/stream_executor/rocm/rocm_blas.cc:413] failed to run ROCBLAS routine rocblas_sgemm: rocblas_status_internal_error
```
This error is thrown on the model.fit call. The first line states something about the tensile solution being okay but not the kernel. I'm not exactly sure what's causing this issue. The options I can think of are:
- Dodgy rccl library (as I built it from source myself - but used the install bash script)
- Dodgy rocblas library (which would make sense given the rocblas_sgemm error)
- Something to do with my specific GPU (I'm running an RX570)
- Kernel 5.7 incompatibility. I've got kernel 5.4 installed which I will try next.

This issue is isolated to arch. I've tried the exact same setup on ubuntu, installing the equivalent modules, and all runs well. This makes me think it's something to do with either rccl or rocblas. Note, with ubuntu I installed rccl without problem using apt-get so no manual compilation.

I was hoping to get @acxz 's opinion on the error as I've followed several of your issues / solutions for the installation of rocm on arch.

**Comment by acxz** [comment]
> I've built the rocm libraries on arch linux running kernel 5.7. All libraries built apart from RCCL which I built manually using the rocm docs. Everything compiled correctly and seemed fine.

Can you clarify this statement a bit?
Are all libraries installed from the AUR/arch4edu?

Also how have you installed tensorflow? Compiled from source, AUR package, pypi/tensorflow-rocm?

> To test the GPU, I ran the following:

I'm afraid that codeblock doesn't tell us if the GPU is being used or not. Can you try the [following](https://www.tensorflow.org/guide/gpu#logging_device_placement)?

> 2020-08-13 09:04:42.725334: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7399 MB memory) -> physical GPU (device: 0, name: Ellesmere [Radeon RX 470/480/570/570X/580/580X/590], pci bus id: 0000:07:00.0)
27

Ah nvm I guess the output from your model has the following confirming the GPU is trying to be used

hmm since this error is happening with tensorflow I think it is better placed over at the tensorflow-rocm repo. Do you mind if I transfer the issue over there?
For us to classify and debug this as a rocblas issue, it is best to reproduce the error purely using rocblas. tensorflow is a huge codebase and a lot of things could be happening.

> Dodgy rccl library (as I built it from source myself - but used the install bash script)

Please use the AUR/arch4edu package for rccl since we do not support source installs.

> Dodgy rocblas library (which would make sense given the rocblas_sgemm error)

We can do a comparison to make sure that the AUR rocblas package installs the same files as the ubuntu rocblas package.
Do you notice any differences when comparing the output `pacman -Ql rocblas` and the rocblas files under [rocm-deb-installation-files.txt](https://github.com/rocm-arch/rocm-arch/files/4776798/rocm-deb-installation-files.txt)?
If so then we can create a separate issue rocblas that may solve this one.

> Something to do with my specific GPU (I'm running an RX570)

As for this, take a look at: https://github.com/RadeonOpenCompute/ROCm#supported-gpus
> The following list of GPUs are enabled in the ROCm software, though full support is not guaranteed:
>    GFX8 GPUs
>       "Polaris 11" chips, such as on the AMD Radeon RX 570 and Radeon Pro WX 4100

I don't think we should rule this issue out with this concern tho, since it mostly likely something on the software side (or atleast we should exhaust that possibility first)

> Kernel 5.7 incompatibility. I've got kernel 5.4 installed which I will try next.

This could be another one, but I'd look into this after we make sure that the rocblas installation matches.

**Comment by haampie** [comment]
Actually I'm getting the same error after following rocBLAS's build script of this repo -- I don't have Arch linux.

I think it has to do with Tensile.

If you install rocBLAS using `apt-get` on ubuntu, you get a plain `rocblas/lib/librocblas.so` and that's all. When you use the build script from this repo and you have an actual AMD GPU, it will use Tensile to optimize kernels, and you get a folder `library` inside of `lib` with the following contents:

```
$ ls library/
Kernels.so-000-gfx803.hsaco  Kernels.so-000-gfx900.hsaco  Kernels.so-000-gfx906.hsaco  Kernels.so-000-gfx908.hsaco  TensileLibrary_gfx803.co  TensileLibrary_gfx900.co  TensileLibrary_gfx906.co  TensileLibrary_gfx908.co  TensileLibrary.yaml
```

I have a gfx908 arch GPU, and when I compile a trivial gemm:

```c++
#include <iostream>
#include <vector>
#include "rocblas.h"

int main()
{
    rocblas_int N = 10;

    double alpha = 1.0;
    double beta = 0.0;

    // create a and b on the host
    std::vector<double> A_h(N * N, 1.0);
    std::vector<double> B_h(N * N, 1.0);
    std::vector<double> C_h(N * N, 0.0);

    double * A_d;
    double * B_d;
    double * C_d;

    rocblas_handle handle;
    rocblas_create_handle(&handle);

    // allocate memory on device
    hipMalloc(&A_d, N * N * sizeof(double));
    hipMalloc(&B_d, N * N * sizeof(double));
    hipMalloc(&C_d, N * N * sizeof(double));

    hipMemcpy(A_d, A_h.data(), sizeof(double) * N * N, hipMemcpyHostToDevice);
    hipMemcpy(B_d, B_h.data(), sizeof(double) * N * N, hipMemcpyHostToDevice);
    hipMemcpy(C_d, C_h.data(), sizeof(double) * N * N, hipMemcpyHostToDevice);

    rocblas_dgemm(handle, rocblas_operation_none, rocblas_operation_none, N, N, N, &alpha, A_d, N, B_d, N, &beta, C_d, N);

    // copy output from device memory to host memory
    hipMemcpy(C_h.data(), C_d, sizeof(double) * N * N, hipMemcpyDeviceToHost);

    // verify rocblas_scal result
    auto err = 0.0;
    for (size_t i = 0; i < N * N; ++i)
        err += std::abs(C_h[i] - N);
    
    std::cout << "Error = " << err << '\n';

    hipFree(A_d);
    hipFree(B_d);
    hipFree(C_d);
    rocblas_destroy_handle(handle);
}
```
using
```
hipcc -std=c++14 -I /path/to/rocblas-3.5.0-dw53bgvdvqnorc3yhrofeph4otryt3jz/include/ dgemm.cpp -L /path/to/rocblas/lib/ -lrocblas
```

It outputs:

```
Error: Tensile solution found, but Kernel Cijk_Ailk_Bljk_DB_MT32x64x8_SN_APM1_AF0EM1_AF1EM1_AMAS3_ASBE01_ASEM1_BL1_DTL0_EPS1_FL1_GRVW2_GSU1_ISA906_IU1_K1_KLA_LBSPPn1_LPA0_LPB0_LDL1_NLCA1_NLCB1_ONLL1_PBD0_PK0_PGR1_PLR1_RK0_SIA1_SU0_SUM0_SUS256_SNLL1_TT4_4_TLDS0_USFGRO0_VAW1_VS1_VW2_WG8_16_1_WGM1 not found in any loaded module. exception thown for { a_type: "f64_r", b_type: "f64_r", c_type: "f64_r", d_type: "f64_r", compute_type: "f64_r", transA: 'N', transB: 'N', M: 10, N: 10, K: 10, lda: 10, ldb: 10, ldc: 10, ldd: 10, beta: -12345.0, batch_count: 1, stride_a: 100, stride_b: 100, stride_c: 100, stride_d: 100 }
```

It seems this kernel does exist, though:

```
$ grep Cijk_Ailk_Bljk_DB_MT32x64x8_SN_APM1_AF0EM1_AF1EM1_AMAS3_ASBE01_ASEM1_BL1_DTL0_EPS1_FL1_GRVW2_GSU1_ISA906_IU1_K1_KLA_LBSPPn1_LPA0_LPB0_LDL1_NLCA1_NLCB1_ONLL1_PBD0_PK0_PGR1_PLR1_RK0_SIA1_SU0_SUM0_SUS256_SNLL1_TT4_4_TLDS0_USFGRO0_VAW1_VS1_VW2_WG8_16_1_WGM1 /path/to/rocblas/lib/  -r
Binary file /path/to/rocblas/lib/library/TensileLibrary_gfx906.co matches
/path/to/rocblas/lib/library/TensileLibrary.yaml:  name: Cijk_Ailk_Bljk_DB_MT32x64x8_SN_APM1_AF0EM1_AF1EM1_AMAS3_ASBE01_ASEM1_BL1_DTL0_EPS1_FL1_GRVW2_GSU1_ISA906_IU1_K1_KLA_LBSPPn1_LPA0_LPB0_LDL1_NLCA1_NLCB1_ONLL1_PBD0_PK0_PGR1_PLR1_RK0_SIA1_SU0_SUM0_SUS256_SNLL1_TT4_4_TLDS0_USFGRO0_VAW1_VS1_VW2_WG8_16_1_WGM1
/path/to/rocblas/lib/library/TensileLibrary.yaml:  name: Cijk_Ailk_Bljk_DB_MT32x64x8_SN_APM1_AF0EM1_AF1EM1_AMAS3_ASBE01_ASEM1_BL1_DTL0_EPS1_FL1_GRVW2_GSU1_ISA906_IU1_K1_KLA_LBSPPn1_LPA0_LPB0_LDL1_NLCA1_NLCB1_ONLL1_PBD0_PK0_PGR1_PLR1_RK0_SIA1_SU0_SUM0_SUS256_SNLL1_TT4_4_TLDS0_USFGRO0_VAW1_VS1_VW2_WG8_16_1_WGM1
```

since the symbol is found in this `.co` file.

**Comment by acxz** [comment]
Thanks for looking into this @haampie!
Okay so we have confirmed where the root issue is, but I'm afraid I don't know the solution. Maybe going upstream about this issue can give us more clues.

**Comment by haampie** [comment]
Let me make an issue in the rocBLAS repo

**Comment by haampie** [comment]
Btw, the corresponding Tensile version has the following in their last commit:

https://github.com/ROCmSoftwarePlatform/Tensile/commit/f842a1a4427624eff6cbddb2405c36dec9a210cd#diff-71fdb92488b0a07be4968071daa33a51R191-R192

Something with CodeObjectVersion V3, whereas the default in the cmake version in rocBLAS is V2.

Let me try to recompile with `-DCODE_OBJECT_VERSION=V3`. I'll report back in ... multiple hours when rocBLAS is finally done compiling :upside_down_face: ref https://github.com/ROCmSoftwarePlatform/Tensile/issues/1128

**Comment by haampie** [comment]
It's not that

**Comment by acxz** [comment]
bummer, thx for checking that out tho!

**Comment by acxz** [comment]
@goastler can you confirm if updating to the latest rocblas fixes the original issue for you?
If it does not feel free to open up another issue for it.

**Comment by goastler** [comment]
@acxz @haampie

**In answer to above:**

All libraries were originally installed from the AUR, I was unaware of arch4edu and rccl wasn't compiling properly during the pkgbuild from AUR so I compiled myself.

GPU is definitely being used.

I'll have a look at the ubuntu install differences and report back.

**In other news:**

 I've uninstalled all rocm related libraries, added the arch4edu repo and reinstalled all libraries from there as requested. This has successfully installed rccl so I should have a regular setup now. However, this hasn't fixed my issues.

Upon reboot I got the same amdgpu 3.5 kernel bug listed in issue #269 . I upgraded to kernel 5.8 just to get my system to boot. No kernel bug now, but same rocblas error. #269 says it's working on kernel 5.6, but I do not have that available on manjaro so I'm going to try the 5.4 LTS kernel and report back in a minute.

**Comment by goastler** [comment]
Kernel 5.4 doesn't work, same error :(

**Comment by haampie** [comment]
Are you sure rocblas was installed with those two new flags? What does your rocBLAS install folder look like when you run `tree path/to/rocblas`?

**Comment by goastler** [comment]
Not sure as my rocblas came from arch4edu so it's precompiled, right? Yay doesn't give the option to edit the pkgbuild when installing from arch4edu.

```
/opt/rocm/rocblas/
├── include
│   ├── rocblas-auxiliary.h
│   ├── rocblas_bfloat16.h
│   ├── rocblas-complex-types.h
│   ├── rocblas-exported-proto.hpp
│   ├── rocblas-export.h
│   ├── rocblas-functions.h
│   ├── rocblas.h
│   ├── rocblas-types.h
│   └── rocblas-version.h
└── lib
    ├── cmake
    │   └── rocblas
    │       ├── rocblas-config.cmake
    │       ├── rocblas-config-version.cmake
    │       ├── rocblas-targets.cmake
    │       └── rocblas-targets-release.cmake
    ├── library
    │   ├── Kernels.so-000-gfx803.hsaco
    │   ├── Kernels.so-000-gfx900.hsaco
    │   ├── Kernels.so-000-gfx906.hsaco
    │   ├── Kernels.so-000-gfx908.hsaco
    │   ├── TensileLibrary_gfx803.co
    │   ├── TensileLibrary_gfx900.co
    │   ├── TensileLibrary_gfx906.co
    │   ├── TensileLibrary_gfx908.co
    │   └── TensileLibrary.yaml
    ├── librocblas.so -> librocblas.so.0
    ├── librocblas.so.0 -> librocblas.so.0.1
    └── librocblas.so.0.1
```

**Comment by goastler** [comment]
The AUR pkgbuild does have both of those flags from #313 so I'll try installing from there.

**Comment by haampie** [comment]
> The AUR pkgbuild does have both of those flags from #313 so I'll try installing from there.

Yes... that's not a big surprise since this repo == AUR.

Please try that, cause from your `tree` output it looks like arch4edu is not compiling with `BUILD_WITH_TENSILE_HOST=OFF`. There shouldn't be this `library/` folder, everything should be merged into `librocblas.so`.

**Comment by tpkessler** [comment]
When a package included in arch4edu is updated on the AUR, it's queued for compilation. Depending on the number updated packages and their size (rocblas takes forever to build) it may take a while before the package is updated in the arch4edu repo. I think that the updated rocblas will be available from arch4edu during this afternoon, perhaps tomorrow (depends on the mirror you use).

**Comment by goastler** [comment]
I see :)

I'm reinstalling from AUR, will let you know what happens.

**Comment by goastler** [comment]
Now getting the following error when attempting to install rocblas from AUR

```
CMake Error at /usr/share/cmake-3.18/Modules/CMakeTestCXXCompiler.cmake:59 (message):
  The C++ compiler

    "/opt/rocm/hip/bin/hipcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/goastler/.cache/yay/rocblas/src/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/make cmTC_ae927/fast && /usr/bin/make  -f CMakeFiles/cmTC_ae927.dir/build.make CMakeFiles/cmTC_ae927.dir/build
    make[1]: Entering directory '/home/goastler/.cache/yay/rocblas/src/build/CMakeFiles/CMakeTmp'
    Building CXX object CMakeFiles/cmTC_ae927.dir/testCXXCompiler.cxx.o
    /opt/rocm/hip/bin/hipcc   -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe  -fno-plt  -o CMakeFiles/cmTC_ae927.dir/testCXXCompiler.cxx.o -c /home/goastler/.cache/yay/rocblas/src/build/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
    clang-11: error: no such file or directory: 'hip.amdgcn.bc'
    clang-11: error: no such file or directory: 'ocml.amdgcn.bc'
    clang-11: error: no such file or directory: 'ockl.amdgcn.bc'
    clang-11: error: no such file or directory: 'oclc_finite_only_off.amdgcn.bc'
    clang-11: error: no such file or directory: 'oclc_daz_opt_on.amdgcn.bc'
    clang-11: error: no such file or directory: 'oclc_correctly_rounded_sqrt_on.amdgcn.bc'
    clang-11: error: no such file or directory: 'oclc_unsafe_math_off.amdgcn.bc'
    clang-11: error: no such file or directory: 'oclc_isa_version_803.amdgcn.bc'
    clang-11: error: no such file or directory: 'oclc_wavefrontsize64_on.amdgcn.bc'
    make[1]: *** [CMakeFiles/cmTC_ae927.dir/build.make:85: CMakeFiles/cmTC_ae927.dir/testCXXCompiler.cxx.o] Error 1
    make[1]: Leaving directory '/home/goastler/.cache/yay/rocblas/src/build/CMakeFiles/CMakeTmp'
    make: *** [Makefile:140: cmTC_ae927/fast] Error 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:29 (project)

```

**Comment by haampie** [comment]
is rocm-device-libs properly installed? try `find /opt/rocm -name hip.amdgcn.bc`

**Comment by goastler** [comment]
Just reinstalled rocm-device-libs and the following warnings occurred

```
:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                                         [#######################################] 100%
(1/1) checking package integrity                                       [#######################################] 100%
(1/1) loading package files                                            [#######################################] 100%
(1/1) checking for file conflicts                                      [#######################################] 100%
(1/1) checking available disk space                                    [#######################################] 100%
warning: could not get file information for opt/rocm/lib/cmake/AMDDeviceLibs/
warning: could not get file information for opt/rocm/lib/cmake/AMDDeviceLibs/AMDDeviceLibsConfig.cmake
warning: could not get file information for opt/rocm/lib/hc.amdgcn.bc
warning: could not get file information for opt/rocm/lib/hip.amdgcn.bc
warning: could not get file information for opt/rocm/lib/ockl.amdgcn.bc
warning: could not get file information for opt/rocm/lib/oclc_correctly_rounded_sqrt_off.amdgcn.bc
warning: could not get file information for opt/rocm/lib/oclc_correctly_rounded_sqrt_on.amdgcn.bc
warning: could not get file information for opt/rocm/lib/oclc_daz_opt_off.amdgcn.bc
warning: could not get file information for opt/rocm/lib/oclc_daz_opt_on.amdgcn.bc
warning: could not get file information for opt/rocm/lib/oclc_finite_only_off.amdgcn.bc
warning: could not get file information for opt/rocm/lib/oclc_finite_only_on.amdgcn.bc
warning: could not get file information for opt/rocm/lib/oclc_isa_version_1010.amdgcn.bc
warning: could not get file information for opt/rocm/lib/oclc_isa_version_1011.amdgcn.bc
warning: could not get file information for opt/rocm/lib/oclc_isa_version_1012.amdgcn.bc
warning: could not get file information for opt/rocm/lib/oclc_isa_version_700.amdgcn.bc
warning: could not get file information for opt/rocm/lib/oclc_isa_version_701.amdgcn.bc
warning: could not get file information for opt/rocm/lib/oclc_isa_version_702.amdgcn.bc
warning: could not get file information for opt/rocm/lib/oclc_isa_version_801.amdgcn.bc
warning: could not get file information for opt/rocm/lib/oclc_isa_version_802.amdgcn.bc
warning: could not get file information for opt/rocm/lib/oclc_isa_version_803.amdgcn.bc
warning: could not get file information for opt/rocm/lib/oclc_isa_version_810.amdgcn.bc
warning: could not get file information for opt/rocm/lib/oclc_isa_version_900.amdgcn.bc
warning: could not get file information for opt/rocm/lib/oclc_isa_version_902.amdgcn.bc
warning: could not get file information for opt/rocm/lib/oclc_isa_version_904.amdgcn.bc
warning: could not get file information for opt/rocm/lib/oclc_isa_version_906.amdgcn.bc
warning: could not get file information for opt/rocm/lib/oclc_isa_version_908.amdgcn.bc
warning: could not get file information for opt/rocm/lib/oclc_unsafe_math_off.amdgcn.bc
warning: could not get file information for opt/rocm/lib/oclc_unsafe_math_on.amdgcn.bc
warning: could not get file information for opt/rocm/lib/oclc_wavefrontsize64_off.amdgcn.bc
warning: could not get file information for opt/rocm/lib/oclc_wavefrontsize64_on.amdgcn.bc
warning: could not get file information for opt/rocm/lib/ocml.amdgcn.bc
warning: could not get file information for opt/rocm/lib/opencl.amdgcn.bc
```

Installing rocblas then hangs with hundreds of errors like below
```
<instantiation>:1:1: error: instruction not supported on this GPU
v_add_u32 v68, vcc, v64, 48 
^
/home/goastler/.cache/yay/rocblas/src/assembly/Cijk_Alik_Bljk_ZB_MT64x64x4_SN_APM1_AF0EM1_AF1EM1_AMAS0_ASBE01_ASEM1_BL1_DTL0_EPS1_FL0_GRVW1_GSUmq_jEenUSR5ctiyRzVus53rneLMR8wsvzGyCugAJBz0=.s:3375:1: note: while in macro instantiation
_v_add_co_u32 v68, vcc, v64, 48                    // coord0.1: coord0 += d0*sg0*VW + vc0
^
<instantiation>:1:1: error: instruction not supported on this GPU
v_add_u32 v75, vcc, v66, v68
^
/home/goastler/.cache/yay/rocblas/src/assembly/Cijk_Alik_Bljk_ZB_MT64x64x4_SN_APM1_AF0EM1_AF1EM1_AMAS0_ASBE01_ASEM1_BL1_DTL0_EPS1_FL0_GRVW1_GSUmq_jEenUSR5ctiyRzVus53rneLMR8wsvzGyCugAJBz0=.s:3379:1: note: while in macro instantiation
_v_add_lshl_u32 v75, v66, v68, 0x4                 // scaleToBpe: accumulate d0 lower and *= bpe into Cin addr
^
<instantiation>:1:1: error: instruction not supported on this GPU
v_add_u32 v75, vcc, v67, v68
^
/home/goastler/.cache/yay/rocblas/src/assembly/Cijk_Alik_Bljk_ZB_MT64x64x4_SN_APM1_AF0EM1_AF1EM1_AMAS0_ASBE01_ASEM1_BL1_DTL0_EPS1_FL0_GRVW1_GSUmq_jEenUSR5ctiyRzVus53rneLMR8wsvzGyCugAJBz0=.s:3382:1: note: while in macro instantiation
_v_add_lshl_u32 v75, v67, v68, 0x4                 // emitLddChange: accumulate d0 lower and *= bpe into addr
^
warning: ISA: (9, 0, 6)  is not supported; overriding with  (9, 0, 0)
Command '['/usr/bin/clang++', '-x', 'assembler', '-target', 'amdgcn-amd-amdhsa', '-mcpu=gfx900', '-c', '-o', '/home/goastler/.cache/yay/rocblas/src/assembly/Cijk_Alik_Bljk_ZB_MT64x64x4_SN_APM1_AF0EM1_AF1EM1_AMAS0_ASBE01_ASEM1_BL1_DTL0_EPS1_FL0_GRVW1_GSUmq_jEenUSR5ctiyRzVus53rneLMR8wsvzGyCugAJBz0=.o', '/home/goastler/.cache/yay/rocblas/src/assembly/Cijk_Alik_Bljk_ZB_MT64x64x4_SN_APM1_AF0EM1_AF1EM1_AMAS0_ASBE01_ASEM1_BL1_DTL0_EPS1_FL0_GRVW1_GSUmq_jEenUSR5ctiyRzVus53rneLMR8wsvzGyCugAJBz0=.s']' returned non-zero exit status 1.
```

**Comment by goastler** [comment]
The `find` command resolves to `/opt/rocm/lib/hip.amdgcn.bc`

**Comment by acxz** [comment]
> If it does not feel free to open up another issue for it.

I'm gonna lock this thread as offtopic, if you could open up a new issue for the problems you are facing @goastler that would be great.
