### ISSUE TITLE
Package Request Thread

### ISSUE THREAD

**Issue by acxz** [rocm-arch/rocm-arch#34]
Here are some packages that are provided by upstream ROCm but not in the AUR: [Link](https://github.com/RadeonOpenCompute/ROCm/blob/master/README.md#rocm-platform-packages)
For reference, [here](http://repo.radeon.com/rocm/apt/debian/pool/main/) is the Ubuntu package repository for ROCm.

- [x] [`mivisionx`](https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX)
- [x] [`migraphx`](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX)
- [x] [`atmi`](https://github.com/RadeonOpenCompute/atmi)
- [x] [`aomp`](https://github.com/ROCM-Developer-Tools/aomp)

**Comment by tpkessler** [comment]
`aomp` is tricky. As of now, they rely on custom versions of the ROCm stack. You basically have to recompile every package specifically for the use of aomp. In addition, their tool chain is based on bash scripts. Maybe this will change with the release of version 11.0

**Comment by acxz** [comment]
Yeah, I wasn't able to get aomp building. I pushed what I had tho.
