### ISSUE TITLE
[hcc] HCC build failure

### ISSUE THREAD

**Issue by Laser-Cat** [rocm-arch/rocm-arch#35]
I have the following error during building 
ln: failed to create symbolic link '/home/lasercat/Downloads/rocm-arch-master/hcc/pkg/hcc/usr/bin/bin': File exists
Possibly caused by:
https://github.com/rocm-arch/rocm-arch/blob/4b767fa63e0bcb9b5ff76afb374256aae4db1e8e/hcc/PKGBUILD#L53
I changed to
```
  for _fn in hcc hcc-config; do
    ln -s "/opt/rocm/hcc/bin/$_fn" "$pkgdir/usr/bin/$_fn";
  done
```
and it can then generate a package(not sure whether the built package works properly tho).

**Comment by acxz** [comment]
@Laser-Cat thanks for the bug reports! Note, one of the big reasons as to why we moved our development to github was that people can submit PRs. Feel free to create PRs if you think you have found a fix to your issues! It will make testing easier and getting the fix out much faster.
