### ISSUE TITLE
[rocm-opencl-runtime] Update to new release

### ISSUE THREAD

**Issue by tpkessler** [rocm-arch/rocm-arch#351]

**Comment by naetherm** [comment]
Closed in https://github.com/rocm-arch/rocm-arch/commit/e3d88440f0a785029ecabe07d614241ff14f135b

As there is no tagged release the corresponding branch was used.

**Comment by acxz** [comment]
Please look carefully @naetherm there is a tagged release: https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime/releases/tag/rocm-3.7.0

If there wasn't we should not be using a branch for a release only tags. This puts a considerably load on users needing to rebuild for every commit on a branch. The appropriate name for such a package would be `rocm-opencl-runtime-3.7.0-git` or something like that.

**Comment by tpkessler** [comment]
> As there is no tagged release the corresponding branch was used.

There is, but it's hidden because they changed the naming from `roc-version` to `rocm-version`. Click on "Releases" and then on "Show 2 newer tags".

**Comment by acxz** [comment]
Closed with 0ff2b4e
