### ISSUE TITLE
[hip-rocclr] does not build:

### ISSUE THREAD

**Issue by neoabs** [rocm-arch/rocm-arch#387]
![image](https://user-images.githubusercontent.com/53402602/90975713-fb940d00-e536-11ea-9d1d-eb08618d2659.png)

It says ot cannot read file:
/var/tmp/pamac-build-szpieg/rocclr/src/build/lib/cmake/rocclr/rocclr-targets.cmake

Building on manjaro with pamac

**Comment by neoabs** [comment]
Just follow-up: It builds now

**Comment by acxz** [comment]
glad to hear!
