### ISSUE TITLE
[rocm-dbgapi] cmake fails due to missing docs

### ISSUE THREAD

**Issue by JakeStanger** [rocm-arch/rocm-arch#406]
The installation step for `rocm-dbgabi` fails due to missing docs. This may be related to the latest update to the package that stripped out the docs building step.

```
Install the project...
-- Install configuration: ""
-- Installing: /home/jake/.cache/yay/rocm-dbgapi/pkg/rocm-dbgapi/opt/rocm/lib/librocm-dbgapi.so.0.30.0
-- Installing: /home/jake/.cache/yay/rocm-dbgapi/pkg/rocm-dbgapi/opt/rocm/lib/librocm-dbgapi.so.0
-- Set runtime path of "/home/jake/.cache/yay/rocm-dbgapi/pkg/rocm-dbgapi/opt/rocm/lib/librocm-dbgapi.so.0.30.0" to ""
-- Installing: /home/jake/.cache/yay/rocm-dbgapi/pkg/rocm-dbgapi/opt/rocm/lib/librocm-dbgapi.so
-- Installing: /home/jake/.cache/yay/rocm-dbgapi/pkg/rocm-dbgapi/opt/rocm/include/amd-dbgapi.h
-- Installing: /home/jake/.cache/yay/rocm-dbgapi/pkg/rocm-dbgapi/opt/rocm/share/doc/amd-dbgapi/LICENSE.txt
-- Installing: /home/jake/.cache/yay/rocm-dbgapi/pkg/rocm-dbgapi/opt/rocm/lib/cmake/amd-dbgapi/amd-dbgapi-config.cmake
-- Installing: /home/jake/.cache/yay/rocm-dbgapi/pkg/rocm-dbgapi/opt/rocm/lib/cmake/amd-dbgapi/amd-dbgapi-targets.cmake
-- Installing: /home/jake/.cache/yay/rocm-dbgapi/pkg/rocm-dbgapi/opt/rocm/lib/cmake/amd-dbgapi/amd-dbgapi-targets-noconfig.cmake
CMake Error at cmake_install.cmake:134 (file):
  file INSTALL cannot find
  "/home/jake/.cache/yay/rocm-dbgapi/src/build/doc/html": No such file or
  directory.
```

**Comment by tpkessler** [comment]
Hi Jake, I cannot reproduce your error. Did you clear `yay`'s cache before the installation? We recommend the binary packages from `arch4edu`. See our README.

Torsten

**Comment by JakeStanger** [comment]
Hi Torsten, thanks for getting back to me. I've just tried again after clearing `yay`'s cache and it did not help. Adding the binary repo does of course solve the problem, but I'd ideally prefer to stick to just the official repos.

I'm not sure what information I can provide other than the log above, but I'm happy to provide anything so let me know.

**Comment by tpkessler** [comment]
I found the cause for this problem: In a clean chroot, `doxygen` is not installed which means that `cmake` does not find it and skips the generation of the documentation. If you build with `doxygen` installed, `make` tries to install the documentation without having it generated before (for this you need to call the `build` target). A quick way to fix this is to remove the line `find_package(Doxygen)` from `CMakeLists.txt`.

**Comment by acxz** [comment]
This is how one of sister projects, ([gentoo's rocm](https://github.com/justxi/rocm)), is handling this issue:

https://github.com/justxi/rocm/blob/master/dev-libs/amd-dbgapi/amd-dbgapi-3.7.0.ebuild#L23

**Comment by tpkessler** [comment]
Thanks for reporting this @JakeStanger. It's one of the rare instances where building in clean chroot works but not with directly calling `makepkg` in your home directory.
