### ISSUE TITLE
[rocblas] build failed

### ISSUE THREAD

**Issue by darkstego** [rocm-arch/rocm-arch#410]
I get a build fail whenever I try to install rocblas. I am running on a Vega 56 and it keeps generating a ton of errors (400+MB)  filled with errors like
`<instantiation>:1:1: error: instruction not supported on this GPU`

[Here is a link](https://pastebin.com/4bWf0ZEv) to the first 800 lines of the build output and errors.

**Comment by acxz** [comment]
If you just want to install rocblas see https://github.com/rocm-arch/rocm-arch#installation, particularly the precompiled binaries hosted by arch4edu. (Please star them to show support if you end up using them!)

You can also check if your GPU is supported from the official rocm docs:https://github.com/RadeonOpenCompute/ROCm#supported-gpus

**Comment by darkstego** [comment]
The GPU I am using is listed as officially supported (GFX9 GPU). But the build still fails for some reason. I remember I did successfully build it using the same setup several months ago. 

I ended up using the arch4edu binaries.

**Comment by acxz** [comment]
hmm that is weird, I would suggest to opening up an upstream issue over at https://github.com/ROCmSoftwarePlatform/rocBLAS then.

**Comment by tpkessler** [comment]
Do you have a second dGPU in your PC @darkstego? Which version of `llvm-amdgpu` are you using? For me, it seems to be a problem on the compiler side (the error says that `v_add_u32` is not supported) not that much on tensile (this error is part of the tensile configuration, which is a prerequisite for RocBLAS)

**Comment by darkstego** [comment]
I have a second GPU on the system. AMD Vega 56 that is the GPU for linux, and another Nvidia card that is passed to a VM through VFIO. I was thinking that this could be an issue, even though early on it does find the compatible AMD GPU.

llvm-amdgpu is version 3.7.0
