### ISSUE TITLE
[hip-rocclr] Missing gfx803 archicture in list

### ISSUE THREAD

**Issue by tpkessler** [rocm-arch/rocm-arch#416]
Fixed with #415

**Comment by oleid** [comment]
There might still be bits missing. This is my latest upstream issue: https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/1110

With `AMD_LOG_LEVEL=1` I get the following error:

```
Error: runtime metadata section not present in ELF program binary                                                                          
Error: Cannot Global Var Sizes
```

**Comment by tpkessler** [comment]
`hip-rocclr` was removed with 4.5.0. Its successor is `hip-runtime-amd`.
