### ISSUE TITLE
[llvm-amdgpu-git] MAKEFLAGS still uses undefined $THREADS

### ISSUE THREAD

**Issue by rmsc** [rocm-arch/rocm-arch#418]
Commit beebfd5b6c0a3b4da87e70970a22586e1abaf68c removed the thread logic, but in build() there's still a reference to $THREADS:

`MAKEFLAGS="$MAKEFLAGS -j$THREADS" make`

**Comment by rmsc** [comment]
By the way, this essentially overrides whatever -j option is set in makepkg.conf, and removes the limit on compilation processes. It generates dozens of compiler processes.

**Comment by rigred** [comment]
Why was this build logic removed in the first place?
It's now just going to run away with way too much memory on a bunch of threads that all stall for IO if someone doesn't have enough resources.

**Comment by rmsc** [comment]
IMO the PKGBUILD should just respect whatever was put in makepkg.conf, which it does after the fix. The runaway was just a bug, and IMO removing the logic was a good thing.

**Comment by tpkessler** [comment]
@rigred  because of https://github.com/rocm-arch/rocm-arch/pull/368#issue-471953438

**Comment by rigred** [comment]
@tpkessler Great to know
I missed that merge but did notice drastic memory use reduction.
