### ISSUE TITLE
[rocm-opencl-runtime] Conflict with opencl-amdgpu-pro-pal, which also use 'amdocl64.icd'

### ISSUE THREAD

**Issue by Kingmk13** [rocm-arch/rocm-arch#420]
Hello,
I am not an expert, so I may say some abominations. Sorry for that.

I tried to install _rocm-opencl-runtime_ on my machine, but it uses a library called "**amdocl64.icd**".
The problem is that _opencl-amdgpu-pro-pal_ also use it elsewhere...
So in the **/etc/OpenCL/vendors/** directory, there can't be 2 identical file.

So it isn't a big issue, maybe you just need to add a conflicting package "_opencl-amdgpu-pro-pal_" in the PKGBUILD ?

NOTE : I have my arch system installed on my arch based laptop (with an APU, the ryzen 2700u + vega10 mobile graphics).
I just discovered that ROCM doesn't support Raven APU :facepalm:  But the issue doesn't depend on hardawre so it still is an "issue".

**Comment by acxz** [comment]
thx for the report @Kingmk13 yep seems like we should add a `opencl-amdgpu-pro-pal` as a conflict.

**Comment by acxz** [comment]
fixed with d821028

**Comment by eingrossfilou** [comment]
Now it is impossible to have rocm-opencl-runtime installed in parallel to any other opencl implementatiion.
I have a system with nvidia and amd gpu. I cannot have open-nvidia nor opencl-mesa installed with rocm-opencl-runtime

**Comment by acxz** [comment]
oh shucks mb thx for pointing that out
