### ISSUE TITLE
[llvm-roc] Uses too much RAM

### ISSUE THREAD

**Issue by marco44** [rocm-arch/rocm-arch#43]
# building LLVM/Clang requires ~1.5G per unit                               
    THREADS=$(( ($(getconf _PHYS_PAGES) * $(getconf PAGESIZE)) / 1610612736 ))  

Is quite wrong. My PC almost just died (was freezing like crazy because of swap storm). Ok, I've got 24 threads (AMD 3900x), so maybe some people get protected from this. Anyway, it was particularly nasty with the last link at 100%. Some ld tasks at the end take over 4GB of RAM.

With 4.5GB instead of 1.5, my system survived…

**Comment by acxz** [comment]
@marco44 what package does this correspond to?

**Comment by acxz** [comment]
mb misclicked

**Comment by marco44** [comment]
llvm-roc, sorry

**Comment by acxz** [comment]
I'm gonna take the build error flag away since, building it self works just fine (also tested it on my machine).

**Comment by marco44** [comment]
Ok, I found what was the difference. I'm building with debug. Without it the memory consumption is much lower. Anyway, building with debug is perfectly valid, maybe there should be either a warning, or avoid setting THREADS in this case?

**Comment by ranisalt** [comment]
Are you by chance using LTO? That sky rockets RAM usage, I can't compile it single thread with 16GB of RAM

**Comment by rigred** [comment]
Closing as no longer relevant. 
LMK if someone thinks otherwise

**Comment by acxz** [comment]
@rigred it seems like this issue is still relevant. Instead of reopening this one, we will just continue the conversation at the above mentioned issue.
