### ISSUE TITLE
[hip-rocclr] compile without using `git` as makedepend

### ISSUE THREAD

**Issue by acxz** [rocm-arch/rocm-arch#448]
I know we have hip-rocclr use `git` as a makedepend: https://github.com/rocm-arch/rocm-arch/blob/master/hip-rocclr/PKGBUILD#L10

but it might be causing some issues downstream. https://github.com/rocm-arch/python-pytorch-rocm/issues/8#issuecomment-711405125
In particular the `.so` that gets created ends up using the git commit instead of the proper version number.

Edit: turns out building without `git` still generates an `.so` file with `-` at the end.

**Comment by tpkessler** [comment]
This helps if you build `hip-rocclr` in a clean chroot but it doesn't prevent `cmake` from picking `git` when running `makepkg` as a normal user on your system with `git` being very likely installed. To really fix the problem, we should patch the `CMakeLists.txt`.

**Comment by tpkessler** [comment]
Patched with above PR.

**Comment by acxz** [comment]
Closed with 1d1b470

Seems like projects like Eigen use the patch number provided when built with git. Reverted the changed.
