### ISSUE TITLE
[comgr] Version 3.9.0-1 fails to build

### ISSUE THREAD

**Issue by Sebastian-Hirsch** [rocm-arch/rocm-arch#460]
### Issue Description

Comgr Version 3.9.0-1 fails to build. The build fails with the following message:

```
==> Beginne build()...
-- The C compiler identification is GNU 10.2.0
-- The CXX compiler identification is GNU 10.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:61 (find_package):
  Could not find a package configuration file provided by "LLD" with any of
  the following names:

    LLDConfig.cmake
    lld-config.cmake

  Add the installation prefix of "LLD" to CMAKE_PREFIX_PATH or set "LLD_DIR"
  to a directory containing one of the above files.  If "LLD" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "/var/tmp/pamac-build-sebastian/comgr/src/build/CMakeFiles/CMakeOutput.log".
==> FEHLER: Ein Fehler geschah in build().
    Breche ab...
```
I attached the CMakeOutput.log for further information.

[CMakeOutput.log](https://github.com/rocm-arch/rocm-arch/files/5471144/CMakeOutput.log)

### System Information

- Operating System: Arch Linux
- KDE Plasma Version: 5.20.2
- KDE Frameworks Version: 5.75.0
- Qt Version: 5.15.1
- Kernel Version: 5.9.2-zen1-1-zen
- OS Type: 64-bit
- Processors: 16 × AMD Ryzen 7 1700X Eight-Core Processor
- Memory: 32 GB of RAM
- Graphics Processor: Radeon RX Vega 56

**Comment by tpkessler** [comment]
I cannot reproduce our build error in a clean chroot with all necessary packages at `3.9.0`. Which version of `llvm-amdgpu` are you using? Make sure that you update to `3.9.0` which has LLD included.

**Comment by Sebastian-Hirsch** [comment]
I used version 3.8.0. I am now trying to upgrade to 3.9.0 but there were issues along the road. I opened a bug for that. I will comment when I could update llvm-amdgpu.

**Comment by acxz** [comment]
@Sebastian-Hirsch llvm-amdgpu has been updated without the unit tests. Please confirm if this error still occurs for you.

**Comment by Sebastian-Hirsch** [comment]
@acxz With the updated llvm-amdgpu package I could install comgr. I will close the issue.
