### ISSUE TITLE
[hip] HIPCC how to define --rocm-path

### ISSUE THREAD

**Issue by skrax** [rocm-arch/rocm-arch#466]
I am building rocm-libs and hipcc is complaining about specifiying '/opt/rocm' with --rocm-path.
I tried setting ROCM_PATH in my profile, however with no success.

For now I am changing the build scripts to add the flag, but it is rather tedious.

How do I specify --rocm-path globally ?

**Comment by acxz** [comment]
Closing this issue in favor of #468
