### ISSUE TITLE
[llvm-amdgpu] Build fails if tensorflow is installed

### ISSUE THREAD

**Issue by bilde2910** [rocm-arch/rocm-arch#473]
Installed via yay with clean build. Build of `llvm-amdgpu` fails on `llvm/lib/Analysis/TFUtils.cpp` when `tensorflow` is installed. TFUtils.cpp includes these headers:

```c
#include "tensorflow/c/c_api.h"
#include "tensorflow/c/c_api_experimental.h"
```

`tensorflow` installs both of these files to:

- /usr/include/tensorflow/tensorflow/c/c_api.h
- /usr/include/tensorflow/tensorflow/c/c_api_experimental.h

Building `llvm-amdgpu` fails:

```
[ 74%] Building CXX object lib/Analysis/CMakeFiles/LLVMAnalysis.dir/TFUtils.cpp.o
/home/kruzah/.cache/yay/llvm-amdgpu/src/llvm-project-rocm-3.9.0/llvm/lib/Analysis/TFUtils.cpp:23:10: fatal error: tensorflow/c/c_api.h: No such file or directory
   23 | #include "tensorflow/c/c_api.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [lib/Analysis/CMakeFiles/LLVMAnalysis.dir/build.make:1330: lib/Analysis/CMakeFiles/LLVMAnalysis.dir/TFUtils.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 74%] Linking CXX executable ../../bin/llvm-readobj
[ 74%] Built target llvm-readobj
Scanning dependencies of target llvm-readelf
[ 74%] Generating ../../bin/llvm-readelf
[ 74%] Built target llvm-readelf
make[1]: *** [CMakeFiles/Makefile2:16834: lib/Analysis/CMakeFiles/LLVMAnalysis.dir/all] Error 2
make: *** [Makefile:171: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
error making: llvm-amdgpu
```

**Comment by acxz** [comment]
Hello @bilde2910, if you don't want to build `llvm-amdgpu` yourself, you can use the `arch4edu` repos as specified in the readme, be sure to give them a star if you use 'em!

While this might be considered an upstream error, ideally you should be building in a clean chroot, anyway. If you end up making an upstream issue about this please link back here.

I think @rmsc also faced this issue: https://github.com/rocm-arch/rocm-arch/issues/302#issuecomment-691990901

**Comment by acxz** [comment]
@bilde2910, I'm going to go ahead and close this issue.

If you can still reproduce this error when building from clean chroot, please feel free to continue posting on this thread
or if you make an upstream issue and link it back here.
