### ISSUE TITLE
[rocm-dev] Cyclic dependency

### ISSUE THREAD

**Issue by tpkessler** [rocm-arch/rocm-arch#49]
`rocprofiler` needs the meta package `rocm` which itself depends on `rocm-dev`, which among other, lists `rocprofiler` as a dependency. Is the `rocm-dev` package really needed?

**Comment by acxz** [comment]
Ah that totally went over my head. I think the easy way to handle this is to move rocprofiler out of rocm-dev's dep list. The better way is to bigger out exact packages rocprofiler needs. We would like to stick to upstream as close as possible and rocm-dev depends on rocprofiler as shown here: https://github.com/RadeonOpenCompute/ROCm#rocm-binary-package-structure
But rocprofiler depends on `rocm`: https://github.com/ROCm-Developer-Tools/rocprofiler/#to-build-with-the-current-installed-rocm

I think making an upstream issue of this is necessary, or at least asking them to clarify their instructions. Do you mind making an upstream issue about this? I'll move rocprofiler out of the rocm-dev dep in the meanwhile.

**Comment by tpkessler** [comment]
Thanks for your explanation. I see what causes the problems. I opened an issue:
https://github.com/ROCm-Developer-Tools/rocprofiler/issues/18

**Comment by tpkessler** [comment]
I created a PR to remove rocprofiler from the dependencies.

**Comment by acxz** [comment]
Also just dropping this here, can't build or reproduce (I know the cyclic dep is still an issue) due to the following issue: https://aur.archlinux.org/packages/rocm-clang-ocl/#comment-733764

**Comment by acxz** [comment]
Keeping this issue open until upstream resolves it.

**Comment by acxz** [comment]
Requesting @neeshy to sync to AUR.

**Comment by acxz** [comment]
just synced

**Comment by tpkessler** [comment]
rocprofiler seems to only depend on rocr-runtime, see pr #61

**Comment by acxz** [comment]
Should an upstream PR be made to their readme to point to rocr-runtime instead of ROCm?

**Comment by tpkessler** [comment]
That's a good idea. Let's see if they will response to my issue.
