### ISSUE TITLE
[hcc] devendor 

### ISSUE THREAD

**Issue by acxz** [rocm-arch/rocm-arch#5]
Need to package and devendor hcc's submodules: 
- [ ] [rocm-llvm](https://github.com/RadeonOpenCompute/llvm-project/tree/6a70953f87a209f37ea7884abdbb6bcb2d6db732)
- [ ] [rocdl](https://github.com/RadeonOpenCompute/ROCm-Device-Libs)

**Comment by neeshy** [comment]
Upon further investigation, it seems that roc-llvm has two release types: roc-hcc and roc-ocl. roc-hcc is specifically targeted towards being a submodule of hcc, while roc-ocl is general and already packaged in llvm-roc. I think we should stick to pulling in those submodules as opposed to trying to build against system libraries.
