### ISSUE TITLE
Handling Dual Release Streams

### ISSUE THREAD

**Issue by acxz** [rocm-arch/rocm-arch#54]
So I am sure some of you may have noticed that in some of the AMD repos for releasing rocm related packages, there are two release streams. One is usually tagged as roc-x.y.z while the other is just a.b.c.
Because of this it may be confusing what the version number should be for what we package. To combat this I think we should have two packages for each release stream. I believe for releases that are targeted for the rocm metapackage, those packages be prefixed with `rocm-<package_name>` and the "og" releases of the repo be created as a separate package as just `<package_name>`. This may involving creating new packages and moving some PKGBUILDs around. What do you guys think?

**Comment by neeshy** [comment]
That would roughly double the amount of packages we have to maintain. I think that presents too much of a maintainability burden.
Instead, why don't we look at which versions AMD are using for their radeon debian repo: http://repo.radeon.com/rocm/apt/debian/pool/main/

**Comment by acxz** [comment]
That's true and I'm not saying we should create them all, just that we keep the naming conventions appropriate.

**Comment by acxz** [comment]
Closing this issue as resolved with neeshy's comment.
