### ISSUE TITLE
[rocm-cmake, rocm-gdb] sha256sum validity check fail

### ISSUE THREAD

**Issue by QMechanic** [rocm-arch/rocm-arch#553]
Just tried to install the new 4.0.0 version and it fails at the validation check.
I checked what the sha256sums were of my previous package, the newly downloaded and compared to the PKGBUILD file.

So I saw that the `PKGBUILD` file still has the hash from `rocm-cmake-3.10.0.tar.gz` which is `751be4484efdcf0d5fa675480db6e2cddab897de4708c7c7b9fa7adb430b52d7`
But when I verify the hash myself of the file `rocm-cmake-4.0.0.tar.gz` I get `4577487acaa6e041a1316145867584f31caaf0d4aa2dd8fd7f82f81c269cada6`

I have downloaded it by hand a few times from https://github.com/RadeonOpenCompute/rocm-cmake/archive/rocm-4.0.0.tar.gz
just to make sure there wasn't just some random cosmic ray/bit flip (has actually happened before) but I still get the new hash and if I download 3.10.0, that gives the same old hash as is found in PKGBUILD.

Edit:
After manually editing the PKGBUILD and installing it offline I also ran into rocm-gdb not passing the check so added that to the title and also fixed a spelling mistake.

**Comment by acxz** [comment]
thx for reporting, feel free to make PRs!
