### ISSUE TITLE
[rocm-libs] miopen dependency

### ISSUE THREAD

**Issue by JP-Ellis** [rocm-arch/rocm-arch#557]
I noticed that `rocm-libs` depends on `miopen-hip` explicitly, instead of `miopen` which is provided by both `miopen-hip` and `miopen-opencl`.  Is there a reason for this?  Or would it be worth making the dependency `miopen` and let the user decide on which backend to use?

**Comment by acxz** [comment]
The official `rocm-libs` deb package lists `miopen-hip` as a dep.
From: http://repo.radeon.com/rocm/apt/4.0/pool/main/r/rocm-libs/
```
Architecture: amd64
Depends: hipblas, hipcub, hipsparse, miopen-hip, rocalution, rocblas, rocfft, rocprim, rocrand, rocsolver, rocsparse, rocthrust
Description: Radeon Open Compute (ROCm) Runtime software stack
Homepage: https://github.com/RadeonOpenCompute/ROCm
Maintainer: Advanced Micro Devices, Inc.
Package: rocm-libs
Priority: optional
Section: devel
Version: 4.0.0.40000-23
Installed-Size: 13
```
