### ISSUE TITLE
Line up build flags with upstream

### ISSUE THREAD

**Issue by darjankrijan** [rocm-arch/rocm-arch#562]
Given the [hardware requirements](https://github.com/RadeonOpenCompute/ROCm#Hardware-and-Software-Support) for ROCm currently being essentially **AMD Zen and newer** or **Intel Haswell and newer**, it would be wise to set appropriate ```-march``` and ```-O``` flags to enable CPU features like e.g. F16C for handling FP16 floats with proper instructions instead of high overhead workarounds in software.

I opened an issue to get some info on this matter upstream: https://github.com/RadeonOpenCompute/ROCm/issues/1348

The default ```-march=x86-64``` in ```/etc/makepkg.conf``` enables a very basic set of instructions (up to SSE2) for the first x86-64 CPUs. In this case I'd propose replacing the ```x86-64``` ```march``` value in ```CFLAGS``` and ```CXXFLAGS``` in the PKGBUILDs to something in line with the hardware requirements.

Let's for now wait for an answer from upstream for proper and safe to use flags.

**Comment by darjankrijan** [comment]
Issue https://github.com/RadeonOpenCompute/ROCm/issues/1348 was rudely closed, I guess AMD doesn't want to disclose the flags they use for the repository builds.

I will check if some of the packages leave behind the flags they were build with, otherwise I will reverse engineer this by trying out a couple march flags with different optimization levels and compare with objdump.

**Comment by darjankrijan** [comment]
I finally took a deeper look into the libs.

I objdumped the libs deployed from the AMD repos, ROCm 4.1.0 on CentOS 8.3:

- The only libs with instructions that use YMM registers (AVX) are **libhipblas** and **librocblas**.
- The only lib with F16C instructions is **librocblas**.

[detect_rocm_instructions.sh](https://github.com/rocm-arch/rocm-arch/files/6411435/detect_rocm_instructions.sh.txt)
[rocm_4.1.0_xmm_ymm_f16c_ins.csv](https://github.com/rocm-arch/rocm-arch/files/6411436/rocm_4.1.0_xmm_ymm_f16c_ins.csv)

This is baffling.
I bet there are lots of scenarios where the conversion of huge datasets between CPU <-> GPU is bottlenecked due to missing instructions above.

I will do a rebuild on arch with
```
CFLAGS="-march=haswell -mtune=haswell -O3 -pipe -fno-plt"
CXXFLAGS="-march=haswell -mtune=haswell -O3 -pipe -fno-plt"
```
set in ```/etc/makepkg.conf``` and will provide the output of the ```detect_rocm_instructions.sh``` script.

**Comment by darjankrijan** [comment]
I was finally able to compile the stack and compare rocm 4.2.0, tried on and off with weird C++ errors each time.

[rocm_4.2.0_centos8_xmm_ymm_f16c_ins.csv](https://github.com/rocm-arch/rocm-arch/files/6623996/rocm_4.2.0_centos8_xmm_ymm_f16c_ins.csv)
[rocm-arch_4.2.0_xmm_ymm_f16c_ins.csv](https://github.com/rocm-arch/rocm-arch/files/6623995/rocm-arch_4.2.0_xmm_ymm_f16c_ins.csv)

This shows they are not even using any AVX flags for the majority of libs even though the minimum hardware can do so.

During this, I noticed that miopen didn't include any F16C instruction even though including `half.hpp` from [half](http://half.sourceforge.net)
It pulls half as a dependency in version 1.12 that doesn't have F16C intrinsics (current version 2.1.0 has).
I did a build with a hot-swapped half.hpp with the patched 2.1.0 half (see here: https://github.com/acxz/pkgbuilds/issues/94) and voila, F16C instructions:
```
Library					XMM Register Instructions	YMM Register Instructions	F16C Instructions
/opt/rocm/miopen/lib/libMIOpen.so.1.0	48679				28280				102
```

I'll create a couple of upstream issues, this is nothing rocm-arch needs to add in my opinion.
Also poking Christian Rau again to finally release an update for half.

**Comment by tpkessler** [comment]
Thanks for your analysis @darjankrijan! 
> This shows they are not even using any AVX flags for the majority of libs even though the minimum hardware can do so.

That's weird, given that they set `CMAKE_BUILD_TYPE` to `Release` by default for most packages, which implies `-O3`, but apparently don't care for `-march`.

**Comment by acxz** [comment]
> this is nothing rocm-arch needs to add in my opinion.

I'll go ahead and close the issue then.

@darjankrijan feel free to send PRs / make issues our way wrt what you think proper build flags for certain packages should be.
Ideally the flags should be incorporated upstream as you mentioned and the PKGBUILDs should add as little as possible.
