### ISSUE TITLE
rocfft install warning

### ISSUE THREAD

**Issue by mr-suroot** [rocm-arch/rocm-arch#570]
Warning: The specified HIP target: gfx902 is unknown. Correct compilation is not guaranteed.
iGpu: vega 6 (ryzen 5 4500u)

**Comment by tpkessler** [comment]
This is because the APU Vegas are not officially supported by ROCm, see https://github.com/RadeonOpenCompute/ROCm#supported-gpus

**Comment by mr-suroot** [comment]
Thank you for your response
