### ISSUE TITLE
[hip-rocclr] compilation error

### ISSUE THREAD

**Issue by Stefan2409** [rocm-arch/rocm-arch#571]
I'm getting the following error by compiling on arch linux with kernel 5.10.7:
struct device::Info does not have pciDomainID.

Here's the console info:

Scanning dependencies of target hip64
make[2]: Verzeichnis „/home/stefan/.cache/yay/hip-rocclr/src/build“ wird verlassen
make[2]: Verzeichnis „/home/stefan/.cache/yay/hip-rocclr/src/build“ wird betreten
[  0%] Building CXX object rocclr/CMakeFiles/hip64.dir/hip_context.cpp.o
In Datei, eingebunden von /home/stefan/.cache/yay/hip-rocclr/src/HIP-rocm-4.0.0/rocclr/hip_internal.hpp:25,
                 von /home/stefan/.cache/yay/hip-rocclr/src/HIP-rocm-4.0.0/rocclr/hip_context.cpp:22:
/home/stefan/.cache/yay/hip-rocclr/src/HIP-rocm-4.0.0/rocclr/hip_prof_api.h: In Konstruktor »api_callbacks_table_t::api_callbacks_table_t()«:
/home/stefan/.cache/yay/hip-rocclr/src/HIP-rocm-4.0.0/rocclr/hip_prof_api.h:72:59: Warnung: »void* memset(void*, int, size_t)« Säubern eines Objekts des Typs »struct api_callbacks_table_t::hip_cb_table_t« ohne triviale Kopierzuweisung; use value-initialization instead [-Wclass-memaccess]
   72 |      memset(&callbacks_table_, 0, sizeof(callbacks_table_));
      |                                                           ^
/home/stefan/.cache/yay/hip-rocclr/src/HIP-rocm-4.0.0/rocclr/hip_prof_api.h:67:10: Anmerkung: »struct api_callbacks_table_t::hip_cb_table_t« wird hier deklariert
   67 |   struct hip_cb_table_t {
      |          ^~~~~~~~~~~~~~
[ 25%] Building CXX object rocclr/CMakeFiles/hip64.dir/hip_code_object.cpp.o
In Datei, eingebunden von /home/stefan/.cache/yay/hip-rocclr/src/HIP-rocm-4.0.0/rocclr/hip_internal.hpp:25,
                 von /home/stefan/.cache/yay/hip-rocclr/src/HIP-rocm-4.0.0/rocclr/hip_global.hpp:9,
                 von /home/stefan/.cache/yay/hip-rocclr/src/HIP-rocm-4.0.0/rocclr/hip_code_object.hpp:4,
                 von /home/stefan/.cache/yay/hip-rocclr/src/HIP-rocm-4.0.0/rocclr/hip_code_object.cpp:1:
/home/stefan/.cache/yay/hip-rocclr/src/HIP-rocm-4.0.0/rocclr/hip_prof_api.h: In Konstruktor »api_callbacks_table_t::api_callbacks_table_t()«:
/home/stefan/.cache/yay/hip-rocclr/src/HIP-rocm-4.0.0/rocclr/hip_prof_api.h:72:59: Warnung: »void* memset(void*, int, size_t)« Säubern eines Objekts des Typs »struct api_callbacks_table_t::hip_cb_table_t« ohne triviale Kopierzuweisung; use value-initialization instead [-Wclass-memaccess]
   72 |      memset(&callbacks_table_, 0, sizeof(callbacks_table_));
      |                                                           ^
/home/stefan/.cache/yay/hip-rocclr/src/HIP-rocm-4.0.0/rocclr/hip_prof_api.h:67:10: Anmerkung: »struct api_callbacks_table_t::hip_cb_table_t« wird hier deklariert
   67 |   struct hip_cb_table_t {
      |          ^~~~~~~~~~~~~~
[ 25%] Building CXX object rocclr/CMakeFiles/hip64.dir/hip_device.cpp.o
In Datei, eingebunden von /home/stefan/.cache/yay/hip-rocclr/src/HIP-rocm-4.0.0/rocclr/hip_internal.hpp:25,
                 von /home/stefan/.cache/yay/hip-rocclr/src/HIP-rocm-4.0.0/rocclr/hip_device.cpp:23:
/home/stefan/.cache/yay/hip-rocclr/src/HIP-rocm-4.0.0/rocclr/hip_prof_api.h: In Konstruktor »api_callbacks_table_t::api_callbacks_table_t()«:
/home/stefan/.cache/yay/hip-rocclr/src/HIP-rocm-4.0.0/rocclr/hip_prof_api.h:72:59: Warnung: »void* memset(void*, int, size_t)« Säubern eines Objekts des Typs »struct api_callbacks_table_t::hip_cb_table_t« ohne triviale Kopierzuweisung; use value-initialization instead [-Wclass-memaccess]
   72 |      memset(&callbacks_table_, 0, sizeof(callbacks_table_));
      |                                                           ^
/home/stefan/.cache/yay/hip-rocclr/src/HIP-rocm-4.0.0/rocclr/hip_prof_api.h:67:10: Anmerkung: »struct api_callbacks_table_t::hip_cb_table_t« wird hier deklariert
   67 |   struct hip_cb_table_t {
      |          ^~~~~~~~~~~~~~
/home/stefan/.cache/yay/hip-rocclr/src/HIP-rocm-4.0.0/rocclr/hip_device.cpp: In Funktion »hipError_t hipGetDeviceProperties(hipDeviceProp_t*, hipDevice_t)«:
/home/stefan/.cache/yay/hip-rocclr/src/HIP-rocm-4.0.0/rocclr/hip_device.cpp:196:34: Fehler: »const struct device::Info« hat kein Element namens »pciDomainID«
  196 |   deviceProps.pciDomainID = info.pciDomainID;
      |                                  ^~~~~~~~~~~
make[2]: *** [rocclr/CMakeFiles/hip64.dir/build.make:108: rocclr/CMakeFiles/hip64.dir/hip_device.cpp.o] Fehler 1
make[2]: Verzeichnis „/home/stefan/.cache/yay/hip-rocclr/src/build“ wird verlassen
make[1]: *** [CMakeFiles/Makefile2:9167: rocclr/CMakeFiles/hip64.dir/all] Fehler 2
make[1]: Verzeichnis „/home/stefan/.cache/yay/hip-rocclr/src/build“ wird verlassen
make: *** [Makefile:160: all] Fehler 2
make: Verzeichnis „/home/stefan/.cache/yay/hip-rocclr/src/build“ wird verlassen
==> FEHLER: Ein Fehler geschah in build().
    Breche ab...
error making: hip-rocclr

If you need more information I will try to help!

**Comment by tpkessler** [comment]
Hi @Stefan2409! I cannot reproduce your error in a clean chroot. We generally recommend to use the binary packages from [arch4edu](https://github.com/arch4edu/arch4edu/wiki/Add-arch4edu-to-your-Archlinux) unless and then simply do
```
pacman -S rocm-dev rocm-utils rocm-libs
```
Coming back to your build issue: Which compiler are you using?

**Comment by Stefan2409** [comment]
@tpkessler sorry for my late reply!
I've solved the issue with compiling the hip-rocclr. There have been some artifacts from the former version been left after the uninstall and so it won't work. You can close this issue! Thank you for your help!
