### ISSUE TITLE
[llvm-amdgpu] Build fails without tensorflow

### ISSUE THREAD

**Issue by lahwaacz** [rocm-arch/rocm-arch#575]
Since tensorflow is not in the `depends` or `makedepends` array, the package should build without it. But it gives an error:
```
CMake Error at CMakeLists.txt:861 (add_subdirectory):
  add_subdirectory given source
  "/usr/lib/python/site-packages/tensorflow/xla_aot_runtime_src" which is not
  an existing directory.
```

**Comment by tpkessler** [comment]
You're right. I reverted the previous changes and added a warning to the README of the repository.

**Comment by JP-Ellis** [comment]
Why was the tensorflow dependency fully removed, isntead of dynmically checking if tensorflow is present and adding it to the `optdepends`?

**Comment by lahwaacz** [comment]
It was not added correctly to the PKGBUILD in the first place. Also you can't have dynamic checking if you want to build in a clean chroot - which is the recommended practice.

**Comment by tpkessler** [comment]
Jakub already gave the perfect explanation. Adding tensorflow caused more problems than it solved. To avoid confusion in the future, I added a warning to the README:


>    WARNING It is strongly recommended to remove all ROCm components when updating to a new release. Otherwise, building the packages with yay may have unwanted side effects resulting in build errors. If it's a small release with only a few updated packages, consider building them in a clean chroot.
>
>One way to mitigate these issues is to use the binary versions of the packages provided by arch4edu.

This is in accordance with AMD's README on ROCm which recommends a fresh installation,

https://github.com/RadeonOpenCompute/ROCm#fresh-installation-of-amd-rocm-v401-recommended
