### ISSUE TITLE
[llvm-amdgpu] missing libclang_rt.asan-x86_64.a

### ISSUE THREAD

**Issue by lahwaacz** [rocm-arch/rocm-arch#576]
It seems that `llvm-amdgpu` does not include static libraries which may be needed for regular usage of the compiler. For example, using `-fsanitize=address` with `hipcc` (`hello_world.cpp` is just a dummy C++ source code):

```
$ hipcc hello_world.cpp -fsanitize=address
/usr/bin/ld: cannot find /opt/rocm/llvm/lib/clang/12.0.0/lib/linux/libclang_rt.asan-x86_64.a: No such file or directory
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
```
Same when calling `clang++` directly:
```
$ /opt/rocm/llvm/bin/clang++ hello_world.cpp -fsanitize=address
/usr/bin/ld: cannot find /opt/rocm/llvm/lib/clang/12.0.0/lib/linux/libclang_rt.asan-x86_64.a: No such file or directory
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
```

Why does it try to use this file instead of `/usr/lib/libasan.so` anyway?

**Comment by tpkessler** [comment]
That's because `makepkg` removes the static version of a shared library by default. Adding `options=(staticlibs)` resolves the issue. See the updated package.
