### ISSUE TITLE
[rocm-opencl-runtime] runtime.cpp:1103: void rocr::core::Runtime::BindVmFaultHandler(): Assertion `false && "Failed on creating VM fault signal"' failed.

### ISSUE THREAD

**Issue by tarunKoyalwar** [rocm-arch/rocm-arch#581]
core dumped while running clinfo and any other opencl using app.

`clinfo: /home/tarun/.cache/yay/hsa-rocr-git/src/hsa-rocr-git/src/core/runtime/runtime.cpp:1103: void rocr::core::Runtime::BindVmFaultHandler(): Assertion false && "Failed on creating VM fault signal"' failed.
`
same error for both hsa-rocr-git and hsa-rocr . i also tried compiling as well as using binaries from arch4edu .

`inxi -Fxxx`

`Graphics:`
Device-1: AMD Baffin [Radeon RX 460/560D / Pro 450/455/460/555/555X/560/560X] vendor: ASUSTeK driver: amdgpu  v: kernel bus ID: 01:00.0 chip ID: 1002:67ef class ID: 0380 
           
Device-2: Advanced Micro Devices [AMD/ATI] Picasso vendor: ASUSTeK driver: amdgpu v: kernel bus ID: 04:00.0 
           chip ID: 1002:15d8 class ID: 0300 
           
Device-3: IMC Networks USB2.0 HD UVC WebCam type: USB driver: uvcvideo bus ID: 1-4:4 chip ID: 13d3:56a2 
           class ID: 0e02 serial: 0x0001 
           Display: x11 server: X.org 1.20.10 compositor: kwin_x11 driver: loaded: amdgpu resolution: <missing: xdpyinfo> 
           OpenGL: renderer: AMD Radeon Vega 8 Graphics (RAVEN DRM 3.40.0 5.11.5-arch1-1 LLVM 11.1.0) v: 4.6 Mesa 20.3.4 
           direct render: Yes `

**Comment by tpkessler** [comment]
Hi, your GPU is not officially supported, see 

https://github.com/RadeonOpenCompute/ROCm#supported-gpus

ROCm thus may or may not work.
