### ISSUE TITLE
[rocfft] wrong results if one dimension in 3d FFT is 4096 or larger on Radeon VII

### ISSUE THREAD

**Issue by t1nux** [rocm-arch/rocm-arch#583]
### introduction
I recently converted from CUDA to ROCm and it has so far been a pretty smooth transition. Therefore, I want to thank ROCm and the Arch devs for working on this great open-source tool.

However, now I am experiencing an issue with 3d FFTs. It seems if one of the dimensions in the 3d FFT is 4096 or larger, the result is incorrect.

I order to demonstrate the issue, I wrote a dummy program illustrating it.

I apologize of posting this here (instead of upstream). Since Arch is not an *officially* supported ROCm platform, this typically results in bugs being dropped immediately. Therefore, I am asking if someone here can verify the bug.

### ROCm
I have the current ROCm AUR packages installed, ie.
```
ur/rocm-dbgapi 4.0.0-1 (+0 0.00) (Installed)
aur/rocm-smi-lib64 4.0.0-1 (+0 0.00) (Installed)
aur/hipsparse 4.0.0-1 (+0 0.00) (Installed)
aur/rocalution 4.0.0-2 (+0 0.00) (Installed)
aur/rocm-gdb 4.0.0-2 (+0 0.00) (Installed)
aur/rocprofiler 4.0.0-1 (+0 0.00) (Installed)
aur/rocsolver 4.0.0-1 (+0 0.00) (Installed)
aur/hipcub 4.0.0-1 (+1 0.00) (Installed)
aur/rocsparse 4.0.0-1 (+1 0.00) (Installed)
aur/hip-rocclr 4.0.0-2 (+1 0.00) (Installed)
aur/rocclr 4.0.0-1 (+1 0.00) (Installed)
aur/rccl 4.0.0-1 (+1 0.00) (Installed)
aur/rocm-libs 4.0.0-2 (+1 0.24) (Installed)
aur/rocthrust 4.0.0-1 (+1 0.00) (Installed)
aur/rocm-device-libs 4.0.0-1 (+1 0.00) (Installed)
aur/rocprim 4.0.0-1 (+1 0.00) (Installed)
aur/hipblas 4.0.0-1 (+2 0.00) (Installed)
aur/hsa-rocr 4.0.0-1 (+3 0.00) (Installed)
aur/tensorflow-opt-rocm 2.4.0-4 (+3 0.44) (Installed)
aur/python-tensorflow-opt-rocm 2.4.0-4 (+3 0.44) (Installed)
aur/rocrand 4.0.0-1 (+3 0.00) (Installed)
aur/rocm-cmake 4.0.0-2 (+4 0.01) (Installed)
aur/rocm-dev 4.0.0-2 (+4 0.01) (Out-of-date: 2021-03-22) (Installed)
aur/rocm-clang-ocl 4.0.0-1 (+5 0.00) (Installed)
aur/rocminfo 4.0.0-1 (+7 0.01) (Installed)
aur/rocm-smi 4.0.0-1 (+7 0.00) (Installed)
aur/rocfft 4.0.0-1 (+8 0.24) (Installed)
aur/rocblas 4.0.0-1 (+8 0.00) (Installed)
aur/rocm-utils 4.0.0-2 (+9 0.00) (Installed)
aur/hsakmt-roct 4.0.0-1 (+18 0.00) (Installed)
aur/rocm-opencl-runtime 4.0.0-1 (+32 0.38) (Installed)
```

### hardware
This issue was observed on a Radeon RX6900XT and a Radeon VII.

#### c-code
I use the following code for generating a 3d array of zeros, except in a 3d-square that takes 1/8 in each dimension. This is then copied to the GPU, FFTed, iFFTed, copied back to host, and finally stored in a binary file.

```c++
#include "hip/hip_runtime.h"
#include <thrust/complex.h>
#include <eigen3/Eigen/Core>
#include "hipfft.h"
#import <fstream>
#import <iostream>

hipfftHandle fftPlan;
hipfftResult rc;

Eigen::ArrayXcd z;
Eigen::ArrayXcd Z;
Eigen::ArrayXcd z_test;
thrust::complex<double> *z_d;

void fft(thrust::complex<double>* z_d) {
    rc = hipfftExecZ2Z(fftPlan,
                       reinterpret_cast<hipfftDoubleComplex *>(z_d),
                       reinterpret_cast<hipfftDoubleComplex *>(z_d),
                       HIPFFT_FORWARD);
    assert(rc == HIPFFT_SUCCESS);
    hipDeviceSynchronize();
}

void ifft(thrust::complex<double>* z_d) {
    rc = hipfftExecZ2Z(fftPlan,
                       reinterpret_cast<hipfftDoubleComplex *>(z_d),
                       reinterpret_cast<hipfftDoubleComplex *>(z_d),
                       HIPFFT_BACKWARD);
    assert(rc == HIPFFT_SUCCESS);
    hipDeviceSynchronize();
}

void export_data(Eigen::ArrayXcd z, std::string fn, int N) {
    std::ofstream fl;
    fl.open(fn, std::ios::out | std::ios::binary);
    for (int i=0; i < N; ++i) {
        double rp = z[i].real();
        double ip = z[i].imag();
        fl.write(reinterpret_cast<char*>(&rp), sizeof(double));
        fl.write(reinterpret_cast<char*>(&ip), sizeof(double));
    }
    fl.close();
}

int main() {
    int Nt = 1<<12;
    int Ny = 1<<7;
    int Nx = 1<<6;

    z = Eigen::ArrayXcd::Zero(Nt*Nx*Ny);
    Z = Eigen::ArrayXcd::Zero(Nt*Nx*Ny);
    z_test = Eigen::ArrayXcd::Zero(Nt*Nx*Ny);
    hipMalloc(reinterpret_cast<void **>(&z_d), sizeof(hipDoubleComplex)*Nt*Nx*Ny);
    hipDeviceSynchronize();

    rc = HIPFFT_SUCCESS;
    fftPlan = NULL;
    rc = hipfftCreate(&fftPlan);
    assert(rc == HIPFFT_SUCCESS);
    rc = hipfftPlan3d(&fftPlan, Nt, Ny, Nx, HIPFFT_Z2Z);
    assert(rc == HIPFFT_SUCCESS);
    hipDeviceSynchronize();

    // set some to 1
    int fac = 8;
    for (int tt=0; tt<Nt/fac; ++tt) {
        for (int yy=0; yy<Ny/fac; ++yy) {
            for (int xx=0; xx<Nx/fac; ++xx) {
                z[Ny*Nx*tt + Nx*yy + xx] = 1.;
            }
        }
    }

    hipMemcpy(z_d, z.data(), Nt*Ny*Nx*sizeof(hipDoubleComplex), hipMemcpyHostToDevice);
    hipDeviceSynchronize();
    export_data(z, "/tmp/z.bin", Nt*Ny*Nx);

    fft(z_d);
    hipDeviceSynchronize();
    hipMemcpy(Z.data(), z_d, Nt*Ny*Nx*sizeof(hipDoubleComplex), hipMemcpyDeviceToHost);
    hipDeviceSynchronize();
    export_data(Z, "/tmp/Z.bin", Nt*Ny*Nx);

    ifft(z_d);
    hipDeviceSynchronize();
    hipMemcpy(z_test.data(), z_d, Nt*Ny*Nx*sizeof(hipDoubleComplex), hipMemcpyDeviceToHost);
    hipDeviceSynchronize();
    export_data(z_test, "/tmp/z_test.bin", Nt*Ny*Nx);

    std::cout << Nt << std::endl;
    return 0;
}
```
#### compilation and execution
I compile this with `hipcc 3d_fft_roc.cpp -o 3d_fft_roc -I/opt/rocm/include -L/opt/rocm/lib -lrocfft` for different values of `Nt`. `Nt = 1<<11` works fine (see later), the issue starts with `Nt=1<<12`. I did not try values in between.

#### analysis of the data
As you can see, I am saving a binary file. I read this file using python/matplotlib, using the following code:
```python
%matplotlib widget
import matplotlib.pyplot as plt
import numpy as np
import numpy.fft as npf

def get_data(fn):
    data = np.fromfile(fn)
    return (data[::2] + 1j*data[1::2]).reshape(Nt, Ny, Nx)

Nt, Ny, Nx = 2**12, 2**7, 2**6

z = get_data('/tmp/z.bin')
z_test = get_data('/tmp/z_test.bin')
Z = get_data('/tmp/Z.bin')

fig, ((ax01, ax02, ax03), (ax1, ax2, ax3)) = plt.subplots(ncols=3, nrows=2)
ax01.imshow(abs(z[0]), aspect=Nx/Ny)
ax02.imshow(abs(z[:, 0]), aspect=Nx/Nt)
ax03.imshow(abs(z[:, :, 0]), aspect=Ny/Nt)
ax1.imshow(abs(npf.fftshift(Z[0])), aspect=Nx/Ny)
ax2.imshow(abs(npf.fftshift(Z[:, 0])), aspect=Nx/Nt)
ax3.imshow(abs(npf.fftshift(Z[:, :, 0])), aspect=Ny/Nt)
fig.tight_layout()
```
Of course, the `Nt` is changed according to the value that corresponds to the data that was written to the file `/tmp/z.bin`.

The scaling (aspect) in the graph is chosen to change with `Nt`, so that the images should look alike for all values of `Nt` (it should look like a squared sinc function, ie. (sin(x)/x)^2). 

#### reference
I also wrote something in python to show how it should look like, which is:
```python
fac = 8
zz = np.ones((Nt, Ny, Nx))
zz[Nt//fac:] = 0
zz[:, Ny//fac:] = 0
zz[:, :, Nx//fac:] = 0
ZZ = npf.fftn(zz)

fig, ((ax01, ax02, ax03), (ax1, ax2, ax3)) = plt.subplots(ncols=3, nrows=2)
ax01.imshow(abs(zz[0]), aspect=Nx/Ny)
ax02.imshow(abs(zz[:, 0]), aspect=Nx/Nt)
ax03.imshow(abs(zz[:, :, 0]), aspect=Ny/Nt)
ax1.imshow(abs(npf.fftshift(ZZ[0])), aspect=Nx/Ny)
ax2.imshow(abs(npf.fftshift(ZZ[:, 0])), aspect=Nx/Nt)
ax3.imshow(abs(npf.fftshift(ZZ[:, :, 0])), aspect=Ny/Nt)
fig.tight_layout()
```
#### the acutal issue
The data, ie. the 3d-FFT, looks fine for `Nt=2^11` and smaller numbers, just like how it looks in numpy, which is

![image](https://user-images.githubusercontent.com/4058407/112057080-1ecc7c80-8b59-11eb-8a05-4f6f90308858.png)

The upper row is the initial data, the lower the FFT (well, only slices of it, of course).

However, for `Nt=2^12` the *rocfft* version looks like this

![image](https://user-images.githubusercontent.com/4058407/112057258-576c5600-8b59-11eb-9f57-27fd13a7592b.png)

while the (hopefully correct) numpy version looks like

![image](https://user-images.githubusercontent.com/4058407/112057312-6b17bc80-8b59-11eb-949b-8f5b39dde08a.png)

### conclusion
3d FFTs do not seem to work for dimension sizes of 4096 or larger. This is true for any dimension. I did try this for all of them an the issue is present in all cases.

This got much longer than I expected, but I feel there could still be more info from my side. Still, I do not want to make this too much longer. So, if you need more info, please ask.

**Comment by tpkessler** [comment]
Hi @t1nux, thanks for reporting this. I'll try to reproduce this with my Vega 56.

> This issue was observed on a Radeon RX6900XT and a Radeon VII.

The 6900XT is not officially supported, so this may be a reason (albeit I doubt it). But it should definitely work on a Radeon VII. We've already seen some performance issues with a Radeon VII on this repo. But as long as AMD does not communicate the exact way they compile their packages on officially supported Linux distributions it's hard to figure out what's going wrong.

**Comment by tpkessler** [comment]
`rocfft` (and other relevant parts of the ROCm stack) has been updated to 4.1.0. Could you please run your tests again with the new version?

**Comment by t1nux** [comment]
Hello. I am sorry for the delay. I am/was facing a few issues that I did not manage to resolve yet.

- After updating packages with yay, there were errors running the above code, so I decided to start over with a complete reinstallation and I uninstalled everything before.
- I did not manage to get rocblas (or was it hipblas?) compiled, so I simply upgraded that and all other packages to 4.1 that I managed. All but hip-rocclr are now 4.1, I did not succeed to get hip-rocclr-4.1 installed.
- With, I think, all relevant packages updated to 4.1, I am now getting `HSA Error:  Incompatible kernel and userspace, Vega 20 [Radeon VII] disabled. Upgrade amdgpu.` when I compile the above code (or anything for that matter). I do not remember what I got on the system with the RX6900XT, but I can check that tonight.
- What I am also getting during the compilation is the following: `#warning The hipFFT version included in rocFFT is deprecated.  Please use hipFFT from the hipFFT package/repository instead.` It seems hipfft is just a wrapper for rocfft/cufft. The above message seems to suggest it should still work using hipfft from rocfft, but I am not sure, and because of the issues above, I cannot test at this moment. Another issue I see is that hipfft is not (currently) available in rocm-arch. In any case, once ROC works on my system again, I will try to convert the above code to rocfft, in order to rule out a potential issue in hipfft.

I am happy to help, if I can, but I am not an expert. I am not sure how to proceed on some of the issues mentioned above, and I do not feel that rushing into this by submitting a bug for each issue is the right way to go ;-). So, please, let me know how I can help.

**Comment by tpkessler** [comment]
> What I am also getting during the compilation is the following: #warning The hipFFT version included in rocFFT is deprecated. Please use hipFFT from the hipFFT package/repository instead.

Good catch! `hipfft` has been added as a new package with ROCm 4.1.0

> I did not manage to get rocblas (or was it hipblas?) compiled

Those packages haven't been updated to 4.1.0 yet. But they will be updated til tomorrow.

> With, I think, all relevant packages updated to 4.1, I am now getting HSA Error: Incompatible kernel and userspace, Vega 20 [Radeon VII] disabled. Upgrade amdgpu.

Could you please open an additional issue and provide more details?

> After updating packages with yay, there were errors running the above code, so I decided to start over with a complete reinstallation and I uninstalled everything before

Yes, that's also recommended by AMD, see the README in our repo.

**Comment by tpkessler** [comment]
`rocm-dev`, `rocm-utils` and `rocm-libs` have been updated to `4.1.0`.

**Comment by t1nux** [comment]
@tpkessler Thank you for the info. I also saw you added hipfft. Thanks! After removing everything, it was not problem to install everything in 4.1 using yay.

I'm compiling the above code with `hipcc 3d_fft_roc.cpp -o 3d_fft_roc -I/opt/rocm/hipfft/include -L/opt/rocm/lib -lhipfft` now which works without the warnings that I previously got. However, the execution of the binary gives me:
```
> ./3d_fft_roc
/home/tinux/.cache/yay/hip-rocclr/src/HIP-rocm-4.1.0/rocclr/hip_code_object.cpp:481: "hipErrorNoBinaryForGpu: Unable to find code object for all current devices!"
[1]    1847 abort (core dumped)  ./3d_fft_roc
```
I have no idea where that directory is coming from, in particular since the `src` directory does not exist anymore. I assume this originates from the build...

This was only tested on the RX6900XT. I do not have access to the Radeon VII until Monday morning. I will test and report back asap.

In the next new weeks I will hopefully receive a Radeon Pro VII, which I will also be able to test this with. I assume this should be a GPU that should be 100% supported.

**Comment by t1nux** [comment]
Hello. I installed all 4.1 packages also on the PC with the Radeon VII. During the compilation step I am getting this:
```
HSA Error:  Incompatible kernel and userspace, Vega 20 [Radeon VII] disabled. Upgrade amdgpu.
```
The same happens for execution plus a segmentation fault.

**Comment by tpkessler** [comment]
Do you use the `rocm-dkms` package? It's _not_ recommended (and very likely won't work) with a current kernel.

**Comment by tpkessler** [comment]
> `"hipErrorNoBinaryForGpu: Unable to find code object for all current devices!"`

As the 6900XT is not officially supported it's very likely that the ROCm stack misses some bitcode necessary for the computation.

**Comment by t1nux** [comment]
> Do you use the `rocm-dkms` package? It's _not_ recommended (and very likely won't work) with a current kernel.

No, I installed ROC using 
```
yay -S rocm-dev rocm-utils rocm-libs
```
and it did not install `rocm-dkms`.

**Comment by tpkessler** [comment]
Ok, which kernel do you use?

**Comment by t1nux** [comment]
> Ok, which kernel do you use?

`core/linux 5.11.10.arch1-1`

**Comment by tpkessler** [comment]
That's weird. With my Vega 56 everything runs without errors and the final results (hipfft compared to numpy) agree.

**Comment by t1nux** [comment]
> That's weird. With my Vega 56 everything runs without errors and the final results (hipfft compared to numpy) agree.

I'm truly happy this is working for you and you are getting the correct result! I guess this means there is no issue in the FFT. 

Still, I can live with the fact that the 6900 is not working, but the issue with the Radeon VII is a bit of a bummer. This GPU was meant for a test only, in order to run my big (FP64) simulations on a Radeon Pro VII, which I will receive soon. What do you suggest to do? I was planning to install Ubuntu on a USB drive and see if I run into similar issues. Maybe you have other ideas. 

In any case, thanks a lot for your help and time.

**Comment by tpkessler** [comment]
Instead of installing ubuntu you can also try ROCm in docker: https://github.com/RadeonOpenCompute/ROCm-docker

**Comment by tpkessler** [comment]
> Still, I can live with the fact that the 6900 is not working, but the issue with the Radeon VII is a bit of a bummer.

I totally understand it. We've had a couple of issues (mostly performance) related to the Radeon VII on this repository. Unfortunately, I don't have access to one so I cannot test it. I'll be very grateful if someone who's following this thread could test it on their hardware (not necessarily a Radeon VII). @oleid, could you please test it on your RX 580/480?

**Comment by t1nux** [comment]
> Instead of installing ubuntu you can also try ROCm in docker: https://github.com/RadeonOpenCompute/ROCm-docker

Thanks for the tip, I did this and I am getting
```
> docker run -it --device=/dev/kfd --device=/dev/dri --security-opt seccomp=unconfined --group-add video rocm/rocm-terminal
Error: Incompatible ROCm environment.
The Docker container requires the latest kernel driver to operate correctly.
Upgrade the ROCm kernel to v4.1 or newer, or use a container tagged for v4.0.1 or older.
For more information, see
https://rocmdocs.amd.com/en/latest/Current_Release_Notes/Current-Release-Notes.html#
```

I am for sure *not* using `rocm-dkms`
```
> yay -Ss rocm-dkms
aur/rocm-dkms 3.10.0-1 (+3 0.01)
    ROCm - Open Soruce Platform for HPC and Ultrascale GPU Computing
```
and I *do* run on a recent kernel
```
> uname -a
Linux fractal 5.11.10-arch1-1 #1 SMP PREEMPT Fri, 26 Mar 2021 00:11:29 +0000 x86_64 GNU/Linux
```

Still, it seems to be a kernel issue. I just tried to downgrade to the most recent 5.10 and 5.9 kernels but it did not change anything.

If I find the time, I will try the USB drive tonight.

**Comment by tpkessler** [comment]
Hey, I think I found the reason for your issue: https://github.com/RadeonOpenCompute/ROCm#driver-compatibility-issue-in-this-release

Maybe the changes in amdgpu are already merged in linux 5.12. You may try it with the recent release candidate of the linux kernel.

**Comment by t1nux** [comment]
> Hey, I think I found the reason for your issue: https://github.com/RadeonOpenCompute/ROCm#driver-compatibility-issue-in-this-release
> 
> Maybe the changes in amdgpu are already merged in linux 5.12. You may try it with the recent release candidate of the linux kernel.

This looks indeed promising. I tried 
`Linux fractal 5.12.0-rc5-1-mainline #1 SMP PREEMPT Mon, 29 Mar 2021 12:45:19 +0000 x86_64 GNU/Linux` but I am still getting the same issue.

I will keep trying new RCs once they become available.

**Comment by t1nux** [comment]
I have not forgotten this. I tried linux-mainline-rc6 and rc7 just now, but both do not work, unfortunately:

```HSA Error:  Incompatible kernel and userspace, Vega 20 [Radeon VII] disabled. Upgrade amdgpu.```

I also tried on one of the supported Ubuntu LTS (not docker, full installation) where I am getting the correct results.

I am therefore hopeful, that the switch to 4.1 will also solve this issue on Arch for my Radeon VII. Once the kernel allows to test this again, I will report back.

**Comment by t1nux** [comment]
Hello again. I also tried rc8 without success. This was not a real surprise though since the diff did not contain anything amdgpu related.

I feel/fear this has become an entirely different topic. The discussion concerning this current intermediate issue should probably be done in a separate bug report. Since the issue was mentioned upstream, I do not know how to approach this. I seems upstream is preventing this by using rocm-rock. Maybe this is a way to go.

**Comment by t1nux** [comment]
Unfortunately, `5.12.0-1-mainline` also does not work and I am still getting `HSA Error:  Incompatible kernel and userspace, Vega 20 [Radeon VII] disabled. Upgrade amdgpu.`

**Comment by tictooc** [comment]
I haven't gone back and tested the latest mainline kernel yet, but ROCM 4.1 + the amd-staging-drm-next kernel should get your Radeon VII up and running.  

There were some other issues with a memory leak and SDMA errors, but as of the latest amd-staging-drm-next commit (3b316a3e4b74e96ea34e1d4b4c9a4085be13e72b) I am able to successfully run OpenCl applications on a Radeon VII.  So far my testing has been limited to OpenCl, but since a Vega 56 sucessfully ran your test app, I would think you'll probably good.

There is a pkgbuild for the amd-staging-drm-next kernel on the AUR. [amd-staging-drm-next-git](https://aur.archlinux.org/packages/linux-amd-staging-drm-next-git/)

**Comment by tpkessler** [comment]
> Do you think it would it help to upgrade to 4.1.1

The 4.1.1 update did not introduce any code changes but rather changed one paragraph in the docu.

> ROCM 4.1 + the amd-staging-drm-next kernel should get your Radeon VII up and running.

Hey @tictooc thank you for pointing @t1nux to AMD's staging-drm-next kernel!

**Comment by t1nux** [comment]
@tictooc, @tpkessler Thank you both for your inputs. I will try this in the next few days, but for personal reasons, my flexibility has gone down significantly. I will let you know asap.

**Comment by t1nux** [comment]
AMD's staging-drm-next kernel indeed works with ROCm on the Radeon VII. Also, the FFT issue is resolved, I assume with ROCm >=4. 

Thank you all so much for you help (@tictooc, @tpkessler).
