### ISSUE TITLE
[rocm-opencl-runtime] Warning "Use of non-host signal in host signal wait API."

### ISSUE THREAD

**Issue by ivanmlerner** [rocm-arch/rocm-arch#585]
Looks like the program is making reference to srcdir, the warning thrown is the following:
`ERROR: Warning: (!g_use_interrupt_wait || isIPC()) && "Use of non-host signal in host signal wait API." in virtual hsa_signal_value_t rocr::core::BusyWaitSignal::WaitRelaxed(hsa_signal_condition_t, hsa_signal_value_t, uint64_t, hsa_wait_state_t), <<private AUR directory>>/hsa-rocr/src/ROCR-Runtime-rocm-4.1.0/src/core/runtime/default_signal.cpp:87`

**Comment by tpkessler** [comment]
As far as I see this a warning emitted by the runtime but doesn't affect the result of the computation. Can you please provide more information? For instance an example program that crashes because of the warning?

It would be great if you report this upstream.

**Comment by ivanmlerner** [comment]
Looks like you are correct, the computations are carried out. This warning fills the output so I didn't notice this at first.
Do you mean the warning should be reported upstream?

**Comment by tpkessler** [comment]
Could you please post a link to the upstream issue?

**Comment by ivanmlerner** [comment]
They were not able to reproduce this issue, I will try to gather more information to try and reproduce it successfully before reopening the issue upstream.

**Comment by tpkessler** [comment]
I found the origin of the warning message. It's the output of a debugging function. Building `hsa-rocr` with `-DNDEBUG` fixes the issue. Can you confirm this with the recent version `4.1.0-2`?

**Comment by ivanmlerner** [comment]
Confirmed, no longer seeing the warning.
