### ISSUE TITLE
[comgr] Can't import tensorflow after updating to comgr 4.1.0-1

### ISSUE THREAD

**Issue by Cuiyn** [rocm-arch/rocm-arch#587]
I'm using `Python 3.8.8` and `tensorflow-rocm 2.4.0`. After updating to `comgr 4.1.0-1` with `yay -Syu`, I found I could not import `tensorflow`. Here is the output:
```
Python 3.8.8 (default, Mar 24 2021, 08:23:39) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "/home/xxx/.local/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: libamd_comgr.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxx/.local/lib/python3.8/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/xxx/.local/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 39, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "/home/xxx/.local/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/xxx/.local/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: libamd_comgr.so.1: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

Then I used `downgrade` command to restore to old version `4.0.0-2`, and everything is normal now, although I am not sure why.

**Comment by tpkessler** [comment]
First, let me cite from our README:

> WARNING It is strongly recommended to remove all ROCm components when updating to a new release. Otherwise, building the packages with yay may have unwanted side effects resulting in build errors. If it's a small release with only a few updated packages, consider building them in a clean chroot.

In your particular case the problem is that `tenslorflow` was linked against `libamd_comgr.so.1` but with `4.1.0` the library version was bumped to `libamd_comgr.so.2.0`.

Before you start building `tensorflow` against the new ROCm stack please wait until Monday. I'm incrementally updating to `4.1.0`. This takes some time as I'm checking that every package builds in a clean chroot before submitting it to the AUR.

**Comment by Cuiyn** [comment]
I apologize for not noticing the README file. In fact, I'm so excited that I can' t wait to update and see ROCm working better on Arch. Now I get the reason for the problem, thanks for the explanation and effort on this great work!

**Comment by tpkessler** [comment]
No worries @Cuiyn. ROCm is a complicated stoftware stack and it's easy to break. 

Thanks for your kind words!
