### ISSUE TITLE
Invalid offload arch combinations: gfx900 and gfx900:xnack-

### ISSUE THREAD

**Issue by jamilbk** [rocm-arch/rocm-arch#589]
Hello,

Getting this clang-12 error when building rocrand 4.1.0-1 from AUR:

```shell
[ 60%] Linking CXX executable xorwow_precomputed_generator
[ 60%] Built target xorwow_precomputed_generator
[ 70%] Building CXX object library/CMakeFiles/rocrand.dir/src/rocrand.cpp.o
clang-12: error: Invalid offload arch combinations: gfx900 and gfx900:xnack- (For a specific processor, a feature should either exist in all offload archs, or not exist in any offload archs)
make[2]: *** [library/CMakeFiles/rocrand.dir/build.make:76: library/CMakeFiles/rocrand.dir/src/rocrand.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:226: library/CMakeFiles/rocrand.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
error making: rocrand
```

I manage packages with `yay`, if that matters.

I've tried Googling a bit, but not much out there. Maybe a Clang incompatibility or an edge case with my setup?

System:
Threadripper 1950x
Gigabyte Aorus Gaming 7 x399
Vega Frontier Edition Air-cooled
64 GB DDR4 3333 Mhz

**Comment by tpkessler** [comment]
Do you still have parts of ROCm 4.0.0 installed? Before updating to a new release it is strongly recommended to uninstall all ROCm-related component.

**Comment by bilde2910** [comment]
`rocrand` depends on `hip-rocclr` which is still on 4.0.0 in the AUR

**Comment by tpkessler** [comment]
Oops, I forgot to push my changes. The new version is on the AUR now.

**Comment by jamilbk** [comment]
@tpkessler All fixed! Thanks for your work.
