### ISSUE TITLE
[rocm-opencl-runtime] Freeze after clinfo

### ISSUE THREAD

**Issue by chgara** [rocm-arch/rocm-arch#591]
After installing all the packages I am unable to find /opt/rocm/opencl/bin/x86_64/clinfo as it says in the amd installation guide to check the output of this.
I don't know what it happens or if it matters in arch

**Comment by ArchangeGabriel** [comment]
I’m not sure about a rocm variant, but can’t you just use the [clinfo package](https://archlinux.org/packages/community/x86_64/clinfo/)?

**Comment by chgara** [comment]
> I’m not sure about a rocm variant, but can’t you just use the [clinfo package](https://archlinux.org/packages/community/x86_64/clinfo/)?

Sorry I was searching in the worng dir.
But when I use the package you said my computer gives many errors and it freezes so I need to restart my computer.

**Comment by tpkessler** [comment]
> I’m not sure about a rocm variant, but can’t you just use the clinfo package?

Yes, `clinfo` from the package with the same name is the recommended command. It looks for config files in `/etc/OpenCL/vendors/`, where `rocm-opencl-runtime` installs `amdocl64.icd` which points to `/opt/rocm/lib/libamdocl64.so`.

> my computer gives many errors and it freezes

Please provide more information on your system. What's the output of
```
lscpi | grep VGA
```
My guess is that you use ROCm in combination with an unsupported GPU (for instance the mobile Vega chips).

**Comment by chgara** [comment]
Definitely I am using a vega 8.
the output of `lscpi | grep VGA` is
`03:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Renoir (rev c3)`
There is no even way to make it work rocm and tensorflow rocm in this apu?
I have read this article but is for ubuntu users and not for arch [the article](https://bruhnspace.com/en/bruhnspace-rocm-for-amd-apus/)

**Comment by tpkessler** [comment]
> There is no even way to make it work rocm and tensorflow rocm in this apu?

Not from our side. AMD has to implement the missing bits of the ROCm stack for these GPUs.
