### ISSUE TITLE
AUR build fails

### ISSUE THREAD

**Issue by plasticbomb1986** [rocm-arch/rocm-arch#60]
Id wanna build an install this from AUR, but its fails on my syste, with this error: 

   Building OpenCL runtime...

-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ROCT: /opt/rocm/include  
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find ROCR (missing: FIND_ROCR_INCLUDES FIND_ROCR_LIBRARIES)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindROCR.cmake:11 (find_package_handle_standard_args)
  CMakeLists.txt:30 (find_package)

-- Configuring incomplete, errors occurred!
See also "/var/tmp/pamac-build-attiladeak/rocm-opencl-runtime/src/rocm-opencl-runtime/build/CMakeFiles/CMakeOutput.log".
==> ERROR: A failure occurred in build().
    Aborting... 

System: 

Manjaro Testing branch
Kernel 5.6rc6
AMD Ryzen 2700x
32GB RAM
2* VEGA64

**Comment by acxz** [comment]
Can you let us know which package?

**Comment by plasticbomb1986** [comment]
> Edit thx for the bug report, can you let us know which package?
> Also fair warning we do not officially support Manjaro. If we cannot reproduce the issue on our systems, then we will be able to help/fix the issue you are facing. We recommend you use ArchLinux if you want to use these packages.

Im planning to move over Arch, just havent yet done it.

Im tryin to build rocm-opencl-runtime, llvm-roc built, rocm-comgr built, but this one fails. What else can i provide you what might help to pin point the issue?

**Comment by acxz** [comment]
hmm, interesting I just tried clean building it with yay and got it to compile cleanly. Nice to know it works on your system, tho!

**Comment by plasticbomb1986** [comment]
> hmm, interesting I just tried clean building it with yay and got it to compile cleanly. Nice to know it works on your system, tho!

Probably some "fuckup" in my system, caused by my own tinkering. Two days ago had an another pack not working as it should had, than after some hammering it did went trough. Thats an another thing, why im considering the arch install. Im already know what i want on my system, as base, now its causing more problem where i started from with it. :D

Now what i have to figure out, why luxmark fails to launch with segmentation fault, and why claymore miner fails to build opencl kernel to run on gpu. (Not mining, but usually testing with it with -benchmark 1 option). Already took care the mesa opencl loader, so clinfo see what i want it to see...
