### ISSUE TITLE
[hip-rocclr] CMake Error

### ISSUE THREAD

**Issue by gogoprog** [rocm-arch/rocm-arch#605]
When building hip-rocclr from AUR, I get this:

```CMake Error at rocclr/CMakeLists.txt:71 (find_package):
  Could not find a package configuration file provided by "ROCclr" with any
  of the following names:

    ROCclrConfig.cmake
    rocclr-config.cmake

  Add the installation prefix of "ROCclr" to CMAKE_PREFIX_PATH or set
  "ROCclr_DIR" to a directory containing one of the above files.  If "ROCclr"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/home/gogoprog/.cache/yay/hip-rocclr/src/build/CMakeFiles/CMakeOutput.log".
==> ERROR: A failure occurred in build().
    Aborting...
error making: hip-rocclr
```

Any clue?

**Comment by tpkessler** [comment]
Hey Gauthier, do you have an older version of `rocclr` installed? ROCm does not support partial updates (see the README of this repo), i.e. before an update please uninstall and rebuild all ROCm dependencies.

Torsten

**Comment by gogoprog** [comment]
Hello, yes I had older version.

So I removed everything and trying to build but I encounter other issues.
```LLVM ERROR: Unknown specifier in datalayout string```
When building `rocm-device-libs`

**Comment by tpkessler** [comment]
What version of `llvm-amdgpu` are you using? I cannot reproduce your issue with `llvm-amdgpu-4.2.0`.

**Comment by gogoprog** [comment]
I forgot to update that one, so I'm retrying now.
It is quite hard to update all the required packages to a newer version,
is there a list or meta package available?

**Comment by tpkessler** [comment]
Yes, there are two meta packages: `rocm-dev` with everything needed for HIP development and `rocm-libs` with a couple of libraries for scientific computing (FFT, BLAS, LAPACK,...)

**Comment by gogoprog** [comment]
Thanks, it went better.
Now I still have on issue when building `rocclr` :
``` Could not find a configuration file for package "hsa-runtime64" that is
  compatible with requested version "1.3".

  The following configuration files were considered but not accepted:

    /opt/rocm/lib/cmake/hsa-runtime64/hsa-runtime64-config.cmake, version: 1.2.0
```

**Comment by gogoprog** [comment]
All right I found it by installing `hsa-rocr` which was not included in the meta package

**Comment by gogoprog** [comment]
So after that I can correctly build `hip-rocclr`, thank you for your help!

**Comment by VasanthManiVasi** [comment]
> All right I found it by installing `hsa-rocr` which was not included in the meta package

How did you install `hsa-rocr`? @gogoprog 


I get this error when installing it: 
```
clang-12: error: cannot find ROCm device library for gfx805. Provide its path via --rocm-path or --rocm-device-lib-path, or pass -nogpulib to build without ROCm device library.
```

To fix that, I tried to build [this](https://github.com/RadeonOpenCompute/ROCm-Device-Libs). 
Which fails with this error: 
```
clang-12: error: unknown argument: '-cl-no-stdinc'
make[2]: *** [oclc/CMakeFiles/oclc_wavefrontsize64_on.dir/build.make:85: oclc/wavefrontsize64_on.bc] Error 1
make[1]: *** [CMakeFiles/Makefile2:503: oclc/CMakeFiles/oclc_wavefrontsize64_on.dir/all] Er
```

**Comment by gogoprog** [comment]
@VasanthManiVasi Hello, I did not have any error while installing `hsa-rocr` .
I installed version 4.2.0-1. Is your gpu  supported by rocm ?

**Comment by VasanthManiVasi** [comment]
Did you build `hsa-rocr` from the AUR? @gogoprog
My GPU is RX 570 and it's supported.

**Comment by gogoprog** [comment]
> Did you build `hsa-rocr` from the AUR? @gogoprog
> My GPU is RX 570 and it's supported.

Yes: `aur/hsa-rocr 4.2.0-1 (+4 0.11) (Installed)`
