### ISSUE TITLE
[miopengemm] Correct to include /opt/rocm/include and /opt/rocm/lib, plus issue with gcc11 (missing limits)

### ISSUE THREAD

**Issue by grinness** [rocm-arch/rocm-arch#607]
Hi,

in order to get the package to compile correctly please add -DOPENCL_LIBRARIES=/opt/rocm/lib \ -DOPENCL_INCLUDE_DIRS=/opt/rocm/include

to cmake build, otherwise the system /usr/include/CL include path is used and the rocm libs may not get picked up:

https://github.com/ROCmSoftwarePlatform/MIOpenGEMM/issues/47

Further see the issue with missing #include<limits> that needs to be added to miopengemm/src/MIOpenGEMM-rocm-4.2.0/miopengemm/src/enums.cpp in order to compile with system gcc11:

https://github.com/ROCmSoftwarePlatform/MIOpenGEMM/pull/46

**Comment by lahwaacz** [comment]
The issue with using the correct OpenCL implementation is best solved by [building in a clean chroot](https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot). Actually, setting `-DOPENCL_LIBRARIES=/opt/rocm/lib -DOPENCL_INCLUDE_DIRS=/opt/rocm/include` does not work in a clean chroot.

**Comment by tpkessler** [comment]
Hey @grinness as @lahwaacz already explained the solution for this problem is building in a clean chroot as it is done by `arch4edu`. Regarding your second point: @lahwaacz has opened a PR fixing this issue. In general, I would greatly appreciate if you would not only raise the issue but also create a PR to fix it. We can then jointly work on it and improve it until it's ready to be merged.

**Comment by grinness** [comment]
Why would be building in a chroot be the solution?
Are AUR packages normally built in a chroot?

Any AUR user that installs the package will have problems.
And there is nowhere written in the PKGBUILD or the doc that package _must_ be built in chroot
(chroot is mandatory if you re-build a new version and you do not uninstall the old one)

You are making more difficult to other users to adopt the rocm stack in this way
