### ISSUE TITLE
[rocblas] Endless Looping Bug

### ISSUE THREAD

**Issue by ram19890** [rocm-arch/rocm-arch#611]
Could not install this package as the loop does not end.
[https://pastebin.com/xJrM879X](url)

All the yaml files are listed here, it keeps repeating after reaching 100% & the loop starts again!
https://pastebin.com/3ncqXe1n](url)

**LOOP STARTS HERE!!!**
Reading logic files: Launching 2 threads...
Reading logic files: Done.
[|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||] 100% (677.3 secs elapsed)
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ram/.cache/yay/rocblas/src/build
make: Entering directory '/home/ram/.cache/yay/rocblas/src/build'
make[1]: Entering directory '/home/ram/.cache/yay/rocblas/src/build'
make[2]: Entering directory '/home/ram/.cache/yay/rocblas/src/build'
make[2]: Leaving directory '/home/ram/.cache/yay/rocblas/src/build'
make[2]: Entering directory '/home/ram/.cache/yay/rocblas/src/build'
[  1%] Generating Tensile Libraries

################################################################################
# Tensile Create Library
Tensile::WARNING: Did not detect SupportedISA: [(8, 0, 3), (9, 0, 0), (9, 0, 6), (9, 0, 8), (10, 1, 0), (10, 1, 1)]; cannot benchmark assembly kernels.

Kindly suggest where I went wrong, I could have missed something!

**Comment by tpkessler** [comment]
I cannot reproduce that build error. Could you please provide more information, in particular the version of `llvm-amdgpu`? Did you start with a clean installation, i.e. were there old ROCm packages installed when you did `yay -S rocblas`?

**Comment by ram19890** [comment]
False alarm, the compilation took longer to complete with "the same sets of texts repeating again and again", I mistakenly thought it was looping, but it was working and finally got installed. Sorry and Thanks anyway, closing now!
