### ISSUE TITLE
[llvm-amdgpu] Patch fails validity check

### ISSUE THREAD

**Issue by kozross** [rocm-arch/rocm-arch#612]
Whenever I try to build `llvm-amdgpu-4.2.0-3`, this happens:

```
==> Validating source files with sha256sums...
    llvm-amdgpu-4.2.0.tar.gz ... Passed
    libstdc++-11.1.0-workaround.patch ... FAILED
==> ERROR: One or more files did not pass the validity check!
```

**Comment by tpkessler** [comment]
Hey, I cannot reproduce that. Could you please delete the patch file? Its checksum changed between `pkgrel` 2 and 3. What does
```
curl https://github.com/ROCm-Developer-Tools/llvm-project/commit/9a75c06cd9d94d3fd13c47a01044da97b98cf26b.patch | sha256sum
```
print in your case?

**Comment by QMechanic** [comment]
The reason is probably that there already exists a file `libstdc++-11.1.0-workaround.patch`. For me there was one already and it had a sha256sum of `c874456a8a616735bf524772f7ca229d8e59d9775b2b5f19d734df1afda57d11`. If you delete it then the new and correct file will be downloaded and it should pass the validity check.

**Comment by kozross** [comment]
I get `241d737fe09822b784c37da3cfc38362d8599e4e6e49273fca990e58f4983341  -`.

**Comment by Tzigamm** [comment]
Got the same problem here, I also get the same `241d737fe09822b784c37da3cfc38362d8599e4e6e49273fca990e58f4983341` hash

**Comment by tpkessler** [comment]
@kozross @Tzigamm : Could you please remove `libstdc++-11.1.0-workaround.patch` and then try to build `llvm-amdgpu` again?

**Comment by Tzigamm** [comment]
Remove as in just delete the file from the PKGBUILD ?

**Comment by tpkessler** [comment]
Just remove the patch file from the directory:
```
rm libstdc++-11.1.0-workaround.patch
```
and then call `makepkg`. This downloads the new version of patch file.

**Comment by kozross** [comment]
@tpkessler Yep, that fixed it for me. Thanks!

**Comment by Tzigamm** [comment]
Same here, thanks!
