### ISSUE TITLE
[rocm-llvm] Tame parallelism during build ?

### ISSUE THREAD

**Issue by marco44** [rocm-arch/rocm-arch#613]
Building llvm-amdgpu can be very brutal on certain machines, because of ninja, which decides to use n cpu threads + 2 for its compile. As I'm using a 3900x it means 26 compiles in parallel which is quite a bit too much (I sometimes start swapping, and anyway, I'd like to be able to reduce this to use my machine without too much degradation while compiling).

With packages using make, just using the MAKEFLAGS does the trick, but it seems ninja doesn't have anything like this available (I don't know it that much so I may be mistaken).

I'd like to propose this patch to the PKGBUILD, to retrieve the -j from MAKEFLAGS if it is set. Maybe there's something smarter ?
```
diff --git a/PKGBUILD b/PKGBUILD
index 1b8818a..4f6d6c8 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -25,6 +25,13 @@ prepare() {
 }
 
 build() {
+    # Extract -j from MAKEFLAGS if set
+    NINJAOPTS=""
+    regex="(-j *[0-9]+)" # -j with any number of spaces and then at least one number
+    if [[ $MAKEFLAGS =~ $regex ]]
+    then
+        NINJAOPTS="${BASH_REMATCH[1]}"
+    fi
     cmake -GNinja \
         -Wno-dev \
         -S "$_dirname/llvm" \
@@ -37,7 +44,7 @@ build() {
         -DLLVM_ENABLE_PROJECTS='llvm;clang;compiler-rt;lld' \
         -DLLVM_TARGETS_TO_BUILD='AMDGPU;X86' \
         -DOCAMLFIND=NO
-    ninja
+    ninja $NINJAOPTS
 }
 
 package() {
 ```

**Comment by tpkessler** [comment]
Hey @marco44!
> it means 26 compiles in parallel which is quite a bit too much

I also experience this with my Ryzen 2700x but I'm not convinced that your proposed patch will fix this issue since
> just using the MAKEFLAGS does the trick

and in my case, and I believe for many more, `MAKEFLAGS` at least equals the number of available threads. This does not cause any issue with the ROCm stack (and other packages) with `llvm-amdgpu` being the rare exception. So I would have to change `MAKEFLAGS` in advance in `makepkg.conf` and change it back to its previous value afterwards.
Wouldn't it then be better to ad hoc change the line of the ninja call in the build script?

**Comment by marco44** [comment]
Hi, what would you put as ad-hoc value ? It means having to edit this build script (maybe each time depending on your build workflow) instead of editing the makepkg.conf, which only displaces the problem.


As the MAKEFLAGS option is there and used by many of us to set a default parallel level, it seems logical to me to propagate it to ninja if the user has set a -j flag in its flags, as it means the user wants this level of parallelism by default.

For instance, I set it to the amount of cores + 2, not threads + 2, which means I'm not that slower to compile than what I'd get with all threads, but the machine stays much more responsive, as I still have free threads and use almost half the ram for compilation.

**Comment by tpkessler** [comment]
> what would you put as ad-hoc value ?

I meant you could replace the simple `ninja` command inside the build function by
```
ninja -j14
```

> editing the makepkg.conf, which only displaces the problem

Yes, and my point is that in many cases the number of threads in `MAKEFLAGS` in `makepkg` is set to the number of threads not the number of cores.

> it seems logical to me to propagate it to ninja if the user has set a -j flag in its flags

I don't doubt that this is a reasonable request. What we are doing in the moment is what is done in the `PKGBUILD` for the Arch [`llvm` package](https://github.com/archlinux/svntogit-packages/blob/packages/llvm/trunk/PKGBUILD).
Do you know of any (AUR) package that implements a related logic to what you are proposing?

**Comment by marco44** [comment]
> Yes, and my point is that in many cases the number of threads in `MAKEFLAGS` in `makepkg` is set to the number of threads not the number of cores.
Well, it's set to empty by default, which means only one thread. Which has the advantage of not killing the machine. And then it's set to whatever the user sees fit, which totally depends on the hardware.

> 
> > it seems logical to me to propagate it to ninja if the user has set a -j flag in its flags
> 
> I don't doubt that this is a reasonable request. What we are doing in the moment is what is done in the `PKGBUILD` for the Arch [`llvm` package](https://github.com/archlinux/svntogit-packages/blob/packages/llvm/trunk/PKGBUILD?rgh-link-date=2021-06-13T16%3A51%3A00Z).
> Do you know of any (AUR) package that implements a related logic to what you are proposing?

No, I don't. It's the first package I meet that has a lot to compile and depends on ninja though, so it's the first time I face this problem with an AUR package.

**Comment by marco44** [comment]
Ok, seems you don't like this idea ? How about simply being able to add an environment variable, like NINJAOPTS or whatever to the environment, like we do for MAKEFLAGS ? Editing the configuration each time just to avoid having my PC being overrun by ninja seems a bit too error-prone for me.

**Comment by marco44** [comment]
BTW there have been discussions in the forum like https://bbs.archlinux.org/viewtopic.php?id=246007, it's not the only place where ninja tries to kill a machine :)

**Comment by John-Gee** [comment]
THE NINJAFLAGS from that thread makes sense since ninja has a different behavior from make.

**Comment by marco44** [comment]
yeah, but ninjaflags isn't really more standard, as ninja doesn't take an environment variable…

**Comment by John-Gee** [comment]
Right, but maybe all needed is a few applications using it and then the ninja team would support it (or offer something else of course).

I hadn't seen samurai before, does it work better for this purpose?

**Comment by marco44** [comment]
Well, samurai takes an environment variable, and is a 1:1 replacement for ninja.

As far as ninja is concerned, they just seem to don't care or understand what this environment variable support would solve : https://github.com/ninja-build/ninja/issues/1482

**Comment by John-Gee** [comment]
Interesting link, thank you!

**Comment by acxz** [comment]
I am closing this issue by stating we will keep the build behavior for this package as close as possible to the official Arch LLVM package.

For users building the package on their own machine. Feel free to edit a locally downloaded PKGBUILD as they see fit.

**Comment by LW-archlinux** [comment]
The desribed method was implimented in aur llvm trunk packages and changed a bit due to user feedback.

I'll comment in the MR.

**Comment by tpkessler** [comment]
PR #696 added the possibility to adjust the number of threads for ninja, see the updated section in the README.

**Comment by acxz** [comment]
Gonna close this issue as the information is presented in the readme.
