### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by supermar1010** [rocm-arch/rocm-arch#615]
Hello,
I'm in the process of installing everything. I needed to manually install `hsa-amd-aqlprofile-bin` for it to build. Is that a dependecy that should be added to pkgbuild?

With best regards
Mario

**Comment by tpkessler** [comment]
`hsa-amd-aqlprofile-bin` provides `hsa-amd-aqlprofile` which is listed in the dependencies of `rocm-dev`.

**Comment by supermar1010** [comment]
Ok that's weird as I had to manually install it, because I got a dependency not satisfiable.
