### ISSUE TITLE
Best way to add packages to path

### ISSUE THREAD

**Issue by bernharl** [rocm-arch/rocm-arch#618]
I see that packages like rocm-smi-lib64 have their binaries stored in /opt/rocm/bin. Is it safe to add this directory to PATH, or is this not recommended (possibly due to conflicts with other applications)?

**Comment by tpkessler** [comment]
Hi @bernharl,  I have `/opt/rocm/bin` added to my path and never had problems.
`ls /opt/rocm/bin` with all ROCm packages installed on my system yields
```
clang-ocl        rocaddr2line  rocgdb               rocm-smi               rocobjdump  rocstrings
clinfo           rocar         rocgdb-add-index     rocm_agent_enumerator  rocprof     rocstrip
hipcc            rocc++filt    rocgprof             rocm_smi.py            rocranlib   rsmiBindings.py
hipconfig        rocelfedit    rocminfo             rocnm                  rocreadelf
migraphx-driver  rocgcore      rocm-bandwidth-test  rocobjcopy             rocsize
```
Apart from `clang-ocl` (which is provided by `rocm-clang-ocl`) all files have a `hip` or `roc` prefix, so there should be no conflicts with other applications.

**Comment by bernharl** [comment]
Hi, thanks for the response!

The only thing I see is clinfo, which is also provided by a different arch package. I guess I won't need that package with rocm installed, though. Adding it to path then, thank you.
