### ISSUE TITLE
Outdated packages for 4.3.1

### ISSUE THREAD

**Issue by bilde2910** [rocm-arch/rocm-arch#622]
Rather than flag each one, I figure it's easier to just report them all here and ask if there are any plans to update them in AUR :slightly_smiling_face: 

The following packages have a 4.3.1 tag with additional commits compared to 4.3.0:

- `rccl`
- `rocfft` (documentation changes only)

The following packages received a version bump upstream, but no commits were pushed in between:

- `hipblas`
- `hipcub`
- `hipfft`
- `hipsparse`
- `miopen-hip`
- `miopengemm`
- `rocalution`
- `rocrand`
- `rocsparse`
- `rocthrust`
- `rocprim`

These are all on 4.3.0 in AUR. If these are updated then probably the metapackages `rocm-{dev,libs,utils}` should be bumped too. There may be more packages as well that I did not check.

**Comment by tpkessler** [comment]
Hey Marius, thank you very much for your detailed analysis. I was very busy this week and only updated half of the packages.  I plan to update the remaining packages today.

**Comment by tpkessler** [comment]
I updated all packages to 4.3.1 in the AUR last week. Were you able to build them on your system?

**Comment by bilde2910** [comment]
Yup, it all works! Metapackage `rocm-dev` is still at 4.3.0 FYI, but everything does appear to work. Thanks for the updates!

**Comment by tpkessler** [comment]
> Metapackage rocm-dev is still at 4.3.0

Thanks for the hint. I updated `rocm-dev` in the github repo but forgot to push the changes to the AUR. This is fixed now.
