### ISSUE TITLE
Update `rock-dkms` and `rock-dkms-firmware`

### ISSUE THREAD

**Issue by vchuravy** [rocm-arch/rocm-arch#625]
Looks like `rocgdb` still requires an extended ioctl set that is not provided upstream yet.
I think `rock-dkms` is suspposed to have that? I tried updating myself, but the `rock-dkms`
package failed building during the dkms step after install on 5.14

**Comment by tpkessler** [comment]
Hey Valentin, do you have further references on the ioctl problem? The problem with `rock-dkms` is that it does not support kernel newer than 5.4, see https://github.com/RadeonOpenCompute/ROCm#rocm-support-in-upstream-linux-kernels
We previously tried to get it work on newer kernels but without success. That's why these packages haven't been updated for a long time.

**Comment by tarcey** [comment]
Hello @tpkessler, the newer versions of ROCk do support 5.10-LTS, and dropped support for 5.4-LTS.

The driver appears to be built on the 5.11 kernel now, judging from the [makefile](https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver/blob/c64862acad99afac4b5a5ccd92008584b7d9ea89/Makefile). I use the [4.3.1-59](https://repo.radeon.com/rocm/apt/4.3.1/pool/main/r/rock-dkms/) release of the ROCk driver and firmware on the 5.10.74 LTS kernel release without problems. The newer versions sadly do not build for 5.4 anymore, however.

This is the customized PKGBUILD i use for building ROCk-dkms and the firmware, based on the PKGBUILDs provided here. Feel free to use it however way you want (the checksums at the bottom are likely outdated):

```
pkgbase=rock-dkms
pkgname=(rock-dkms-bin rock-firmware-bin)
pkgver=4.3.1
pkgrel=59
pkgdesc="Linux AMD GPU kernel driver from ROC in DKMS format."
arch=('any')
url="https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver"
license=('GPL')
backup=('etc/modprobe.d/blacklist-radeon.conf')
options=('!strip' '!emptydirs')
source=("https://repo.radeon.com/rocm/apt/${pkgver}/pool/main/r/rock-dkms/rock-dkms_${pkgver:0:-2}-${pkgrel}_all.deb"
        "https://repo.radeon.com/rocm/apt/${pkgver}/pool/main/r/rock-dkms/rock-dkms-firmware_${pkgver:0:-2}-${pkgrel}_all.deb")

prepare() {
  cd "$srcdir"
  mkdir -p module
  mkdir -p firmware

  ar x "rock-dkms_${pkgver:0:-2}-${pkgrel}_all.deb" --output module
  ar x "rock-dkms-firmware_${pkgver:0:-2}-${pkgrel}_all.deb" --output firmware
}

package_rock-dkms-bin() {
  pkgdesc="Linux AMD GPU kernel driver from ROC in DKMS format."
  depends=('dkms' 'rock-firmware-bin')
  provides=('rock-dkms')
  conflicts=('rock-dkms')
  cd "$srcdir"/module

  tar xf data.tar.xz -C "$pkgdir"

  cd $pkgdir/usr/src/amdgpu-${pkgver:0:-2}-${pkgrel}

  install -Dm644 "$pkgdir/usr/share/doc/rock-dkms/copyright" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}

package_rock-firmware-bin() {
  pkgdesc="Linux AMD GPU firmware from ROC for the rock kernel module."
  conflicts=(rock-dkms-firmware-bin)
  provides=(rock-dkms-firmware-bin)
  cd "$srcdir"/firmware

  tar xf data.tar.xz -C "$pkgdir"
  install -Dm644 "$pkgdir/usr/share/doc/rock-dkms-firmware/copyright" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}

sha256sums=('59cedd640b3c8f80c6aeee3a6fb0b675e64faa3f82254d084d62f4284127d30d'
            'c656f4d0c047ace2b686b69b4eb9dff0f97f1c396ef6f00967f031776f9b50b5')
sha256sums=('59cedd640b3c8f80c6aeee3a6fb0b675e64faa3f82254d084d62f4284127d30d'
            'c656f4d0c047ace2b686b69b4eb9dff0f97f1c396ef6f00967f031776f9b50b5')
sha256sums=('37f5e293ed5b2723cdf2f6d79c758a73c7a937f5b8900db7aac125980511418c'
            'ae54248358b00ceced45c5cc59884c986db5be2b104df6fa2006eca4f910877d')
```

**Comment by acxz** [comment]
These packages are not being built by ROCm anymore for their debian stack. As such we will be removing them soon. Closing this issue in regards to this.
