### ISSUE TITLE
4.5.0 Release

### ISSUE THREAD

**Issue by itsagoodbrain** [rocm-arch/rocm-arch#626]
It seems that version 4.5.0 is being rolled out. Not all repositories are showing it though so I thought I'd start an issue to keep track of it. This relates to my issues at https://github.com/arch4edu/arch4edu/issues/138 as well because it would be good to keep these in sync given the documentation points there.

**Comment by justinkb** [comment]
4.5 is up on GitHub "officially" now

**Comment by normalisnormal** [comment]
I don't know if this is relevant but package structure is different on officially supported Ubuntu repos.

They seem to have [provided an installer and introduced some "usecase" switches](https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation_new.html#overview-of-rocm-installation-methods). They are basically [package groups](https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation_new.html#components-of-rocm-programming-models). Those packages are linked in a tree structure with the help of "meta-package" dependencies.

i.e. rocm-opencl-sdk (meta) depends on rocm-core + rocm-llvm + rocm-opencl-dev and rocm-opencl-runtime (meta). rocm-opencl-runtime (meta) depends on rocm-opencl and rocm-language-runtime (meta). rocm-opencl depends on comgr + hsa-rocr-dev and libelf etc.

Also, there is no mention of rock-dkms in the docs but [amdgpu-dkms](https://repo.radeon.com/amdgpu/latest/ubuntu/pool/main/a/amdgpu-dkms/) now

**Comment by tpkessler** [comment]
Hey @normalisnormal thank you for the links! I've included the new meta packages to the repo and deleted the old meta packages.

**Comment by tpkessler** [comment]
All packages have been updated to 4.5.0.
