### ISSUE TITLE
[hip-runtime-amd]  "Failed to embed PCH" error

### ISSUE THREAD

**Issue by FogLizard** [rocm-arch/rocm-arch#629]
When building hip-runtime-amd 4.5.0-1 from AUR, it fails with errors below in CMakeError.log. System has been fully upgraded and all dependencies are installed for this AUR package.

Without this package I can't build the remaining packages:
hipsparse                                          -> 4.5.0-1
 rocm-dev                                          -> 4.5.0-1
 rocprofiler                                         -> 4.5.0-1
 rocsparse                                          -> 4.5.0-1
 roctracer                                          -> 4.5.0-1

`Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: /home/pink/.cache/pikaur/build/hip-runtime-amd/src/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make -f Makefile cmTC_8eaea/fast && /usr/bin/make  -f CMakeFiles/cmTC_8eaea.dir/build.make CMakeFiles/cmTC_8eaea.dir/build
make[1]: Entering directory '/home/pink/.cache/pikaur/build/hip-runtime-amd/src/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_8eaea.dir/src.c.o
/usr/bin/cc -DCMAKE_HAVE_LIBC_PTHREAD  -D_FORTIFY_SOURCE=2 -march=native -O2 -pipe -fstack-protector-strong -fno-plt  -o CMakeFiles/cmTC_8eaea.dir/src.c.o -c /home/pink/.cache/pikaur/build/hip-runtime-amd/s
rc/build/CMakeFiles/CMakeTmp/src.c
Linking C executable cmTC_8eaea
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_8eaea.dir/link.txt --verbose=1
/usr/bin/cc -D_FORTIFY_SOURCE=2 -march=native -O2 -pipe -fstack-protector-strong -fno-plt  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now  CMakeFiles/cmTC_8eaea.dir/src.c.o -o cmTC_8eaea 
/usr/bin/ld: CMakeFiles/cmTC_8eaea.dir/src.c.o: in function `main':
src.c:(.text.startup+0x24): undefined reference to `pthread_create'
/usr/bin/ld: src.c:(.text.startup+0x2e): undefined reference to `pthread_detach'
/usr/bin/ld: src.c:(.text.startup+0x38): undefined reference to `pthread_cancel'
/usr/bin/ld: src.c:(.text.startup+0x44): undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_8eaea.dir/build.make:99: cmTC_8eaea] Error 1
make[1]: Leaving directory '/home/pink/.cache/pikaur/build/hip-runtime-amd/src/build/CMakeFiles/CMakeTmp'
make: *** [Makefile:127: cmTC_8eaea/fast] Error 2

Source file was:
#include <pthread.h>

static void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_cancel(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}
`

`'sh' '-c' '/home/pink/.cache/pikaur/build/hip-runtime-amd/src/HIP-rocm-4.5.0/bin/hip_embed_pch.sh /home/pink/.cache/pikaur/build/hip-runtime-amd/src/HIP-rocm-4.5.0/include /home/pink/.cache/pikaur/build/hip-runtime-amd/src/build/include /home/pink/.cache/pikaur/build/hip-runtime-amd/src/hipamd-rocm-4.5.0/include /usr/lib64/cmake/llvm/../../..'
+ /usr/lib64/cmake/llvm/../../../bin/clang -O3 --rocm-path=/home/pink/.cache/pikaur/build/hip-runtime-amd/src/build/include/.. -std=c++17 -nogpulib -isystem /home/pink/.cache/pikaur/build/hip-runtime-amd/src/build/include -isystem /home/pink/.cache/pikaur/build/hip-runtime-amd/src/HIP-rocm-4.5.0/include -isystem /home/pink/.cache/pikaur/build/hip-runtime-amd/src/hipamd-rocm-4.5.0/include --cuda-device-only -x hip /tmp/hip_pch.102716/hip_pch.h -E
+ cat /tmp/hip_pch.102716/hip_macros.h
+ /usr/lib64/cmake/llvm/../../../bin/clang -cc1 -O3 -emit-pch -triple amdgcn-amd-amdhsa -aux-triple x86_64-unknown-linux-gnu -fcuda-is-device -std=c++17 -fgnuc-version=4.2.1 -o /tmp/hip_pch.102716/hip.pch -x hip-cpp-output -
In file included from /tmp/hip_pch.102716/hip_pch.h:1:
In file included from /home/pink/.cache/pikaur/build/hip-runtime-amd/src/HIP-rocm-4.5.0/include/hip/hip_runtime.h:62:
In file included from /home/pink/.cache/pikaur/build/hip-runtime-amd/src/hipamd-rocm-4.5.0/include/hip/amd_detail/amd_hip_runtime.h:81:
/home/pink/.cache/pikaur/build/hip-runtime-amd/src/hipamd-rocm-4.5.0/include/hip/amd_detail/amd_hip_atomic.h:744:12: error: address argument to atomic operation must be a pointer to integer or pointer ('float *' invalid)
    return __atomic_fetch_add(address, val, 0);
           ^                  ~~~~~~~
/home/pink/.cache/pikaur/build/hip-runtime-amd/src/hipamd-rocm-4.5.0/include/hip/amd_detail/amd_hip_atomic.h:779:12: error: address argument to atomic operation must be a pointer to integer or pointer ('double *' invalid)
    return __atomic_fetch_add(address, val, 0);
           ^                  ~~~~~~~
2 errors generated when compiling for .
CMake Error at src/CMakeLists.txt:171 (message):
  Failed to embed PCH

-- Configuring incomplete, errors occurred!
See also "/home/pink/.cache/pikaur/build/hip-runtime-amd/src/build/CMakeFiles/CMakeOutput.log".
See also "/home/pink/.cache/pikaur/build/hip-runtime-amd/src/build/CMakeFiles/CMakeError.log".
==> ERROR: A failure occurred in build().
    Aborting...
`

**Comment by j-stephan** [comment]
I'm seeing a different error, although with the same final result:

```
==> Starting build()...
mkdir: cannot create directory 'build': File exists
-- The C compiler identification is GNU 11.1.0
-- The CXX compiler identification is GNU 11.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- HIP_COMMON_DIR found at /home/stepha27/.cache/pacaur/hip-runtime-amd/src/HIP-rocm-4.5.0
-- Found Perl: /usr/bin/perl (found version "5.34.0") 
-- Found Git: /usr/bin/git (found version "2.33.1") 
-- Using CPACK_DEBIAN_PACKAGE_RELEASE local
-- CPACK_RPM_PACKAGE_RELEASE: local
-- HIP Platform: amd
-- HIP Runtime: rocclr
-- HIP Compiler: clang
-- HIP will be installed in: /opt/rocm/hip
-- ROCM Installation path(ROCM_PATH): /opt/rocm
-- Found ROCclr: /home/stepha27/.cache/pacaur/hip-runtime-amd/src/ROCclr-rocm-4.5.0/include  
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Found AMD_OPENCL: /home/stepha27/.cache/pacaur/hip-runtime-amd/src/ROCm-OpenCL-Runtime-rocm-4.5.0/khronos/headers/opencl2.2/CL  
-- Found NUMA: /usr/lib/libnuma.so  
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.11") 
-- Found LibXml2: /usr/lib/libxml2.so (found version "2.9.12") 
'sh' '-c' '/home/stepha27/.cache/pacaur/hip-runtime-amd/src/HIP-rocm-4.5.0/bin/hip_embed_pch.sh /home/stepha27/.cache/pacaur/hip-runtime-amd/src/HIP-rocm-4.5.0/include /home/stepha27/.cache/pacaur/hip-runtime-amd/src/include /home/stepha27/.cache/pacaur/hip-runtime-amd/src/hipamd-rocm-4.5.0/include /home/stepha27/sycl-workspace/llvm/build/lib/cmake/llvm/../../..'
+ /home/stepha27/sycl-workspace/llvm/build/lib/cmake/llvm/../../../bin/clang -O3 --rocm-path=/home/stepha27/.cache/pacaur/hip-runtime-amd/src/include/.. -std=c++17 -nogpulib -isystem /home/stepha27/.cache/pacaur/hip-runtime-amd/src/include -isystem /home/stepha27/.cache/pacaur/hip-runtime-amd/src/HIP-rocm-4.5.0/include -isystem /home/stepha27/.cache/pacaur/hip-runtime-amd/src/hipamd-rocm-4.5.0/include --cuda-device-only -x hip /tmp/hip_pch.902501/hip_pch.h -E
clang (LLVM option parsing): Unknown command line argument '-amdgpu-internalize-symbols'.  Try: 'clang (LLVM option parsing) --help'
clang (LLVM option parsing): Did you mean '--large-interval-size-threshold'?
CMake Error at src/CMakeLists.txt:171 (message):
  Failed to embed PCH


-- Configuring incomplete, errors occurred!
```

**Comment by j-stephan** [comment]
Ah, disregard my previous comment. I just noticed that I had a custom LLVM build in my `PATH`. After removing that the build succeeds.

**Comment by j-stephan** [comment]
I noticed that `which clang` did not point to `/usr/bin/clang` but some custom path on my machine. So my `echo $PATH` looked something like this for me:

```
$ echo $PATH
/home/stepha27/sycl-workspace/llvm/build/bin:/opt/rocm/bin:/usr/local/sbin:/usr/local/bin:/usr/bin
```

Note the first entry here (which is my custom LLVM). I unset it temporarily:

```
$ export PATH=/opt/rocm/bin:/usr/local/sbin:/usr/local/bin:/usr/bin
```

and then re-ran the build of `hip-runtime-amd`.

**Comment by FogLizard** [comment]
Thx, now it builds, but miopen-hip 4.3.1-1 is not updated and it is missing hip-rocclr dependency in AUR. I still can't finish building 4.5.0-1 rocm...

**Comment by tpkessler** [comment]
> miopen-hip 4.3.1-1 is not updated

I'm on it! I'll update the remaining packages today.

> hip-rocclr dependency in AUR

AMD renamed the packages upstream. 

> I still can't finish building 4.5.0-1 rocm...

You can submit a PR with updated package version and checksums, see the README of this repo!

**Comment by justinkb** [comment]
thanks for your hard work, it is very much appreciated

**Comment by tpkessler** [comment]
> I still can't finish building 4.5.0-1 rocm...

I've updated all relevant packages.

**Comment by kub0x** [comment]
I had the 'Failed to embed PCH' error. Uninstalled all the packages related to rocm, Installed clang-13 and llvm-libs (ver13) and reinstaled the package using the new way found in README which correctly works:

yay -S rocm-hip-sdk rocm-opencl-sdk

Also if you want to do it manually, as I tried, the comment by @j-stephan solved the PCH error issue. Even tuned the PKGBUILD of hip-runtime-amd to use another compiler and works.

Last but not least, thanks @tpkessler for the work you've done these days as the runtime works now with hipSYCL.

**Comment by FogLizard** [comment]
After the recent system upgrades hip-runtime-amd now builds without PATH changed.

**Comment by tpkessler** [comment]
> thanks @tpkessler for the work you've done these days.

Thank you! Much appreciated.

> the runtime works now with hipSYCL.

That's awesome! I tried it a while back but I couldn't get it working at that point.

> hip-runtime-amd now builds

Great! I'll close this issue.
