### ISSUE TITLE
[rocm-libs]  not updated in AUR

### ISSUE THREAD

**Issue by FogLizard** [rocm-arch/rocm-arch#631]
Could you please update this package?

**Comment by IsaacMvmv** [comment]
read README.MD, now it is rocm-hip-sdk rocm-opencl-sdk
uninstall rocm-libs, rocm-utils and rocm-dev

**Comment by FogLizard** [comment]
Ok, I've been looking at this page and I am not sure if it was in cache or when it got updated, but it still had the old info today until I refreshed.

https://github.com/rocm-arch/rocm-arch

**Comment by tpkessler** [comment]
The meta packages have been removed from the AUR.
