### ISSUE TITLE
[rocm-clang-ocl]  cmake error when parsing string

### ISSUE THREAD

**Issue by Dantali0n** [rocm-arch/rocm-arch#632]
rocm-clang-ocl package version 4.5.0-1 can't be build due to cmake errors:

```
CMake Error at /opt/rocm/share/rocm/cmake/ROCMCreatePackage.cmake:13 (if):
  Syntax error in cmake code at

    /opt/rocm/share/rocm/cmake/ROCMCreatePackage.cmake:13

  when parsing string

    rocm-([0-9]+(\.[0-9]+)+)

  Invalid escape sequence \.
Call Stack (most recent call first):
  CMakeLists.txt:10 (include)
```

My cmake version is 3.21.4

I have manually changed `rocm-([0-9]+(\.[0-9]+)+)` into `rocm-([0-9]+(\\.[0-9]+)+)` and all is well. This needs to be done for both line 13 and 15 of the aforementioned file.

73,
Dantali0n

**Comment by tpkessler** [comment]
I cannot reproduce your error in a clean chroot. Do you use a mix of ROCm packages with different versions?

**Comment by Dantali0n** [comment]
> I cannot reproduce your error in a clean chroot. Do you use a mix of ROCm packages with different versions?

Likely, I keep installing `rocm-dev` thinking that will work because the package name makes more sense to me than `rocm-hip-sdk` and `rocm-opencl-sdk` do. After uninstalling everything and reinstalling it seems to be fine now.
