### ISSUE TITLE
[rocblas]  remove TENSILE_ARCHITECTURES

### ISSUE THREAD

**Issue by riaqn** [rocm-arch/rocm-arch#636]
As of rocm 4.5.0:
https://github.com/ROCmSoftwarePlatform/rocBLAS/blob/337552f09e399d06e1c17939370411a1206452b5/install.sh#L633

Although it's later copied to `TENSILE_ARCHITECTURE`. https://github.com/ROCmSoftwarePlatform/rocBLAS/blob/337552f09e399d06e1c17939370411a1206452b5/CMakeLists.txt#L237

 I wonder if that would make some difference?

**Comment by tpkessler** [comment]
Thank you for the hint @riaqn! I'll change it with the next bug release.
