### ISSUE TITLE
hip-runtime-amd and hip-rocclr are in conflict

### ISSUE THREAD

**Issue by EduMio** [rocm-arch/rocm-arch#639]
Hello. I am trying to install the package but the installation has been problematic. First i had the issue where i could not build llvm-rocm even with my MAKEFLAGS = j1 (building with yay) because 16GB is not enough. Then i moved to arch4edu repo to see if it fixed, but then i run into the problem that it has a dependence conflict. How do i fix this? Should I remove the hip-runtime-amd? Coud it cause problems? I use this machine as a daily driver, it is worth mentioning.

**Comment by tpkessler** [comment]
Hi! arch4edu still distributes the old 4.3.1 packages. `hip-rocclr` was superseded by `hip-runtime-amd`.

> MAKEFLAGS = j1 (building with yay) because 16GB is not enough

This is because `rocm-llvm` uses `ninja`, not `make`. A swap partition fixes your problem.

**Comment by EduMio** [comment]
I see, thank you and sorry for the problem
