### ISSUE TITLE
[rocm-validation-suite] fails to build

### ISSUE THREAD

**Issue by exzombie** [rocm-arch/rocm-arch#64]
There are several issues which apply to both 3.2.0 and 3.1.0.

First, it tries to find includes for rocblas and hip in "wrong" places. As a workaround to see how far I get with the build, I did
```
cd /opt/rocm
ln -s rocm_smi_lib/rocm_smi .
ln -s hip/include/hip include
echo '#include "../rocblas/include/rocblas.h"' > include/rocblas.h
```
This let the build continue. However, it then failed with
```
/tmp/makepkg/rocm-validation-suite/src/ROCmValidationSuite-roc-3.1.0/rcqt.so/src/action.cpp: In member function ‘virtual int rcqt_action::pkgchk_run()’:
/tmp/makepkg/rocm-validation-suite/src/ROCmValidationSuite-roc-3.1.0/rcqt.so/src/action.cpp:209:3: error: ‘command_string’ was not declared in this scope
  209 |   command_string += PKG_CMD_FILE;
```
This is caused by `RVS_OS_TYPE_NUM` being defined to `0`, whereas the `#if`s surrounding the definition of `command_string` only check for `1` and `2`. No big wonder: the two values correspond to `dpkg` and `rpm`, respectively. This thing simply does not support arch. As a workaround, I declared `string command_string = "false";` which will cause this function to properly fail when run (I haven't looked into what it does, but I think I don't want it to  run a package manager anyway). Alternatively, CMake could be lied to when it checks which OS it's building on.

With these workarounds, it builds. Now let's see if it's any use :)

**Comment by exzombie** [comment]
`libgm.so` is incorrectly linked to `librocm_smi64.so.1` and cannot find the library. Other libraries seem to be linked correctly. Running
```
LD_LIBRARY_PATH=/opt/rocm/rocm_smi/lib gdb --args ./rvs -c ./conf/gm_1.conf
```
crashes in
```
0x00007ffff79cf9ce in amd::smi::Monitor::readMonitor(amd::smi::MonitorTypes, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) ()
   from /opt/rocm/rocm_smi/lib/librocm_smi64.so.1
```
Something about that library is not OK.

**Comment by exzombie** [comment]
I found that the gst module wasn't built. It was silently skipped due to not finding blas. I've been hacking around and in the end, I produced the following set of workarounds in the PKGBUILD:
```diff
diff --git a/PKGBUILD b/PKGBUILD
index de0b845..085ab8e 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -17,9 +17,17 @@ build() {
   mkdir -p "$srcdir/build"
   cd "$srcdir/build"
 
+  local src="$srcdir/ROCmValidationSuite-roc-$pkgver"
+  echo -e '#!/bin/bash\necho ubuntu' > "${src}/rvs_os_helper.sh"
+  sed -i 's/\(set(ROCBLAS_.*_DIR.*\))/\1 CACHE PATH "Contains files from ROC blas")/' "${src}/CMakeLists.txt"
+
   cmake -DCMAKE_BUILD_TYPE=Release \
         -DCMAKE_INSTALL_PREFIX=/opt/rocm/rvs \
-        "$srcdir/ROCmValidationSuite-roc-$pkgver"
+        -DROCBLAS_LIB_DIR=/opt/rocm/rocblas/lib \
+        -DROCBLAS_INC_DIR=/opt/rocm/rocblas/include \
+        -DROCR_LIB_DIR=/opt/rocm/hip/lib \
+        -DROCR_INC_DIR=/opt/rocm/hip/include \
+        "$src"
   make
 }
```
It still doesn't build because it can't find `hsa/hsa.h`. I don't see an existing elegant way to modify the include path. It seems that the build system is not flexible enough to accomodate the way rocm as a whole is packaged right now. At this point, I have to give up because I ran out of free time :(

**Comment by acxz** [comment]
Tried to replicate it but I get stuck on installing rocblas, which in turn is getting stuck on install hip-hcc, which is being tracked at the following issue: #68

**Comment by rigred** [comment]
I've got a full build log here for rocm-validation-suite
It fails due to wrong include directives among a few other issues.
My rocblas though builds and installs fine. 

[rocm-validation-suite.2020-05-15_1520.log](https://github.com/rocm-arch/rocm-arch/files/4634593/rocm-validation-suite.2020-05-15_1520.log)

**Comment by acxz** [comment]
@exzombie @rigred The package has been updated to `3.6.0-1` can you guys update the build logs?

**Comment by codyfish** [comment]
I am getting the same error as @acxz . 
I managed to compile the package by using following patch:

```
--- src/ROCmValidationSuite-rocm-3.9.0/rcqt.so/src/action.cpp	2020-09-24 10:09:40.000000000 +0200
+++ action.cpp	2020-11-02 15:32:36.464149284 +0100
@@ -196,13 +196,7 @@
   // Checking if version field exists
   string version_name;
   version_exists = has_property(VERSION, &version_name);
-  #if RVS_OS_TYPE_NUM == 1
-  string command_string = "dpkg --get-selections > ";
-  #endif
-  #if RVS_OS_TYPE_NUM == 2
-  string command_string = "rpm -qa --qf \"%{NAME}\n\" > ";
-  #endif
-  command_string += PKG_CMD_FILE;
+  string command_string = "pacman -Q > ";
 
   // We execute the dpkg-querry
   if (system(command_string.c_str()) == -1) {

```
and applying the patch at the beginning of `build()`
It seems like this string only outputs installed packages into a file if I've understood correctly.

It compiles and installs, but I get the warning the files from `$srcdir ` are referenced in the package, but I couldn't find out which.

The symlink `/usr/bin/rocm_validation_suite` doesnt point to any existing file, but `/opt/rocm/rvs/rvs` actually works. 
However, it ends with "[ERROR ] [  9834.434271] [action_4] p2p-bandwidth No peers found". 

The testscripts in `/opt/rocm/rvs/testscripts` start after making them executable but all fail. Some errors include double-slashes ('/opt/rocm/rvs//libgst.so: cannot open shared object file: No such file or directory') in library paths. 

Note that I have no idea what I am doing and just want to get pytorch to run (Which runs in docker but not on from arch4edu and doesn't compile, hip seems to work though). The problem here seems to be missing binaries for my rx480 (gfx803) but that's another issue.

**Comment by acxz** [comment]
whoa nice investigation @codyfish 
while your solution is very specific to Arch, if you would like I'd merge a PR with your described patch.
Don't worry to much about the $srcdir warnings :)

Any progress is good progress!

**Comment by codyfish** [comment]
I looked a little further into the non existent libraries and modules and found the following:

* The "Fatal: name not found" errors stem from the version calls in the `CMakeLists.txt` Files:
get_version ( "0.0.0" )
Tagging the directory manually with `git tag` solves this issue.
* The libraries do not all reside where expected:
The `CMakeLists.txt` from the subdirectories use `ROCR_LIB_DIR`, which is set to `/opt/rocm/lib`, but some libraries like `amdhip64` reside in other directories like `/opt/rocm/hip/lib` or others in `/opt/hsa/lib`. All header files seem to be in `/opt/rocm/include` as expected. As the different libraries that have `ROCR_LIB_DIR` in their directory are not in one directory, changing this variable only changes (fixes) some of the issues. One could possibly fix those issue by adding tons of patches to the subdirectory `CMakeLists.txt` files or by symlinking the libraries. It feels like those symlinks should be handled by the libraries packages, respectively.

**Comment by acxz** [comment]
currently patched with #465 
Feel free to submit more PRs as needed

**Comment by lahwaacz** [comment]
It seems the checksums of this package became outdated:
```
==> Making package: rocm-validation-suite 3.10.0-1 (Sun Aug  8 08:36:29 2021)
==> Retrieving sources...
  -> Downloading rocm-validation-suite-3.10.0.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   153  100   153    0     0    910      0 --:--:-- --:--:-- --:--:--   910
100  649k    0  649k    0     0  1413k      0 --:--:-- --:--:-- --:--:-- 1413k
  -> Found action.patch
==> Validating source files with sha256sums...
    rocm-validation-suite-3.10.0.tar.gz ... FAILED
    action.patch ... Passed
==> ERROR: One or more files did not pass the validity check!
==> ERROR: Could not download sources.
```
Also it's still stuck at version 3.10.0 whereas the latest is 4.3.0....

**Comment by tpkessler** [comment]
> version 3.10.0 whereas the latest is 4.3.0....

because it does not run on Arch Linux. Feel free to open a PR to fix that problem.

**Comment by sofiageo** [comment]
Hi, I tried to download the rocm-validation-suite [5.0.0](https://github.com/ROCm-Developer-Tools/ROCmValidationSuite/tags) and manually built it, I did the following: 

* Updated Googletest in `CMakeGtestDownload.cmake` to v1.11.0
* Replaced `build/yaml-src/test/gtest-1.10.0` contents with `build/googletest-src` contents
* I applied the patch from the comments

and I think it's working.. I don't have a solution or PR at the moment I just wanted to comment in case other readers stumble on this issue. The validation suite doesn't complete on my PC but I assume it's because of my GPU.

``` 
      Node Name                                                              Node Type               Index      GPU ID        
=============================================================================================
 AMD Ryzen 7 2700X Eight-Core Processor                                          CPU                 0         N/A 

 gfx1010                                                                         GPU                 1         18662
=============================================================================================
[RESULT] [ 16630.594681] Module name :pebb
[RESULT] [ 16630.594823] [action_3] pcie-bandwidth 0 1 18662  distance:20 PCIe:20 (R)

 Final average 
 Final average 
 Iteration value : 1[RESULT] [ 16632.599926] [action_3] pcie-bandwidth  [1/1]  CPU ::0 GPU ::18662  h2d::true  d2h::false  13.856 GBps  duration: 0.284533 sec

```

```
[RESULT] [ 16632.600595] Module name :pqt
[RESULT] [ 16632.600722] [action_4] p2p 18662 18662 peers:false distance:-1
[ERROR ] [ 16632.600732] [action_4] p2p-bandwidth No peers found
```

**Comment by acxz** [comment]
@sofiageo thx for looking into this. I made an upstream issue on the gtest related problems: https://github.com/ROCm-Developer-Tools/ROCmValidationSuite/issues/524

**Comment by sofiageo** [comment]
By the way I realized that the p2p errors are normal because I'm not using the [dkms-driver](https://github.com/ROCm-Developer-Tools/HIP/issues/2214)

**Comment by acxz** [comment]
@tpkessler can you comment on whether or not you were able to build this package in a clean chroot?

**Comment by tpkessler** [comment]
This is the only package of the entire stack I cannot build in clean chroot as `/etc/os-release` is not populated (I use the [clean-chroot-manager](https://github.com/graysky2/clean-chroot-manager)).

**Comment by acxz** [comment]
i c. Are you able to build this without a clean chroot?

**Comment by tpkessler** [comment]
> i c. Are you able to build this without a clean chroot?

Yes! And it also runs successfully.

> For this, we can create a patch 

Awesome!

**Comment by acxz** [comment]
More info: https://bbs.archlinux.org/viewtopic.php?pid=1879880#p1879880

Looks like we just add `systemd` to deps and we good?
I currently can't build roc* packages due to a build issue but if you can get around to trying this would be much appreciated.

**Comment by tpkessler** [comment]
Indeed! After adding `systemd` to `makedepends` I can build the package in a clean chroot.

**Comment by acxz** [comment]
the patch label here is for the rvs patch

**Comment by tpkessler** [comment]
RVS patch is not needed anymore with 5.3.0.
