### ISSUE TITLE
[comgr] F_Text is not a member of llvm::sys::fs

### ISSUE THREAD

**Issue by krisgopal128** [rocm-arch/rocm-arch#640]
OS : Endeavour OS (Arch Linux) 
Kernel : 5.15.6-zen
Package trying to install hip-runtime-amd

Below mention was the error 

[ 34%] Building CXX object CMakeFiles/amd_comgr.dir/src/comgr-compiler.cpp.o
/home/ldapusers/gpadmin/.cache/pacaur/comgr/src/ROCm-CompilerSupport-rocm-4.5.0/lib/comgr/src/comgr-compiler.cpp: In function ‘std::unique_ptr<llvm::raw_fd_ostream> COMGR::getOutputStream(COMGR::{anonymous}::AssemblerInvocation&, clang::DiagnosticsEngine&, bool)’:
/home/ldapusers/gpadmin/.cache/pacaur/comgr/src/ROCm-CompilerSupport-rocm-4.5.0/lib/comgr/src/comgr-compiler.cpp:334:47: error: ‘F_None’ is not a member of ‘llvm::sys::fs’; did you mean ‘OF_None’?
/home/ldapusers/gpadmin/.cache/pacaur/comgr/src/ROCm-CompilerSupport-rocm-4.5.0/lib/comgr/src/comgr-compiler.cpp:334:65: error: ‘F_Text’ is not a member of ‘llvm::sys::fs’; did you mean ‘OF_Text’?
  334 |     Opts.OutputPath, EC, (Binary ? sys::fs::F_None : sys::fs::F_Text));
      |                                                               ^~~~~~
      |                                                               OF_Text
/home/ldapusers/gpadmin/.cache/pacaur/comgr/src/ROCm-CompilerSupport-rocm-4.5.0/lib/comgr/src/comgr-compiler.cpp: In function ‘bool COMGR::executeAssembler(COMGR::{anonymous}::AssemblerInvocation&, clang::DiagnosticsEngine&, llvm::raw_ostream&)’:
/home/ldapusers/gpadmin/.cache/pacaur/comgr/src/ROCm-CompilerSupport-rocm-4.5.0/lib/comgr/src/comgr-compiler.cpp:399:58: error: no matching function for call to ‘llvm::MCContext::MCContext(std::unique_ptr<llvm::MCAsmInfo>::pointer, std::unique_ptr<llvm::MCRegisterInfo>::pointer, std::unique_ptr<llvm::MCObjectFileInfo>::pointer, llvm::SourceMgr*)’
  399 |   MCContext Ctx(MAI.get(), MRI.get(), MOFI.get(), &SrcMgr);
      |                                                          ^
In file included from /home/ldapusers/gpadmin/.cache/pacaur/comgr/src/ROCm-CompilerSupport-rocm-4.5.0/lib/comgr/src/comgr-compiler.cpp:62:
/opt/rocm/llvm/include/llvm/MC/MCContext.h:398:14: note: candidate: ‘llvm::MCContext::MCContext(const llvm::Triple&, const llvm::MCAsmInfo*, const llvm::MCRegisterInfo*, const llvm::MCSubtargetInfo*, const llvm::SourceMgr*, const llvm::MCTargetOptions*, bool)’
  398 |     explicit MCContext(const Triple &TheTriple, const MCAsmInfo *MAI,
      |              ^~~~~~~~~
/opt/rocm/llvm/include/llvm/MC/MCContext.h:398:38: note:   no known conversion for argument 1 from ‘std::unique_ptr<llvm::MCAsmInfo>::pointer’ {aka ‘llvm::MCAsmInfo*’} to ‘const llvm::Triple&’
  398 |     explicit MCContext(const Triple &TheTriple, const MCAsmInfo *MAI,
      |                        ~~~~~~~~~~~~~~^~~~~~~~~
/home/ldapusers/gpadmin/.cache/pacaur/comgr/src/ROCm-CompilerSupport-rocm-4.5.0/lib/comgr/src/comgr-compiler.cpp:411:9: error: ‘class llvm::MCObjectFileInfo’ has no member named ‘InitMCObjectFileInfo’; did you mean ‘initMCObjectFileInfo’?
  411 |   MOFI->InitMCObjectFileInfo(Triple(Opts.Triple), PIC, Ctx);
      |         ^~~~~~~~~~~~~~~~~~~~
      |         initMCObjectFileInfo
/home/ldapusers/gpadmin/.cache/pacaur/comgr/src/ROCm-CompilerSupport-rocm-4.5.0/lib/comgr/src/comgr-compiler.cpp:485:16: error: ‘class llvm::MCStreamer’ has no member named ‘InitSections’; did you mean ‘initSections’?
  485 |     Str.get()->InitSections(Opts.NoExecStack);
      |                ^~~~~~~~~~~~
      |                initSections
/home/ldapusers/gpadmin/.cache/pacaur/comgr/src/ROCm-CompilerSupport-rocm-4.5.0/lib/comgr/src/comgr-compiler.cpp: In function ‘amd_comgr_status_t COMGR::outputToFile(llvm::StringRef, llvm::StringRef)’:
/home/ldapusers/gpadmin/.cache/pacaur/comgr/src/ROCm-CompilerSupport-rocm-4.5.0/lib/comgr/src/comgr-compiler.cpp:560:35: error: ‘F_None’ is not a member of ‘llvm::sys::fs’; did you mean ‘OF_None’?
  560 |   raw_fd_ostream OS(Path, EC, fs::F_None);
      |                                   ^~~~~~
      |                                   OF_None
make[2]: *** [CMakeFiles/amd_comgr.dir/build.make:76: CMakeFiles/amd_comgr.dir/src/comgr-compiler.cpp.o] Error 1
make[2]: Leaving directory '/home/ldapusers/gpadmin/.cache/pacaur/comgr/src/build'
make[1]: *** [CMakeFiles/Makefile2:303: CMakeFiles/amd_comgr.dir/all] Error 2
make[1]: Leaving directory '/home/ldapusers/gpadmin/.cache/pacaur/comgr/src/build'
make: *** [Makefile:166: all] Error 2
make: Leaving directory '/home/ldapusers/gpadmin/.cache/pacaur/comgr/src/build'
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by tpkessler** [comment]
Did you uninstall all ROCm packages from previous releases before building `comgr`? (See the README for more details.)

**Comment by tpkessler** [comment]
The problem in your case is that `cmake` finds system `llvm` before `rocm-llvm`.

**Comment by krisgopal128** [comment]
Sorry for the delay.
based on your comment. i will try to reinstall the package again
