### ISSUE TITLE
Provide a way to specify which gfx targets to compile for in the PKGBUILD

### ISSUE THREAD

**Issue by Ta180m** [rocm-arch/rocm-arch#641]
I have a Radeon RX 6600 XT, and while ROCm does not officially support gfx1032 yet, I was able to manually edit the `CMakeLists.txt` for the various repositories to compile for the gfx1032 target. This also decreased my compile times by a lot and the resulting binaries were much smaller since they didn't contain binaries for any other targets. For instance, rocFFT is only 600MB when only compiling for gfx1032 instead of 3GB. I'm wondering if a programmatic way to do this could be added to the ROCm PKGBUILDs.

**Comment by tpkessler** [comment]
Hey @Ta180m there are currently no plans to add such options to the build scripts. We try to stay as close as possible to upstream packages (http://repo.radeon.com/rocm/apt/4.5.2/pool/main/) which include binaries for all supported architectures.

**Comment by Ta180m** [comment]
One idea I had would be to have a variable at the top of the PKGBUILD called `AMDGPU_TARGETS` to specify which targets to compile for. It could be commented out by default, and users could manually set a custom value such as `gfx1032`, and the PKGBUILD could check if the variable is set and modify the `CMakeLists.txt` if it is.

**Comment by tpkessler** [comment]
I've added a paragraph on the usage of `AMDGPU_TARGETS` to the readme.
