### ISSUE TITLE
Conflicts between AUR and arch4edu

### ISSUE THREAD

**Issue by darkbasic** [rocm-arch/rocm-arch#642]
I've been trying to install `rocm-hip-sdk` and `rocm-opencl-sdk` from `arch4edu` but it failed because it was trying to pull deps from both arch4edu and the AUR, possibly because arch4edu is outdated (AUR is 4.5.2, arch4edu 4.5.0).
How are you supposed to handle this? It's been 10 days since 4.5.2 got released in the AUR, so there must definitely be a workaround to this. I'm trying to compile 4.5.2 from AUR but it's going on for more than 24 hours with no end in sight.

**Comment by tpkessler** [comment]
> How are you supposed to handle this?

Keep your cool and wait. Everything here is done voluntarily. @petronny is doing a fantastic job over at arch4edu, but sometimes things need some time to work. 

> It's been 10 days since 4.5.2 got released in the AUR, so there must definitely be a workaround to this.

Compile it from source. This will _always_ work.

>  I'm trying to compile 4.5.2 from AUR

Yes, compiling the full ROCm stack takes hours.

**Comment by darkbasic** [comment]
> Keep your cool and wait. Everything here is done voluntarily. @petronny is doing a fantastic job over at arch4edu, but sometimes things need some time to work.

Nobody is denying that, I just wanted to know if this is expected behaviour or if I'm doing something wrong.

> Compile it from source

That's what I did, but I also had to remove the `arch4edu` repository in order to do so. Also what's the point of a binary repo if you can't use it? There was no way to install either 4.5.0 from `arch4edu` nor `4.5.2` from `arch4edu` when I add the repo installed.

**Comment by tpkessler** [comment]
> expected behaviour or if I'm doing something wrong.

Currently, arch4edu is not in sync with the packages on the AUR, so this is expected behavior. @petronny can tell us more about the current status.

> Also what's the point of a binary repo if you can't use it?

As I wrote before: There's no guarantee that arch4edu is synced in the moment I push a new ROCm version to the AUR. It takes time to update the scripts and to build the packages.

**Comment by petronny** [comment]
Currently the main build server for arch4edu is down. And I'm not sure if it can be fixed again.

I'm trying to migrate things to a new server.

**Comment by darkbasic** [comment]
> As I wrote before: There's no guarantee that arch4edu is synced in the moment I push a new ROCm version to the AUR

I'm fine with that, but still it should **not** leave the system in a broken dependency state, instead it should simply let me compile from AUR instead (or, even better, allow me to use the latest binary version). Instead I had to remove arch4edu in order to satisfy deps.

**Comment by acxz** [comment]
Closing this issue as the conversation has ended.
