### ISSUE TITLE
Compilation can be faster with: make -j $(nproc)

### ISSUE THREAD

**Issue by PysKa-Ratzinger** [rocm-arch/rocm-arch#643]
Basically title.

I just noticed that most PKGBUILD's here have the command `make -C build` for compilation.

Changing it to `make -j $(nproc) -C build` would make compilation times faster on PCs with multiple cores.

**Comment by tpkessler** [comment]
Hey, @PysKa-Ratzinger, this is intended as `MAKEFALGS` are set globally in `makepkg.conf`, see the [wiki article](https://wiki.archlinux.org/title/Makepkg#Parallel_compilation).

**Comment by PysKa-Ratzinger** [comment]
I did end up changing my `MAKEFLAGS` after I created the issue. Good to know it is intended then. I'll close the issue. ;)
