### ISSUE TITLE
[rocm-llvm] Build fails with gcc 11.1.0

### ISSUE THREAD

**Issue by tpkessler** [rocm-arch/rocm-arch#648]
Building `rocm-llvm 5.0.0` fails with an internal compiler error (a bug). Only with `clang` the package is built successfully. Until `gcc` is updated upstream, I add `clang` to `makedepends`.

**Comment by acxz** [comment]
This issue has been closed with https://github.com/rocm-arch/rocm-arch/commit/18cdc7ef21386b6cf4848a60cd570b03dbfc5461
