### ISSUE TITLE
Use upstream `.deb` for version info packages

### ISSUE THREAD

**Issue by JP-Ellis** [rocm-arch/rocm-arch#739]
Currently, the PKGBUILDs generate the various `version` files used in ROCM (in `/opt/rocm/.info`).  I am creating a tracking issue to instead use the published `.deb` files.

As most of these `deb` files only contain text file, there would be no need to repackage them as `-bin` packages.

Of the top of my head, these packages are:
- [ ] `rocm-core` (note that the upstream `.deb` *does* have binaries, so we need to check what to do there)
- [ ] `rocm-hip-libraries`
- [ ] `rocm-hip-runtime`
- [ ] `rocm-hip-sdk`
- [ ] `rocm-language-runtime`
- [ ] `rocm-opencl-sdk`

**Comment by JP-Ellis** [comment]
I have pushed commits to address the above for `rocm-hip-{libraries,runtime,sdk}`, `rocm-language-runtime` and `rocm-opencl-sdk` in the same PR which upgrades them to `5.1.0`.  Feel free to squash them before mergin them.

**Comment by tpkessler** [comment]
Thank you for working on this @JP-Ellis. When those packages were released first I took a look at the deb files and then generated the info files manually. But as there's no source code for them I think it's better to extract the info files from the deb files. This will greatly simplify the maintenance of these packages.
