### ISSUE TITLE
Replace logic for AMDGPU_TARGETS

### ISSUE THREAD

**Issue by tpkessler** [rocm-arch/rocm-arch#745]
Right now the possible GPU targets are listed explicitly, for instance https://github.com/rocm-arch/rocm-arch/blob/04f1dd9701f5fd7b35d234757660a1e703511532/rocfft/PKGBUILD#L27

With the next release this should be changed to https://github.com/rocm-arch/rocm-arch/blob/04f1dd9701f5fd7b35d234757660a1e703511532/rocsparse/PKGBUILD#L22-L24

**Comment by JP-Ellis** [comment]
How did you want to upgrade the various packages?  Probably easier to push the changes all at once instead of upgrading packages individually.  Did you want to bump the `pkgrel` as well, or leave it as is and wait for the next released version?

**Comment by acxz** [comment]
As a side note, can we also target #636 ?
TENSILE_ARCHITECTURE should be deprecated by AMDGPU_TARGETS as seen here: 

https://github.com/ROCmSoftwarePlatform/rocBLAS/blob/490c4140fc96cd1e0a04dca3fdab64420110585c/CMakeLists.txt#L244

**Comment by tpkessler** [comment]
>  Did you want to bump the pkgrel as well, or leave it as is and wait for the next released version?

We can include those changes as we update the packages to 5.1.1.

**Comment by tpkessler** [comment]
> As a side note, can we also target https://github.com/rocm-arch/rocm-arch/issues/636 ?

Yes, TENSILE_ARCHITECTURE will be replaced with the next update.

**Comment by acxz** [comment]
After the upgrade to 5.1.1 what is the status of this issue?

**Comment by tpkessler** [comment]
New logic in all relevant packages.

**Comment by acxz** [comment]
We all did some good work today! Everyone should pat themselves on the back!
