### ISSUE TITLE
Upgrade to 5.1.1

### ISSUE THREAD

**Issue by JP-Ellis** [rocm-arch/rocm-arch#747]
`5.1.1` has been released and is making it way through the various packages.  We should probably merge the remaining `5.1.0` PRs though before the `5.1.1` upgrade.

This will be a good opportunity to implement #745 too.

As with the `5.1.0` upgrade, I'm happy to contribute.  As I expect that the `5.1.0` to `5.1.1` transisition will be mostly trivial, would there be any objects to having just one PR instead of a PR for each package?

**Comment by tpkessler** [comment]
Hey @JP-Ellis!
>  We should probably merge the remaining 5.1.0 PRs though before the 5.1.1 upgrade.

Yes. The reason why I haven't merged all your PRs yet is that I build all packages in a clean chroot before I push them to this repo and the AUR.

> This will be a good opportunity to implement https://github.com/rocm-arch/rocm-arch/issues/745 too.

I agree.

> As with the 5.1.0 upgrade, I'm happy to contribute.

Thank you! Much appreciated.

> Would there be any objects to having just one PR instead of a PR for each package?

No. We can split responsibility for the updates. I take care of the low level packages up to HIP (including `rocm-gdb`, `roctracer`,...) and you can update the HIP libraries. Is this ok for you?

**Comment by acxz** [comment]
I can tackle the `cuda` related packages such as `hip-runtime-nvidia` and `hipify-clang`.

**Comment by tpkessler** [comment]
All packages* have been updated to 5.1.1! Thank you very much for your support @acxz and @JP-Ellis!

(*) llvm-mlir does not have a 5.1.1 release / tag.
