### ISSUE TITLE
[miopen-opencl-5.1.1] linker error

### ISSUE THREAD

**Issue by lahwaacz** [rocm-arch/rocm-arch#759]
miopen-opencl-5.1.1 does not build for me in a clean chroot:
```
/usr/bin/ld: ../lib/libMIOpen.so.1.0: undefined reference to `miirGetKernelCount'
/usr/bin/ld: ../lib/libMIOpen.so.1.0: undefined reference to `miirGetExecutionDims'
/usr/bin/ld: ../lib/libMIOpen.so.1.0: undefined reference to `miirDestroyHandle'
/usr/bin/ld: ../lib/libMIOpen.so.1.0: undefined reference to `miirLowerTuningParams'
/usr/bin/ld: ../lib/libMIOpen.so.1.0: undefined reference to `miirBufferGet'
/usr/bin/ld: ../lib/libMIOpen.so.1.0: undefined reference to `miirLowerBin'
/usr/bin/ld: ../lib/libMIOpen.so.1.0: undefined reference to `miirCreateHandle'
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
```

Dependencies that were installed:
```
Packages (41) comgr-5.1.1-1  hip-runtime-amd-5.1.1-1  hsa-amd-aqlprofile-bin-5.1.1-1  hsa-rocr-5.1.1-1  hsakmt-roct-5.1.1-1  hwdata-0.358-1  kmod-29-3
              libdrm-2.4.110-1  libedit-20210910_3.1-1  libglvnd-1.4.0-1  libnsl-2.0.0-2  libomxil-bellagio-0.9.3-3  libpciaccess-0.16-2  libunwind-1.6.2-1
              libx11-1.7.5-1  libxau-1.0.9-3  libxcb-1.14-1  libxdamage-1.1.5-3  libxdmcp-1.1.3-3  libxext-1.3.4-3  libxfixes-6.0.0-1  libxshmfence-1.3-2
              libxxf86vm-1.1.4-4  llvm-libs-13.0.1-2  lm_sensors-1:3.6.0.r41.g31d1f125-1  mesa-22.0.1-3  numactl-2.0.14-2  openmp-13.0.1-1  pciutils-3.7.0-2
              python-3.10.4-1  rocm-device-libs-5.1.1-1  rocminfo-5.1.1-1  vulkan-icd-loader-1.3.208-1  wayland-1.20.0-2  xcb-proto-1.14.1-5
              xorgproto-2021.5-1  z3-4.8.14-1  ocl-icd-2.3.1-1  rocblas-5.1.1-1  rocm-llvm-5.1.1-1  rocm-llvm-mlir-5.1.0-1
```
makedepends:
```
Packages (10) boost-libs-1.78.0-1  hicolor-icon-theme-0.17-2  jsoncpp-1.9.5-1  libuv-1.43.0-1  rhash-1.4.2-1  boost-1.78.0-1  cmake-3.23.0-1
              miopengemm-5.1.1-1  opencl-headers-2:2022.01.04-1  rocm-cmake-5.1.1-1
```

**Comment by tpkessler** [comment]
I cannot reproduce this on my machine and I cannot find an obvious reason in your logs why it shouldn't build.

**Comment by lahwaacz** [comment]
It's probably LTO again... Do you use paru to build in a chroot? I see from [its source](https://github.com/Morganamilo/paru/blob/08da32781c05e563ac781164a995fa8db6c7d679/src/lib.rs#L447) that paru defaults to using `/etc/makepkg.conf` in the chroot. Since users might modify this file, it may not result in a _clean_ chroot build. On the other hand, I'm using [aurutils](https://github.com/AladW/aurutils/) which by default uses `/usr/share/devtools/makepkg-x86_64.conf` from the [devtools](https://archlinux.org/packages/extra/any/devtools/) package. The difference is that Arch did not enable LTO by default in `/etc/makepkg.conf`, but only in `/usr/share/devtools/makepkg-x86_64.conf` (so all official Arch packages are built with LTO unless explicitly disabled in the PKGBUILD).

**Comment by lahwaacz** [comment]
Disabling LTO in rocm-llvm-mlir fixed it for me.

**Comment by acxz** [comment]
edit some more useful links: [`devtools/makepkg.conf`](https://gitlab.archlinux.org/archlinux/devtools/-/blob/20220207/makepkg-x86_64.conf) and [`pacman/makepkg.conf`](https://gitlab.archlinux.org/pacman/pacman/-/blob/v6.0.1/etc/makepkg.conf.in)

While I personally use `paru -Ui --chroot` I have edited my `etc/makepkg.conf` to resemble the devtools makepkg.conf, most noticeably this includes adding lto. With paru you can also specify the specific the makepkg.conf to use for the chroot and can have it point the devtools makepkg.conf if you want to keep a separate etc/makepkg.conf.

But I agree with @lahwaacz here, @tpkessler you should change/update your makepkg.conf to resemble the devtools.

**Comment by tpkessler** [comment]
Good point! I didn't know that. I initialized my clean chroot a while back. I will set up a new one with LTO enabled for the next ROCm release.
