### ISSUE TITLE
[rocminfo] puts the executable in /opt, which means it's not on PATH

### ISSUE THREAD

**Issue by kozross** [rocm-arch/rocm-arch#76]
After you install ``rocminfo``, the executable itself is not in ``/usr/bin`` or anywhere else like that, instead being placed in ``/opt/rocm/bin``. This is not typically on the PATH, which means you need a full path to call it. This is both confusing and undesirable.

**Comment by acxz** [comment]
Agreed, we are trying to add symlinks from the /opt location to /usr/bin.

**Comment by ranisalt** [comment]
I think there's no point in installing to /opt if we then symlink to /usr. We just use /opt because AMD does so, but it is blatantly wrong.

**Comment by naetherm** [comment]
> We just use /opt because AMD does so, but it is blatantly wrong.
It is installed in /opt because that's the specification of FHS: https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.pdf#page=20

**Comment by ranisalt** [comment]
@naetherm aha, that makes sense, didn't catch up to the latest FHS yet. So it looks like packages are supposed to be self-isolated inside /opt, right? On the contrary of most Arch packages currently do.
