### ISSUE TITLE
[migraphx] Build does not enable GPU backend

### ISSUE THREAD

**Issue by opcod3** [rocm-arch/rocm-arch#770]
Building migraphx in a clean chroot using paru, results in the wrong compiler being selected by cmake.

Therefore HIP support is not detected and the GPU backend gets disabled.

**Comment by JP-Ellis** [comment]
Strange that it fails to build for you.

If you adjust the `PKGBUILD` by adding the following before `cmake` is run, is the issue fixed?

```
export CC=/opt/rocm/llvm/bin/clang
export CXX=/opt/rocm/llvm/bin/clang++
```

If not, what about:

```
export CXX=/opt/rocm/hip/bin/hipcc
```

**Comment by acxz** [comment]
Closing this to inactivity, feel free to comment on this @opcod3 if the issue still persists for you or if you come back to this.
