### ISSUE TITLE
Mismatched checksums in 'rocsolver'

### ISSUE THREAD

**Issue by pangwalla** [rocm-arch/rocm-arch#772]
Getting the following error message with paru when attempting to build rocsolver:
`==> ERROR: One or more files did not pass the validity check!
error: failed to download sources for 'rocsolver-5.1.1-1':`

The rocsolver source tarball passes its checksum, but the associated patch fails:

PKGBUILD version -> '3c2935fea8136ce6d1078318a50aa3c58bd39384da7e3a7e12e8d7fec5e31f69'
curl `curl -O https://github.com/acxz/rocSOLVER/commit/0f4658e04ac7b48fea213f29b209a0206b67c43f.patch`
then sha256sum -> '1f2ad0256013dcc3f3d6a494b864326d2ac0e79b528102cd5b235f55f8069c61'

Don't see any recent changes recently, unclear to me why this is failing.

**Comment by JP-Ellis** [comment]
I can confirm this.  The upstream patch has indeed changed with the diff of the patches being:

```diff
--- fmt.patch	2022-04-13 14:51:47.286786514 +1000
+++ new-fmt.patch	2022-04-22 07:46:46.149270257 +1000
@@ -8,7 +8,7 @@
  1 file changed, 22 insertions(+), 14 deletions(-)
 
 diff --git a/library/src/include/rocsolver_logvalue.hpp b/library/src/include/rocsolver_logvalue.hpp
-index 199f8d57..ecb10f16 100644
+index 199f8d57d..ecb10f168 100644
 --- a/library/src/include/rocsolver_logvalue.hpp
 +++ b/library/src/include/rocsolver_logvalue.hpp
 @@ -8,6 +8,14 @@
```

I wonder whether there was a forced push perhaps?  As the change is only in the patch's metadata, it is completely safe to proceed.
