### ISSUE TITLE
[hcc] need to sync

### ISSUE THREAD

**Issue by acxz** [rocm-arch/rocm-arch#78]

**Comment by acxz** [comment]
@farnoy, @naetherm, @neeshy this issue has been open for a week, can you take a look at it? If we don't hear a response within a couple of days, we'll go ahead and submit an orphan request for this package.

**Comment by farnoy** [comment]
@acxz Added you as co-maintainer for this package as well

**Comment by acxz** [comment]
Thank you! and synced
