### ISSUE TITLE
[rocm-llvm-mlir] Validating source files fails

### ISSUE THREAD

**Issue by tayebzaidi** [rocm-arch/rocm-arch#784]
When attempting to install python-pytorch-rocm, the dependency rocm-llvm-mlir was being downloaded. I had already run `paru -S rocm-hip-sdk rocm-opencl-sdk` successfully and this is the output of my attempt to install python-pytorch-rocm

```
paru -S python-pytorch-rocm
:: Resolving dependencies...
:: There are 2 providers available for miopen:
:: Repository AUR:
    1) miopen-hip  2) miopen-opencl  
Enter a number (default=1): 
:: Calculating conflicts...
:: Calculating inner conflicts...

Aur (4) rocm-llvm-mlir-5.1.2-1  miopen-hip-5.1.3-1  hipmagma-2.6.2-1  python-pytorch-rocm-1.11.0-3

:: Proceed to review? [Y/n]: 

:: Downloading PKGBUILDs...
 PKGBUILDs up to date
 nothing new to review
fetching devel info...
==> Making package: rocm-llvm-mlir 5.1.2-1 (Mon May 23 19:11:45 2022)
==> Retrieving sources...
  -> Downloading rocm-llvm-mlir-5.1.2.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 51.9M    0 51.9M    0     0  40047      0 --:--:--  0:22:41 --:--:-- 26023
==> Validating source files with sha256sums...
    rocm-llvm-mlir-5.1.2.tar.gz ... FAILED
==> ERROR: One or more files did not pass the validity check!
error: failed to download sources for 'rocm-llvm-mlir-5.1.2-1':
```

Downloading the file directly from Github using a browser shows a different sha256sum that is also not the same as the one in `.SRCINFO`. It seems like the sha256sums may not have been updated yet for the package version but I am not sure whether this package should be using the 5.1.2 or the 5.1.3 package from Github.

Any help resolving this issue is appreciated, thanks!

**Comment by tpkessler** [comment]
Hi @tayebzaidi! Thanks for reporting this and bringing my attention to the newest release. I've updated the package to the recent 5.1.3 version.

**Comment by tpkessler** [comment]
Closing this issue as checksums were updated. Feel free to reopen if you still encounter problems.
