### ISSUE TITLE
[rocsparse] Illegal instruction with gfx1010

### ISSUE THREAD

**Issue by DarkShadow44** [rocm-arch/rocm-arch#791]
I'm compiling with AMDGPU_TARGETS=gfx1010 (AMD Radeon RX 5700), and it fails with a lot of errors:

[error.log](https://github.com/rocm-arch/rocm-arch/files/9006150/error.log)

**Comment by DarkShadow44** [comment]
Also see https://github.com/ROCmSoftwarePlatform/rocSPARSE/issues/250

**Comment by tpkessler** [comment]
Hey @DarkShadow44! Does including this patch fixes your problem?

**Comment by acxz** [comment]
@DarkShadow44 can you specify which exact patch works? Is it this patch: https://github.com/ROCmSoftwarePlatform/rocSPARSE/issues/250#issuecomment-1174690582?

Based on your feedback, if you'd like to submit a PR to the rocsparse PKGBUILD adding that patch. That would be wonderful.

**Comment by DarkShadow44** [comment]
@acxz Both patches will work. The patch I originally meant was the one from xuhuisheng, since the other one didn't exist yet.

**Comment by acxz** [comment]
Got it. I just made a PR for adding @cmgb's patch into the rocsparse PKGBUILD.

**Comment by tpkessler** [comment]
Now in [extra].
