### ISSUE TITLE
[rocminfo] need to sync

### ISSUE THREAD

**Issue by acxz** [rocm-arch/rocm-arch#80]

**Comment by naetherm** [comment]
Postponed due to update of rocm infrastructure to 3.3.0 ?

**Comment by acxz** [comment]
I don't see why. we can just sync the latest version we have here on the git to the AUR. The

**Comment by acxz** [comment]
@farnoy, @naetherm, @neeshy this issue has been open for a week, can you take a look at it? If we don't hear a response within a couple of days, we'll go ahead and submit an orphan request for this package.

**Comment by farnoy** [comment]
Sorry @acxz, been very busy lately. I've added you as Co-Maintainer, could you do the sync yourself?

**Comment by acxz** [comment]
Thank you! and synced.
