### ISSUE TITLE
[hipsparse] hip::amdhip64/device/host build errors

### ISSUE THREAD

**Issue by 7910f6ba7ee4** [rocm-arch/rocm-arch#801]
Attempting to install ROCm from the AUR without arch4edu and receiving a few build errors. Because the errors appear to not be linked, I'm creating two issues (#800).

Trying to install hipsparse gives a [variety](https://github.com/rocm-arch/rocm-arch/files/9068322/bulid_errors.log) of errors, but mainly consist of not finding the targets `hip::amdhip64, hip::device, hip::host` and the file `/opt/rocm/hip/lib/cmake/hip/hip-targets.cmake`.

Here is the [CMakeOutput.log](https://github.com/rocm-arch/rocm-arch/files/9068311/CMakeOutput.log).

And output of `hipconfig`, if it's of any use.
```
HIP version  : 5.2.21151-d422fb5

== hipconfig
HIP_PATH     : /opt/rocm
ROCM_PATH    : /opt/rocm
HIP_COMPILER : clang
HIP_PLATFORM : amd
HIP_RUNTIME  : rocclr
CPP_CONFIG   :  -D__HIP_PLATFORM_HCC__= -D__HIP_PLATFORM_AMD__= -I/opt/rocm/include -I/opt/rocm/llvm/bin/../lib/clang/14.0.0 -I/opt/rocm/hsa/include

== hip-clang
HSA_PATH         : /opt/rocm/hsa
HIP_CLANG_PATH   : /opt/rocm/llvm/bin
clang version 14.0.0 (https://aur.archlinux.org/rocm-llvm 4f4ca29a97e446b1ee0d5ccc511a56787e7d7b64)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/llvm/bin
AOMP-12.0-3 (http://github.com/ROCm-Developer-Tools/aomp):
 Source ID:12.0-3-bebd719ff2bb58a4220658c708f91d486729dbc1
  LLVM version 14.0.0git
  Optimized build.
  Default target: x86_64-pc-linux-gnu
  Host CPU: skylake

  Registered Targets:
    amdgcn - AMD GCN GPUs
    r600   - AMD GPUs HD2XXX-HD6XXX
    x86    - 32-bit X86: Pentium-Pro and above
    x86-64 - 64-bit X86: EM64T and AMD64
hip-clang-cxxflags :  -std=c++11 -isystem "/opt/rocm/llvm/lib/clang/14.0.0/include/.." -isystem /opt/rocm/hsa/include -isystem "/opt/rocm/include" -O3
hip-clang-ldflags  :  -L"/opt/rocm/lib" -O3 -lgcc_s -lgcc -lpthread -lm -lrt

=== Environment Variables
PATH=/home/whisper/.local/bin:/usr/local/bin:/usr/bin:/var/lib/snapd/snap/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl

== Linux Kernel
Hostname     : MK1
Linux MK1 5.15.50-1-MANJARO #1 SMP PREEMPT Sun Jun 26 07:06:30 UTC 2022 x86_64 GNU/Linux
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	21.3.2
Codename:	Ruah

```

**Comment by acxz** [comment]
Have you tried building in a clean chroot? If not, can you post the output of a build in clean chroot?

**Comment by 7910f6ba7ee4** [comment]
I'm unfamiliar with trying to build in a clean chroot, following the [arch](https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot) wiki entry results in missing dependencies since pacman is trying to install packages that exist on the AUR. How do I resolve this, since building each dependency individually does not work?

**Comment by acxz** [comment]
Take a look at `paru`. `paru` is an aur helper that can build packages in a clean chroot. Look at the `--chroot` option. For example `paru -Syu --chroot`.

**Comment by tpkessler** [comment]
Setting `HIP_PATH` to `/opt/rocm` fixes the issue with the newest `hip-rutime-amd` package.
