### ISSUE TITLE
unable to satisfy dependency 'hsa-rocr>=3.1.0' required by rocm-opencl-runtime

### ISSUE THREAD

**Issue by kozross** [rocm-arch/rocm-arch#81]
I got this today when trying to update both ``rocm-opencl-runtime`` and ``rocm-device-libs``.

**Comment by acxz** [comment]
Similar to roct-thunk-interface we have also deprecated rocr-runtime in favor of the upstream name: hsa-rocr to make it easier for users to use ROCm's official documentation.

Try installing hsa-rocr.

**Comment by kozross** [comment]
That solved it, thanks!
