### ISSUE TITLE
[rocm-llvm-mlir] Appending RPATH linker flags with list(APPEND ...) generates a stray ";", breaking compilation

### ISSUE THREAD

**Issue by acxz** [rocm-arch/rocm-arch#818]
From @linedot 

Hi all,
In `cmake/llvm-project.cmake` rpath flags are appended to `CMAKE_EXE_LINKER_FLAGS` with list(APPEND .... This inserts a ";" between the previous flags (if present) and the newly appended flags, breaking compilation.

Upstream issue: https://github.com/ROCmSoftwarePlatform/llvm-project-mlir/issues/687

**Comment by acxz** [comment]
patched with #808

**Comment by tpkessler** [comment]
Patch merged upstream.
