### ISSUE TITLE
[miopen] dependency conflict

### ISSUE THREAD

**Issue by helfio** [rocm-arch/rocm-arch#84]
Hi,

I'm trying to set everything up in order to use my RX 590 with tensorflow-rocm and it looks like MIOpen is a necessary package. The currently available PKGBUILD has as dependency clang-ocl while there is another package in the AUR called rocm-clang-ocl which apparently is same package, different name. I renamed clang-ocl -> rocm-clang-ocl and apparently that is fine and the new error I think is the one reported in #56.

If you are ok, I can make a PR with this minor change.

Edit:  I forgot to say rocm-clang-ocl is already there because it is a dependency of rocm-utils, which I have it installed.

**Comment by acxz** [comment]
sorry for taking a long time to respond to this, should be resolved with 
99f2a22
