### ISSUE TITLE
[rocm-llvm] Error 404 for glibc2.36.patch

### ISSUE THREAD

**Issue by Thorhian** [rocm-arch/rocm-arch#843]
Hello, I wanted to compile rocm-llvm, but it seems that the glibc patch used in the package build no longer exists at this link: https://reviews.llvm.org/file/data/ze666dm5s4qvfxexr6xo/PHID-FILE-vjcwlcibswfg77e4dyam/D129471.diff

I keep getting 404s lol. Any quick fix would be appreciated.

**Comment by Fisk24** [comment]
404 here as well. this is making it impossible to install from the AUR

**Comment by ticklebunny** [comment]
Was making sure I wasn't the only one receiving a 404 as well.

**Comment by ikubaku** [comment]
The original patch seems to be at https://reviews.llvm.org/D129471 (click "Download Raw Diff"). The link has been changed for some reason. Maybe the download link is not persistent?

We can use https://reviews.llvm.org/D129471?download=true for downloading the patch instead.

**Comment by tpkessler** [comment]
Yes, the URL has changed over night. I've added a local copy of the patch to the repo.

**Comment by Thorhian** [comment]
> Yes, the URL has changed over night. I've added a local copy of the patch to the repo.

Thanks a ton. Should I close this issue for now people?
