### ISSUE TITLE
[rocm-hip-libraries, rocm-hip-sdk] should also depend on hipsolver

### ISSUE THREAD

**Issue by wuxxin** [rocm-arch/rocm-arch#845]
while building a customized version of tensorflow-rocm, hipsolver headers where not found.
this came to a surprise, because the base packages 
```
rocm-hip-libraries
rocm-hip-sdk
```

are installed and should probably be sufficient to pull in hipsolver

**Comment by tpkessler** [comment]
The dependencies of the meta packages are that of the [official documentation](https://docs.amd.com/bundle/ROCm-Installation-Guide-v5.0.1/page/Meta-packages_in_ROCm_Programming_Models.html#d2457e366) and `hipsolver` is not part of any meta package.

**Comment by wuxxin** [comment]
makes sense to keep packages close to upstream,
but in contrast to the stated documentation,
the control files from the meta packages of the upstream repo:

+ https://repo.radeon.com/rocm/apt/5.2.1/pool/main/r/rocm-hip-sdk/rocm-hip-sdk_5.2.1.50201-79_amd64.deb

+ https://repo.radeon.com/rocm/apt/5.2.1/pool/main/r/rocm-hip-libraries/rocm-hip-libraries_5.2.1.50201-79_amd64.deb

both have hipsolver as dependencies.

+ rocm-hip-sdk
```
Architecture: amd64
Depends: rocm-hip-libraries (= 5.2.1.50201-79), 
  rocm-llvm (= 14.0.0.22204.50201-79), rocm-core (= 5.2.1.50201-79),
  rocm-hip-runtime-dev (= 5.2.1.50201-79), hipblas-dev (= 0.51.0.50201-79), 
  hipcub-dev (= 2.10.12.50201-79), hipfft-dev (= 1.0.8.50201-79),
  hipsparse-dev (= 2.1.0.50201-79), hipsolver-dev (= 1.4.0.50201-79),
  miopen-hip-dev (= 2.17.0.50201-79), rccl-dev (= 2.11.4.50201-79), 
  rocalution-dev (= 2.0.2.50201-79), rocblas-dev (= 2.44.0.50201-79), 
  rocfft-dev (= 1.0.17.50201-79), rocprim-dev (= 2.10.9.50201-79), 
  rocrand-dev (= 2.10.9.50201-79), rocsolver-dev (= 3.18.0.50201-79),
  rocsparse-dev (= 2.2.0.50201-79), rocthrust-dev (= 2.10.9.50201-79)
Description: Radeon Open Compute (ROCm) Runtime software stack
Homepage: https://github.com/RadeonOpenCompute/ROCm
Maintainer: ROCm Libs Support <rocm-libs.support@amd.com>
Package: rocm-hip-sdk
Priority: optional
Section: devel
Version: 5.2.1.50201-79
Installed-Size: 13
```


+ rocm-hip-libraries
```control
Architecture: amd64
Depends: rocm-core (= 5.2.1.50201-79), rocm-hip-runtime (= 5.2.1.50201-79),
  hipblas (= 0.51.0.50201-79), hipfft (= 1.0.8.50201-79),
  hipsparse (= 2.1.0.50201-79), hipsolver (= 1.4.0.50201-79),
  rccl (= 2.11.4.50201-79), rocalution (= 2.0.2.50201-79),
  rocblas (= 2.44.0.50201-79), rocfft (= 1.0.17.50201-79),
  rocrand (= 2.10.9.50201-79), rocsolver (= 3.18.0.50201-79),
  rocsparse (= 2.2.0.50201-79)
Description: Radeon Open Compute (ROCm) Runtime software stack
Homepage: https://github.com/RadeonOpenCompute/ROCm
Maintainer: ROCm Libs Support <rocm-libs.support@amd.com>
Package: rocm-hip-libraries
Priority: optional
Section: devel
Version: 5.2.1.50201-79
Installed-Size: 13
```

**Comment by acxz** [comment]
ROCm has been using that meta package chart for a while and it seems that it is a bit dated. While someone should file some kind of report to the AMD documentation to update their meta package diagram, not sure if that is our job.

@wuxxin thanks for digging into the deb packages, based on this we'd accept a PR with updated deps correlating to the ones used in the deb packages.
