### ISSUE TITLE
[python-jax-rocm] new package

### ISSUE THREAD

**Issue by wuxxin** [rocm-arch/rocm-arch#846]
hi,
i packaged google/jax with ROCM support,
its currently available under: https://github.com/wuxxin/python-jax-rocm

i would like to move it to rocm-arch , as done with python-torchvision-rocm,
and register it with AUR.

feel free to ignore/close if this is not wanted.

**Comment by tpkessler** [comment]
Thanks! @acxz: Can you please take care of this?

**Comment by acxz** [comment]
@wuxxin sent over collaborator request for [python-jax-rocm](https://github.com/rocm-arch/python-jax-rocm)

**Comment by wuxxin** [comment]
added files to https://github.com/rocm-arch/python-jax-rocm , registered with aur, put @acxz as co-maintainer
