### ISSUE TITLE
Update of rocrand and missing "${cmake_args[@]}" in compile options

### ISSUE THREAD

**Issue by fractal-fumbler** [rocm-arch/rocm-arch#860]
Hello. 
recently i've started to get error ` hipErrorNoBinaryForGpu: Unable to find code object for all current devices`
1. started to dig down source of an error, but failed, so recompiled every dependency.
2. also checked for guide  https://docs.amd.com/bundle/Deep_learning_Guide_5.2/page/Troubleshooting.html
test passed also, since i got gfx1031 in both commands

but after i stumbled upon that error can be in rocrand and i've remembered that it was recently updated and checked for changes in PKGBUILD
 ```cpp
  CXX=/opt/rocm/hip/bin/hipcc \
  CXXFLAGS="${CXXFLAGS} -fcf-protection=none" \
  cmake -Wno-dev -S "$_dirname" \
        "${cmake_args[@]}"
  make
```
spotted that after update there is missing "${cmake_args[@]}" in compile options
 ```cpp
  cmake \
    -Wno-dev \
    -B build \
    -S "$_dirname" \
    -DCMAKE_CXX_COMPILER=/opt/rocm/hip/bin/hipcc \
    -DCMAKE_INSTALL_PREFIX=/opt/rocm \
    -DBUILD_TEST=OFF
  cmake --build build
}
```
so i've added `-DAMDGPU_TARGETS=${AMDGPU_TARGETS} \` to compile options 
and after i've installed rocrand with named addition i got success
```python
 python3                                                                                                        
Python 3.10.7 (main, Sep  6 2022, 21:22:27) [GCC 12.2.0] on linux                                                       
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True
```
please, review this report

**Comment by tpkessler** [comment]
Our GPU 6700XT is not officially supported. The old logic was removed as part of the effort to transfer the packages to the official Arch repositories.

**Comment by fractal-fumbler** [comment]
sorry to ask here, but after compiling rocrand with default PKGBUILD, i should recompile pytorch?
