### ISSUE TITLE
[rocfft] hipcc not found

### ISSUE THREAD

**Issue by nidjan** [rocm-arch/rocm-arch#861]
not build with -DCMAKE_CXX_COMPILER=hipcc 
please change to full path -DCMAKE_CXX_COMPILER=/opt/rocm/hip/bin/hipcc

**Comment by RAMChYLD** [comment]
Can confirm also happening to me. Had to modify pkgbuild file manually to make it work.

**Comment by tpkessler** [comment]
Fixed with update to 5.3.0.
