### ISSUE TITLE
rocsolver build error with fmt 9

### ISSUE THREAD

**Issue by nidjan** [rocm-arch/rocm-arch#862]
```
In file included from /var/tmp/pamac-build-chameleon/rocsolver/src/rocSOLVER-rocm-5.2.3/library/src/include/rocsolver_logger.hpp:7:

/usr/include/fmt/format.h:3122:38: error: implicit instantiation of undefined template 'fmt::detail::dragonbox::float_info'

const auto f = basic_fp<typename info::carrier_uint>(converted_value);
                                 ^
```
i build fmt7 from aur, manually replace folders&files from /opt/fmt7 to /usr, create symlink /opt/fmt7/lib/libfmt.so.7 from /opt/fmt7/lib/libfmt7.so  - and /usr/lib/libfmt.so from /usr/lib/libfmt7.so.7.1.3

and it builds

**Comment by fractal-fumbler** [comment]
please, check previous issue with fmt https://github.com/rocm-arch/rocm-arch/issues/850

**Comment by nidjan** [comment]
yes, it ok
