### ISSUE TITLE
[rocm-llvm-mlir] source folder not found

### ISSUE THREAD

**Issue by nidjan** [rocm-arch/rocm-arch#863]
first file in 'source' changed. another checksum,, another name, another path

i skip first check and change _dirname="/var/tmp/pamac-build-username/rocm-llvm-mlir/src/rocMLIR-rocm-5.3.0/"
now build

**Comment by RAMChYLD** [comment]
Having same issue. I'm having a hard time building 5.3.0 as of October 5 2022. Yay will always error out with the error that one or more files did not pass the validity check. If I run updpkgsums and makepkg manually, I get the error llvm-project-mlir-rocm-5.3.0: no such file or directory and Error: A failure occurred in prepare(). Aborting...
If I check the src dir, there is no llvm-project-mlir-rocm-5.3.0 dir but a rocMLIR-rocm-5.3.0 dir.

**Comment by tpkessler** [comment]
Fixed with update.
