### ISSUE TITLE
hipmagma not build - server lost

### ISSUE THREAD

**Issue by nidjan** [rocm-arch/rocm-arch#864]
Do you have any copy of magma-2.6.2.tar.gz?

**Comment by nidjan** [comment]
working link to source is
git clone https://bitbucket.org/icl/magma.git

please add

**Comment by nidjan** [comment]
oh. this version from bitbucket need some change in prepare(), as make.inc and make generate - and ninja build fail in the middle (about 1550 file)

i need magma-2.6.2.tar.gz --__--
This is not only my problem - https://groups.google.com/a/icl.utk.edu/g/magma-user/c/lefhRo09sVY?pli=1

**Comment by nidjan** [comment]
hmmm

`Detecting CXX OpenMP version failed with the following output:
Change Dir: /var/tmp/pamac-build-chameleon/hipmagma/src/magma-2.6.2/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/ninja cmTC_533e1 && [1/2] Building CXX object CMakeFiles/cmTC_533e1.dir/OpenMPCheckVersion.cpp.o
FAILED: CMakeFiles/cmTC_533e1.dir/OpenMPCheckVersion.cpp.o 
/opt/rocm/bin/hipcc   -march=native -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2,-D_GLIBCXX_ASSERTIONS         -Wformat         -fstack-clash-protection -fcf-protection -fcf-protection=none -std=c++11 -fopenmp=libomp -O3 -DNDEBUG -MD -MT CMakeFiles/cmTC_533e1.dir/OpenMPCheckVersion.cpp.o -MF CMakeFiles/cmTC_533e1.dir/OpenMPCheckVersion.cpp.o.d -o CMakeFiles/cmTC_533e1.dir/OpenMPCheckVersion.cpp.o -c /var/tmp/pamac-build-chameleon/hipmagma/src/magma-2.6.2/build/CMakeFiles/FindOpenMP/OpenMPCheckVersion.cpp
/var/tmp/pamac-build-chameleon/hipmagma/src/magma-2.6.2/build/CMakeFiles/FindOpenMP/OpenMPCheckVersion.cpp:6:38: error: use of undeclared identifier '_OPENMP'
                            ('0' + ((_OPENMP/100000)%10)),
                                     ^
/var/tmp/pamac-build-chameleon/hipmagma/src/magma-2.6.2/build/CMakeFiles/FindOpenMP/OpenMPCheckVersion.cpp:7:38: error: use of undeclared identifier '_OPENMP'
                            ('0' + ((_OPENMP/10000)%10)),
                                     ^
/var/tmp/pamac-build-chameleon/hipmagma/src/magma-2.6.2/build/CMakeFiles/FindOpenMP/OpenMPCheckVersion.cpp:8:38: error: use of undeclared identifier '_OPENMP'
                            ('0' + ((_OPENMP/1000)%10)),
                                     ^
/var/tmp/pamac-build-chameleon/hipmagma/src/magma-2.6.2/build/CMakeFiles/FindOpenMP/OpenMPCheckVersion.cpp:9:38: error: use of undeclared identifier '_OPENMP'
                            ('0' + ((_OPENMP/100)%10)),
                                     ^
/var/tmp/pamac-build-chameleon/hipmagma/src/magma-2.6.2/build/CMakeFiles/FindOpenMP/OpenMPCheckVersion.cpp:10:38: error: use of undeclared identifier '_OPENMP'
                            ('0' + ((_OPENMP/10)%10)),
                                     ^
/var/tmp/pamac-build-chameleon/hipmagma/src/magma-2.6.2/build/CMakeFiles/FindOpenMP/OpenMPCheckVersion.cpp:11:38: error: use of undeclared identifier '_OPENMP'
                            ('0' + ((_OPENMP/1)%10)),
                                     ^
6 errors generated when compiling for gfx803.
ninja: build stopped: subcommand failed.



Determining if the Fortran sgemm exists failed with the following output:
Change Dir: /var/tmp/pamac-build-chameleon/hipmagma/src/magma-2.6.2/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/ninja cmTC_b87df && [1/4] Building Fortran preprocessed CMakeFiles/cmTC_b87df.dir/testFortranCompiler.f-pp.f
[2/4] Generating Fortran dyndep file CMakeFiles/cmTC_b87df.dir/Fortran.dd
[3/4] Building Fortran object CMakeFiles/cmTC_b87df.dir/testFortranCompiler.f.o
[4/4] Linking Fortran executable cmTC_b87df
FAILED: cmTC_b87df 
: && /usr/bin/gfortran-11 -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -O3 -DNDEBUG -O3 CMakeFiles/cmTC_b87df.dir/testFortranCompiler.f.o -o cmTC_b87df   && :
/usr/bin/ld: CMakeFiles/cmTC_b87df.dir/testFortranCompiler.f.o: в функции «main»:
testFortranCompiler.f:(.text.startup+0x1d): неопределённая ссылка на «sgemm_»
collect2: ошибка: выполнение ld завершилось с кодом возврата 1
ninja: build stopped: subcommand failed.`

**Comment by nidjan** [comment]
omg
in 2.6.2 not target gfx803

---

i install hipmagma from arch4edu repo -__-

**Comment by tpkessler** [comment]
For hipmagma, please open an issue at https://github.com/rocm-arch/hipmagma/issues
