### ISSUE TITLE
Unable to use GPU with Pytorch.

### ISSUE THREAD

**Issue by DeeparthGupta** [rocm-arch/rocm-arch#866]
I have the RX580 gpu that I was hoping to use as the gpu target in Pytorch. I've enabled the `ROC_USE_PRE_VEGA` flag after installing ROCm as per the instructions in the readme. The operating system is Arch linux.

I run the following code from the pytorch website to test the GPU target:
`import torch
torch.cuda.is_available()`

It ends with the following error:
`/opt/amdgpu/share/libdrm/amdgpu.ids: No such file or directory
/opt/amdgpu/share/libdrm/amdgpu.ids: No such file or directory  
"hipErrorNoBinaryForGpu: Unable to find code object for all current devices!"  
fish: Job 1, 'python ./test.py' terminated by signal SIGABRT (Abort)`

I've attached the ROCm info output
[rocminfo-output.txt](https://github.com/rocm-arch/rocm-arch/files/9721199/rocminfo-output.txt)

**Comment by nidjan** [comment]
you also need set environment variables GPU_TARGET and AMDGPU_TARGET to gfx803

and maybe also some change in PKGBUILD to rocblas (now i tst it) - 

```
local cmake_args=(-DCMAKE_INSTALL_PREFIX=/opt/rocm
                    -DCMAKE_PREFIX_PATH=/opt/rocm/llvm/lib/cmake/llvm
                    -Damd_comgr_DIR=/opt/rocm/lib/cmake/amd_comgr
                    -DBUILD_WITH_TENSILE=ON
                    -DBUILD_WITH_TENSILE_HOST=ON
        		    -DBUILD_CLIENTS_TESTS=OFF
                    -DBUILD_CLIENTS_BENCHMARKS=OFF
                    -DBUILD_CLIENTS_SAMPLES=OFF
                    -DTensile_LIBRARY_FORMAT=yaml
                    -DTensile_COMPILER=hipcc
                    -DTensile_LOGIC=asm_full
                    -DTensile_ARCHITECTURE=gfx803
                    -DTensile_TEST_LOCAL_PATH="$_tensile_dir"
                    -DTensile_CPU_THREADS="$_tensile_threads"
                    -DTensile_CODE_OBJECT_VERSION=V3
                    -DCMAKE_TOOLCHAIN_FILE=toolchain-linux.cmake
                    -DBUILD_TESTING=OFF)

```

**Comment by DeeparthGupta** [comment]
I downloaded and installed existing binaries via `pacaur -S rocm-hip-sdk rocm-opencl-sdk`. Are you saying I should build it instead?

**Comment by nidjan** [comment]
Install from aur this package == build it)
pls run
`
env ROC_USE_PRE_VEGA=1 ROCM_HOME=/opt/rocm/ AMDGPU_TARGET=gfx803 pacaur -S rocm-hip-sdk rocm-opencl-sdk
`
and maybe itworks

**Comment by DeeparthGupta** [comment]
That didn't work. I have the same error.

**Comment by nidjan** [comment]
i also install from aur python-pytorch-rocm
and then torch works
BUT Stable Diffusion catch more than 20 errors(

**Comment by tpkessler** [comment]
Support for your GPU was dropped long ago (back in ROCm 2.x), so there's litte / no hope that you may run pytorch with it.

**Comment by xuhuisheng** [comment]
@DeeparthGupta 
You can try this pre-built pytorch on gfx803.
<https://github.com/xuhuisheng/rocm-gfx803>
