### ISSUE TITLE
hsa-rocr 5.3.0: error during compilation

### ISSUE THREAD

**Issue by RAMChYLD** [rocm-arch/rocm-arch#875]
When trying to compile hsa-rocr 5.3.0, errors occur and fails. Attached is the error. 

`
leecy@mia:~/.cache/yay/hsa-rocr$ makepkg
==> Making package: hsa-rocr 5.3.0-1 (Tue 11 Oct 2022 10:22:49 PM +08)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found hsa-rocr-5.3.0.tar.gz
==> Validating source files with sha256sums...
    hsa-rocr-5.3.0.tar.gz ... Passed
==> Extracting sources...
  -> Extracting hsa-rocr-5.3.0.tar.gz with bsdtar
==> Removing existing $pkgdir/ directory...
==> Starting build()...
Using CPACK_DEBIAN_PACKAGE_RELEASE local
RESULT_VARIABLE 0 OUTPUT_VARIABLE: 
CPACK_RPM_PACKAGE_RELEASE: local%{?dist}
-- Configuring done
-- Generating done
-- Build files have been written to: /home/leecy/.cache/yay/hsa-rocr/src/build
[  1%] BUILDING bitcode for ocl_blit_object_gfx1100...
[  2%] BUILDING bitcode for ocl_blit_object_gfx1102...
[  3%] BUILDING bitcode for kCodeTrapHandlerV2_11...
[  4%] BUILDING bitcode for ocl_blit_object_gfx1036...
[  5%] BUILDING bitcode for ocl_blit_object_gfx1103...
[  5%] Built target link_libhsa-runtime64.so
[  5%] Built target link_libhsa-runtime64.so.1
clang-14: error: invalid target ID 'gfx1102'; format is a processor name followed by an optional colon-delimited list of features followed by an enable/disable sign (e.g., 'gfx908:sramecc+:xnack-')
clang-14: error: invalid target ID 'gfx1103'; format is a processor name followed by an optional colon-delimited list of features followed by an enable/disable sign (e.g., 'gfx908:sramecc+:xnack-')
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:168: image/blit_src/ocl_blit_object_gfx1102] Error 1
make[2]: *** Waiting for unfinished jobs....
clang-14: error: invalid target ID 'gfx1036'; format is a processor name followed by an optional colon-delimited list of features followed by an enable/disable sign (e.g., 'gfx908:sramecc+:xnack-')make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:173: image/blit_src/ocl_blit_object_gfx1103] Error 1

make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:158: image/blit_src/ocl_blit_object_gfx1036] Error 1
clang-14: error: invalid target ID 'gfx1100'; format is a processor name followed by an optional colon-delimited list of features followed by an enable/disable sign (e.g., 'gfx908:sramecc+:xnack-')
clang-14: error: invalid target ID 'gfx1100'; format is a processor name followed by an optional colon-delimited list of features followed by an enable/disable sign (e.g., 'gfx908:sramecc+:xnack-')
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:163: image/blit_src/ocl_blit_object_gfx1100] Error 1
make[1]: *** [CMakeFiles/Makefile2:335: image/blit_src/CMakeFiles/opencl_blit_objects.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [core/runtime/trap_handler/CMakeFiles/amd_trap_handler_v2.dir/build.make:112: core/runtime/trap_handler/kCodeTrapHandlerV2_11.hsaco] Error 1
make[1]: *** [CMakeFiles/Makefile2:309: core/runtime/trap_handler/CMakeFiles/amd_trap_handler_v2.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
`

**Comment by tpkessler** [comment]
Duplicate #870. Please try to build the package in a clean chroot. See the readme for more information.
