### ISSUE TITLE
Use paru to install but got different providers.

### ISSUE THREAD

**Issue by aoxipo** [rocm-arch/rocm-arch#877]
hello i am trying to use paru to install rocm in ubuntu aarch64 but i got 
'''
:: Resolving dependencies...
:: There are 2 providers available for rocm-hip-sdk:
:: Repository AUR:
    1) rocm-hip-sdk  2) opencl-amd-dev
Enter a number (default=1):
'''
did i need follow a specific sequence to install ?

**Comment by petronny** [comment]
Does rocm or rocm-arch support aarch64 now?

**Comment by aoxipo** [comment]
> Does rocm or rocm-arch support aarch64 now?

did you mean's rocm-arch didn't support aarch64?

**Comment by petronny** [comment]
Currently all PKGBUILDs in this repository only set `arch=('x86_64')`.

**Comment by petronny** [comment]
Also installing arch packages on ubuntu is quite wierd.

**Comment by aoxipo** [comment]
i thought 'ROCm for Arch Linux' mean's rocm support arch64  :-(, i 'll close this iusse after this comment

**Comment by aoxipo** [comment]
> Also installing arch packages on ubuntu is quite wierd.

Do you have any suggestions for install rocm with os:Ubuntu, arch:aarch64  ?

**Comment by petronny** [comment]
In https://github.com/RadeonOpenCompute/ROCm/issues/1529

> ROCm supports x86(x86_64) architecture officially. We do not have official support for aarch64.

So I don't think it's even possible.
