### ISSUE TITLE
AUR: Warn user when unsupported cflags are enabled

### ISSUE THREAD

**Issue by ScoreUnder** [rocm-arch/rocm-arch#888]
To save the trouble of building for a while and getting an error at the end (#789), would it be possible to get a warning at the start of the PKGBUILD build step if unsupported options are present in the CFLAGS/CPPFLAGS/(if applicable)CXXFLAGS?

example:

```bash
case "$CFLAGS $CPPFLAGS $CXXFLAGS" in
    -fstack-protector*)
        warning 'The stack protector is not supported in rocm, you may need to adjust C*FLAGS for this build to work'
        ;;
esac
```

**Comment by fabiscafe** [comment]
IMHO That would require a lot of extra work all around. The pkgbuild should be tuned to build in a clean chroot, set up by [devtools](https://gitlab.archlinux.org/archlinux/devtools/-/blob/master/config/makepkg/x86_64.conf). It should absolutely not try to workaround user-specific settings.

That said, I'm not sure about warnings, but I think the pkgbuild is still not the best place for this.

**Comment by ScoreUnder** [comment]
I see what you mean, though I think the majority of users will be using an AUR wrapper or makepkg itself, which do not use clean chroots to build. I don't think building in a chroot is common knowledge among casual AUR users.

**Comment by fabiscafe** [comment]
Sure, still you're expected to know how to build without helper. If you can't, maybe you shouldn't go for Arch just now. Please see: https://wiki.archlinux.org/title/Arch_Linux - [https://wiki.archlinux.org/title/Frequently_asked_questions#Why_would_I_not_want_to_use_Arch?](https://wiki.archlinux.org/title/Frequently_asked_questions#Why_would_I_not_want_to_use_Arch?)

There are a few packages, like tooling - [glibc](https://github.com/archlinux/svntogit-packages/blob/packages/glibc/trunk/PKGBUILD#L74) who exclude build flags, but here again these are or where default flags.

I'm against changing things for users ease to build on the distribution end. This should always go either upstream or set by the user themself.
