### ISSUE TITLE
[rocm-device-libs] Files missing in comparison to deb

### ISSUE THREAD

**Issue by ranisalt** [rocm-arch/rocm-arch#89]
Comparing the contents of `rocm-device-libs` deb vs Arch:

`rocm-device-libs` dev contents, marked if present in our package:
- [ ] /opt/rocm/include/amd_hsa_common.h
- [ ] /opt/rocm/include/amd_hsa_elf.h
- [ ] /opt/rocm/include/amd_hsa_kernel_code.h
- [ ] /opt/rocm/include/amd_hsa_queue.h
- [ ] /opt/rocm/include/amd_hsa_signal.h
- [ ] /opt/rocm/include/as.h
- [ ] /opt/rocm/include/device_amd_hsa.h
- [ ] /opt/rocm/include/hsa.h
- [ ] /opt/rocm/include/ockl.h
- [ ] /opt/rocm/include/ockl_hsa.h
- [ ] /opt/rocm/include/ocml.h
- [x] /opt/rocm/lib/cmake/AMDDeviceLibs/AMDDeviceLibsConfig.cmake
- [x] /opt/rocm/lib/hc.amdgcn.bc
- [x] /opt/rocm/lib/hip.amdgcn.bc
- [x] /opt/rocm/lib/ockl.amdgcn.bc
- [x] /opt/rocm/lib/oclc_correctly_rounded_sqrt_off.amdgcn.bc
- [x] /opt/rocm/lib/oclc_correctly_rounded_sqrt_on.amdgcn.bc
- [x] /opt/rocm/lib/oclc_daz_opt_off.amdgcn.bc
- [x] /opt/rocm/lib/oclc_daz_opt_on.amdgcn.bc
- [x] /opt/rocm/lib/oclc_finite_only_off.amdgcn.bc
- [x] /opt/rocm/lib/oclc_finite_only_on.amdgcn.bc
- [x] /opt/rocm/lib/oclc_isa_version_700.amdgcn.bc
- [x] /opt/rocm/lib/oclc_isa_version_701.amdgcn.bc
- [x] /opt/rocm/lib/oclc_isa_version_702.amdgcn.bc
- [x] /opt/rocm/lib/oclc_isa_version_801.amdgcn.bc
- [x] /opt/rocm/lib/oclc_isa_version_802.amdgcn.bc
- [x] /opt/rocm/lib/oclc_isa_version_803.amdgcn.bc
- [x] /opt/rocm/lib/oclc_isa_version_810.amdgcn.bc
- [x] /opt/rocm/lib/oclc_isa_version_900.amdgcn.bc
- [x] /opt/rocm/lib/oclc_isa_version_902.amdgcn.bc
- [x] /opt/rocm/lib/oclc_isa_version_904.amdgcn.bc
- [x] /opt/rocm/lib/oclc_isa_version_906.amdgcn.bc
- [x] /opt/rocm/lib/oclc_unsafe_math_off.amdgcn.bc
- [x] /opt/rocm/lib/oclc_unsafe_math_on.amdgcn.bc
- [x] /opt/rocm/lib/ocml.amdgcn.bc
- [x] /opt/rocm/lib/opencl.amdgcn.bc

Our package contents not present in `rocm-device-libs` deb:
- /opt/rocm/lib/oclc_isa_version_908.amdgcn.bc
- /opt/rocm/lib/oclc_wavefrontsize64_off.amdgcn.bc
- /opt/rocm/lib/oclc_wavefrontsize64_on.amdgcn.bc

These are probably due to us picking up updates faster than repositories deliver them, clear by the first file referring to newer GPUs.

**Comment by acxz** [comment]
Based on my list [here](https://github.com/rocm-arch/rocm-arch/files/4441142/rocm-installation.txt), we have all the files we need in this package. I believe we can close this issue.
