### ISSUE TITLE
[hsa-rocr] error: invalid target ID 'gfx1036';

### ISSUE THREAD

**Issue by mikdmst1** [rocm-arch/rocm-arch#894]
[ 26%] BUILDING bitcode for ocl_blit_object_gfx1036...
clang-14: error: invalid target ID 'gfx1036'; format is a processor name followed by an optional colon-delimited list of features followed by an enable/disable sign (e.g., 'gfx908:sramecc+:xnack-')
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:158: image/blit_src/ocl_blit_object_gfx1036] Ошибка 1
make[1]: *** [CMakeFiles/Makefile2:335: image/blit_src/CMakeFiles/opencl_blit_objects.dir/all] Ошибка 2
make: *** [Makefile:156: all] Ошибка 2
==> ОШИБКА: Произошел сбой в build().
    Прерывание...
 -> ошибка сборки: hsa-rocr

Ryzen 5900x
MSI Radeon 5700XT

need Blender Cycles HIP Rendering - broken now

**Comment by mikdmst1** [comment]
help pls!

**Comment by fabiscafe** [comment]
See https://github.com/rocm-arch/rocm-arch#package-x-does-not-build-on-os-y
