### ISSUE TITLE
[llvm-roc] Need makedepends `diffutils`

### ISSUE THREAD

**Issue by helloworld1** [rocm-arch/rocm-arch#90]
Without dependency on diffutils, the build will fail on running unit tests.
We should either disable running unit tests or add diffutils make dependency.

**Comment by ranisalt** [comment]
`diffutils` is required by `autoconf` which is part of `base-devel`, and `base-devel` dependencies [are assumed to be installed](https://wiki.archlinux.org/index.php/PKGBUILD#makedepends):

> **Note:** The group `base-devel` is assumed to be already installed when building with *makepkg*. Members of this group should not be included in `makedepends` array.`
