### ISSUE TITLE
[rocminfo] Missing libhsa-ext-finalize64.so.1and libhsa-ext-image64.so.1

### ISSUE THREAD

**Issue by tpkessler** [rocm-arch/rocm-arch#92]
Executing `rocminfo 3.3.0` I get the following warning:

```
LoadLib(libhsa-ext-finalize64.so.1) failed: libhsa-ext-finalize64.so.1: cannot open shared object file: No such file or directory
LoadLib(libhsa-ext-image64.so.1) failed: libhsa-ext-image64.so.1: cannot open shared object file: No such file or directory
```
The library `libhsa-ext-image64.so` is part of `hsa-ext-rocr`. However, I cannot find a package that ships `libhsa-ext-finalize64`. It seems like AMD removed it with ROCm 1.9, see [here](https://github.com/RadeonOpenCompute/ROCm/issues/537#issuecomment-421691921).
In older versions of ROCm, this library was part of `libhsakmt`, see a comment on the [AUR](https://aur.archlinux.org/packages/libhsakmt-git/).

**Comment by acxz** [comment]
Can you post the output of running rocminfo with `hsa-ext-rocr`? I believe we may need to bring this issue upstream. If you could post an upstream issue, if the issue still persists and link it here that would be great!

**Comment by tpkessler** [comment]
I believe that this is an upstream issue, too. I took a look at the file list you linked in #86. AMD's packages do not include `libhsa-ext-finalize64.so`.

Running `rocminfo` with `hsa-ext-rocr` results in
```
$ rocminfo > /dev/null
LoadLib(libhsa-ext-finalize64.so.1) failed: libhsa-ext-finalize64.so.1: cannot open shared object file: No such file or directory
```

**Comment by acxz** [comment]
I see well then I guess we need to bring this up to the ROCm devs. Thx for looking into this!

**Comment by tpkessler** [comment]
I've opened an issue upstream:

https://github.com/RadeonOpenCompute/ROCR-Runtime/issues/89

**Comment by tpkessler** [comment]
This warning is only visible with a debug build. See my PR #112
