### ISSUE TITLE
[hsa-rocr] cannot build due to missing hsakmt-roct>=3.3.0

### ISSUE THREAD

**Issue by kozross** [rocm-arch/rocm-arch#94]
When trying to update today, I got this:

```
==> hsa-rocr dependencies:
 - cmake (already installed) [makedepend]
 - libelf (already installed) [makedepend]
 - hsakmt-roct>=3.3.0 (building from AUR) [makedepend]


==> Continue building hsa-rocr ? [Y/n]
==> ----------------------------------
==>
==> Building and installing package
==> Install or build missing dependencies for hsa-rocr:
error: target not found: hsakmt-roct>=3.3.0
```

**Comment by acxz** [comment]
Thx for the reports as always @kozross!

**Comment by acxz** [comment]
Need to sync with an `aurpublish hsa-rocr` @neeshy @ranisalt

**Comment by ranisalt** [comment]
I don't have access to it, @neeshy is the only maintainer.

**Comment by acxz** [comment]
You (rsa) are listed as a co-maintainer: https://aur.archlinux.org/packages/hsa-rocr/

**Comment by ranisalt** [comment]
But hsa-rocr is up to date, hsakmt-roct is the problem here

**Comment by acxz** [comment]
See the latest commit on has-rocr. My bad should have created a PR or linked the commit here to get more visibility.
The versioned dep has been removed in this package.

**Comment by ranisalt** [comment]
Ah, sorry. Done, then.
