### ISSUE TITLE
[miopen-opencl] MIOPEN_LOG_LEVEL should be set to 4

### ISSUE THREAD

**Issue by FranGamer1892** [rocm-arch/rocm-arch#952]
Hello, MIOpen from the rocm arch repositories has MIOPEN_LOG_LEVEL set to 5 by default. This makes it impossible to read any output since it gets flooded with info messages. According to [this](https://rocmsoftwareplatform.github.io/MIOpen/doc/html/DebugAndLogging.html), MIOPEN_LOG_LEVEL should be set to 4, as it is a release. Thank you.

**Comment by Mushoz** [comment]
Is there a way to fix this right now instead of having to wait for a new version? I have tried setting the `MIOPEN_LOG_LEVEL` environment variable, but it seems to be ignored. My logs are still getting spammed and I have no way of seeing the actual relevant information.

**Comment by FranGamer1892** [comment]
Hello, that's weird, it works for me.

MIOPEN_LOG_LEVEL=4 python run.py ...

**Comment by tpkessler** [comment]
This is fixed for miopen-hip in the arch repos (currently in staging, soon in testing and then in extra)
https://gitlab.archlinux.org/archlinux/packaging/packages/miopen-hip/-/blob/main/PKGBUILD#L39

**Comment by FranGamer1892** [comment]
Great news!

**Comment by ZappaBoy** [comment]
FYI right today the version `5.6` of `rocm` has been released on `rocm-arch` on the Arch Linux `extra` repository solving this issue. 
I think that this issue can be closed now.

**Comment by tpkessler** [comment]
Thanks for your feedback!
