### ISSUE TITLE
Switch to binary instead Perl scripts by HIP_USE_PERL_SCRIPTS=0

### ISSUE THREAD

**Issue by perestoronin** [rocm-arch/rocm-arch#963]
Please switch rocm 5.5.0 by default to binary instead deprecated Perl scripts by HIP_USE_PERL_SCRIPTS=0
https://github.com/ROCm-Developer-Tools/HIPCC
https://github.com/ROCm-Developer-Tools/HIP

**Comment by tpkessler** [comment]
The default config is still to use perl scripts.
